### ISSUE TITLE
Option to change files working with Memos (not just default Daily Note)

### ISSUE THREAD

**Issue by kalmir** [Quorafind/Obsidian-Thino#102]
I like to use default Daily Notes (XXXX-XX-XX) as a central repository which draws data (via embedding) from other related files: e.g. tasks from XXXX-XX-XX_tasks or journal notes from XXXX-XX-XX_journal. 

Similarly, it would be great if I could configure Memos to work with **XXXX-XX-XX_memos** files instead of the default daily notes.

---
Memos is a great plug-in, thanks, bought you some coffee as thanks for your effort.

**Comment by Quorafind** [comment]
Would you like have a template for this XXXX-XX-XX_memos ? Like daily note template used to generate daily note. Thanks for your coffee 💜

**Comment by kalmir** [comment]
At the moment a blank file would work perfectly ok.

But having a possibility to use a template would be a nice bonus. It would help to filter out memos from searches via yaml tags and such.

**Comment by alanlee127** [comment]
+1，我习惯用 YYYY-MM 作为每月日记，而不是 YYYY-MM-DD 的每日日记。但当我在日记插件中设置格式为 YYYY-MM 时，打开 memos 会报错（fetch error）。希望能自由配置插入 memos 的文件名称格式。

**Comment by Quorafind** [comment]
> +1，我习惯用 YYYY-MM 作为每月日记，而不是 YYYY-MM-DD 的每日日记。但当我在日记插件中设置格式为 YYYY-MM 时，打开 memos 会报错（fetch error）。希望能自由配置插入 memos 的文件名称格式。

在这个基础上，由于 Memos 是基于每日的标题+对应的时间戳来识别 Memo 的时间的，如果是考虑 YYYY-MM 的话，你可以接受文本中带有 DD-HH:mm 这样的时间戳作为起始标志符吗
例如： - 01-10:20 working @alanlee127

**Comment by alanlee127** [comment]
> > +1，我习惯用 YYYY-MM 作为每月日记，而不是 YYYY-MM-DD 的每日日记。但当我在日记插件中设置格式为 YYYY-MM 时，打开 memos 会报错（fetch error）。希望能自由配置插入 memos 的文件名称格式。
> 
> 在这个基础上，由于 Memos 是基于每日的标题+对应的时间戳来识别 Memo 的时间的，如果是考虑 YYYY-MM 的话，你可以接受文本中带有 DD-HH:mm 这样的时间戳作为起始标志符吗 例如： - 01-10:20 working @alanlee127

可以呀！至少能用了哈哈。当然如果后面能优化一下就更好啦~

**Comment by 7enChan** [comment]
我有另外一个想法，就是每条 memo 都创建一个以当前时间戳命名的文件，类似 202202061212，memo 的时间直接读取文件名即可。

这样做的好处是从 memo 之外的地方创建笔记不需要再添加时间戳， 因为每条memo一个文件，memo 的格式也不再受限制，另外也就不用担心不同终端同步不及时造成冲突的问题（因为每次都是新建一个文件）。

我之前有参考这篇文章做了闪念笔记的workflow，问题就是不容易回看，但如果能与 memo 结合的话就不再有这个问题了：https://forum.obsidian.md/t/obsidian-gems-of-the-year-2021-nomination-workflows/28227/15

**Comment by red-co** [comment]
> 我有另外一个以我的名字命名的每条202202220222212，就是我的每条消息，即是我的目录，222022212，就是我的每条消息，即是我的名字。
> 
> 危害的好处是
> 
> * 不再依赖插件，也不再影响日历的依赖功能
> * 备忘录 在不需要的地方创建不需要再添加笔记之外的地方
> * 备忘录的格式也不再受限制
> * 不用担心不同的终端同步不会造成及时的问题。
> 
> 我之前有看这篇文章但没有做这个念闪笔记的工作流程，问题就是不容易与备忘录结合的话就不再有：[https://forum.obsidian.md/t/obsidian- 2021 年度宝石提名工作流程/28227/15](https://forum.obsidian.md/t/obsidian-gems-of-the-year-2021-nomination-workflows/28227/15)

aidenlx 他的folder插件给了一个新的代码块，可以做这件事情，

**Comment by Quorafind** [comment]
Can you try the ver 1.9.0 and set dataview query for these files?
