### ISSUE TITLE
Better support for multi-line input and display

### ISSUE THREAD

**Issue by AiurArtanis** [Quorafind/Obsidian-Thino#108]
@Quorafind 
---
### multi-line input/display enhancement
i usually create a new memo through writting in daily notes directly (cause creating memos through **ob-memos** based on the memos-view). then i find it difficult to input multi-line content and i have to add the `<br>` tag after each line. i wish **ob-memos** is able to recognize Intelligently the content from the `- HH:mm` to next section instead of one line.

### other markdown syntax support
these syntaxes won't be displayed normally for lack of multi-line support
- code block:
![image](https://user-images.githubusercontent.com/98091664/152649385-0fe0b157-8310-4fd1-a4c8-4d5d188475eb.png)

- quote block:
![image](https://user-images.githubusercontent.com/98091664/152649436-db5ac0c1-8d32-4676-aa6f-7fac1199f178.png)

- table:
![image](https://user-images.githubusercontent.com/98091664/152649624-b29cc63f-6fcb-4e04-842b-1ca141db48b9.png)
![image](https://user-images.githubusercontent.com/98091664/152649681-8cb913f0-4ee2-4c55-af4a-40caaa464096.png)

## Environment

os: win10
ob: v0.13.23
ob-memos: 1.7.14

## Last

**ob-memos** is quite a useful plugin, and i hope for your reply asap😊

**Comment by Quorafind** [comment]
Sorry for reply so late! Will add this feature when I found a good way to manage text and block(from markdown

**Comment by Quorafind** [comment]
I'm very sorry for not replying to you for so long. The latest version of Thino (Obsidian Memos) now supports this feature.

**Comment by javiavid** [comment]
Is multi-line possible without <br> in the latest version? 
This is one of the reasons why I stopped using the plugin.

**Comment by AiurArtanis** [comment]
> Is multi-line possible without <br> in the latest version? This is one of the reasons why I stopped using the plugin.

i just created a new note in Memos(Thino) and it does implement with <br> in Source Mode

**Comment by Quorafind** [comment]
Fixed.

**Comment by Quorafind** [comment]
> Is multi-line possible without `<br>` in the latest version? This is one of the reasons why I stopped using the plugin.

It has been removed. No more `<br>`

**Comment by javiavid** [comment]
Thanks for solving it.
I have tried it and it is better, but would it be possible that the text is not tabulated?
I think it is easier to be able to edit the text as you would in obsidian by default, so it is easier to edit the text, copy it...
