### ISSUE TITLE
与 Templater 的结合

### ISSUE THREAD

**Issue by lifesign** [Quorafind/Obsidian-Thino#112]
你好，我是使用 Templater 进行 Daily Notes 的生成，利用 Templater 监控文件夹的功能。但是在使用 memos，如果没有生成当日的 Daily Notes，memos 会直接覆盖当日的 Daily Notes，能否让 memos 的触发也满足 Templater 的条件

希望的两个场景
1. 先打开 Daily Notes，这个时候已经有 memo 的位置了，比如 ## memo，此时通过 memo 写入应该是 ok 的
2. 不打开 Daily Notes，先打开 memo 记录，此时 memo 自动触发 Templater 的机制生成当日的 Daily Notes 后，在进行写入

**Comment by Quorafind** [comment]
这里有一个需要您解释的地方，您设置的&nbsp;Templater&nbsp;监控文件夹生成的对应日记文件的文件名是否与日记插件设置的文件名是否一样，然后日记插件是否开启了，因为按正常的程序运行走的话，它是优先检测你是否已经生成当天的日记（如果没有开启日记插件的话，会默认为 YYYY-MM-DD 文件），如果没有，才会新建一个对应的文件。而如果你是希望它输入后，自动在 Templater 文件下新建一个对应的(日记)文件，然后等待 Templater 填充内容后再插入内容，那么你可以先考虑尝试设置一个空白的日记模板，然后利用自带的日记插件来修复。&nbsp;


HeJianhong
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月10日(星期四) 上午10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Quorafind/Obsidian-Memos] 与 Templater 的结合 (Issue #112)





 
你好，我是使用 Templater 进行 Daily Notes 的生成，利用 Templater 监控文件夹的功能。但是在使用 memos，如果没有生成当日的 Daily Notes，memos 会直接覆盖当日的 Daily Notes，能否让 memos 的触发也满足 Templater 的条件
 
希望的两个场景
  
先打开 Daily Notes，这个时候已经有 memo 的位置了，比如 ## memo，此时通过 memo 写入应该是 ok 的
 
不打开 Daily Notes，先打开 memo 记录，此时 memo 自动触发 Templater 的机制生成当日的 Daily Notes 后，在进行写入

**Comment by lifesign** [comment]
你好，我的日记插件是开启的，同时日记插件下没有模板，因为利用了 Templater 的监控文件夹能力。我发下我几个插件的配置

日记：
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/2189610/153528295-3bd5c818-e4f1-4e38-9b50-ea8303719c52.png">


Templater：
<img width="946" alt="image" src="https://user-images.githubusercontent.com/2189610/153528325-6b3ed555-adeb-4941-9805-c0c3bb26f50a.png">

Memo：
<img width="962" alt="image" src="https://user-images.githubusercontent.com/2189610/153528345-491c24b6-f7eb-4084-b770-af4aa59f4476.png">

在这样的配置下，我直接打开 memo 创建一条，生成的结果是这样的，看起来就直接写入了一个条目，即没有触发日记的模板生成，也没有写入到 ### memo 下

<img width="442" alt="image" src="https://user-images.githubusercontent.com/2189610/153528377-48dd1afd-436f-4a03-adc0-cc57f5a1fbe3.png">
