### ISSUE TITLE
设置flomo API

### ISSUE THREAD

**Issue by frja1234** [Quorafind/Obsidian-Thino#119]
希望可以嵌入flomo的api，这样就可以设置好key后，将内容提交到flomo里面了，不设置的话就只提交到本地，flomo api就只是一个post请求，将写的内容填入提交就可以。对于flomo用户来说是非常赞的

**Comment by Quorafind** [comment]
这个需求我应该不会主动实现，因为我并没有 flomo 高级版也并没有打算付费，可以等待其它的社区用户贡献
