### ISSUE TITLE
试用下面的几个小建议，供参考：

### ISSUE THREAD

**Issue by vimbackground** [Quorafind/Obsidian-Thino#122]
需求：
1. 时段检索：内容检索希望能支持时段检索，即查看类似2022.01.01-2022.01.07的内容
2. 更好的Markdown支持：希望memo页面的编辑功能，能加一些简单的编辑按钮（或者快捷键支持），加粗、列表、引用啥的，虽然语法不难记，多少方便一些。另外，列表的渲染希望能也实现一下。

Bug：
1.  长内容bug：当编辑的某条memo长过一屏时，下方的提交按钮就点不了的，整个编写无法再继续。（——希望能提供一个侧面的滚动条，或者把提交按钮移到上方，或者其它解决方案）
2. 无法显示空行：这个不清楚算是bug还是需求，现在用<br>换行，不管加了几个<br>都没有空行出现，同时是内容较长时，阅读体验挺差。

暂时这些，有想法再补充

**Comment by Quorafind** [comment]
关于需求1和长内容bug，会做会修复。关于快捷键的问题，我在等 ob 开放编辑器实例，从而利用 ob 自带的编辑器再加工具条，所以现在不会做重复工作，空行的bug后续会看一下

**Comment by vimbackground** [comment]
谢谢回复。补两条：

1. 希望能提供标签的专门的快速搜索功能，最好能实现多标签的and/or/not筛选——对于用多标签分类memo内容的场景很实用，似乎检索式能实现类似功能，但是很不直观。
2. 希望左上角日历区的提示信息能显示为中文——目前是类似“x memos on Tue Jan 11 2002”这样的提示，对国人不太直观
2. 希望左下角的常用标签能够提供不同的排序功能（顺序、频次等）——直观一些，不用跳到软件的标签面板去操作

**Comment by Quorafind** [comment]
第一条，可以用筛选器，固定几个常用的下来就好了，其它的先考虑下，不一定会做
