### ISSUE TITLE
Autosave 

### ISSUE THREAD

**Issue by oak86** [Quorafind/Obsidian-Thino#123]
Problem:
Longer passages aren't auto-saved, leading to occasionally losing entries.

This mostly happens because I'll start writing something short and wind up having more to say, so I keep typing. Then I go to click something in Obsidian and close Memos. When I return to Memos, what I typed is gone.

Proposed Solution:
I'd love if what I type gets autosaved. This is *especially* handy on mobile, where the screen is smaller and the ability to open a page in a separate pane just isn't convenient.

**Comment by Quorafind** [comment]
I will add a autosave feature in next version

**Comment by Quorafind** [comment]
I'm very sorry for not replying to you for so long. The latest version of Thino (Obsidian Memos) now supports this feature.
