### ISSUE TITLE
[Request] ability to use memo shortcuts if pinned to sidebar

### ISSUE THREAD

**Issue by rushikb** [Quorafind/Obsidian-Thino#126]
I've found that a really nice way to use memos plugin is to keep it as a pinned pane within the sidebars. (screenshot below)
![CleanShot 2022-02-16 at 06 55 26](https://user-images.githubusercontent.com/6484525/154163837-4892b70e-c932-4d8e-b993-2002ac0ed2e1.png)

Doing this however makes it impossible to to access the memo pane via command palette. is there a way to circumvent this or do you recommend that memos should never be pinned within the sidebars?

**Comment by Quorafind** [comment]
I remember that shortcut should work, let me try it. If I found a bug, I will tell you

**Comment by Quorafind** [comment]
Do you mean the hotkey from Memos? I tested it and it worked correctly

**Comment by red-co** [comment]
> 我发现使用备忘录插件的一种非常好的方法是将其作为固定窗格保留在侧边栏中。（下面的截图） ![CleanShot 2022-02-16 在 06 55 26](https://user-images.githubusercontent.com/6484525/154163837-4892b70e-c932-4d8e-b993-2002ac0ed2e1.png)
> 
> 但是，这样做会导致无法通过命令面板访问备忘录窗格。有没有办法避免这种情况，或者您是否建议永远不要将备忘录固定在侧边栏中？

Interesting usage, I tried, it can be moved to the right sidebar, but when I use the hotkey, it will go back to the middle and,
 it cannot be fixed, but you can open it(by hotkey) as a pane and resize it to the size you want, (the workspace can save the window size),
很有趣的用法，我尝试了，它可以被移动到右侧边栏，但是只要我使用hotkey，它就会重新回到中间，无法固定，但是你可以把它作为一个窗格打开(hotkey)，然后调整到你想要的大小，(工作区可以保存窗口大小)

**Comment by red-co** [comment]
> I've found that a really nice way to use memos plugin is to keep it as a pinned pane within the sidebars. (screenshot below) ![CleanShot 2022-02-16 at 06 55 26](https://user-images.githubusercontent.com/6484525/154163837-4892b70e-c932-4d8e-b993-2002ac0ed2e1.png)
> 
> Doing this however makes it impossible to to access the memo pane via command palette. is there a way to circumvent this or do you recommend that memos should never be pinned within the sidebars?

Interesting usage, I tried, it can be moved to the right sidebar, but as soon as I use the hotkey, it will go back to the middle ...
it cannot be fixed, but you can open(by hotkey) it as a pane and resize it to the size you want, (the workspace can save the window size)

**Comment by red-co** [comment]
> Do you mean the hotkey from Memos? I tested it and it worked correctly

The memo page can be moved to the right sidebar, but using the hotkey (command panel) will cause it to  back to the main page, which he may want to be opened memo by the hotkey when the memo is in the sidebar, rather than returning memo to the main page

**Comment by rushikb** [comment]
+1 to @red-co 's point above. @Quorafind — sorry, let me clarify. After adding the memos pane to the sidebar. I'm able to use the command for "open memos" — which moves the pane back to main page. However, I can't use the command for "note it". This is a very trivial thing however.

**Comment by Quorafind** [comment]
But I am able to use the command to note it 😂 `Ctrl+Enter` and the command `Obsidian-Memos: Note it` both works. And I can add an command to allow open memos in the sidebar.

**Comment by Quorafind** [comment]
Got fixed.
