### ISSUE TITLE
手机移动端的记录叠在一起无法显示

### ISSUE THREAD

**Issue by sparkyen** [Quorafind/Obsidian-Thino#128]
电脑上使用是没有问题的，但是手机上面的每条小的记录多了之后就会出现全部叠加在一起的情况，使用体验很糟糕
  
![SC3Q8K(UNTAWA()RGR %K2M](https://user-images.githubusercontent.com/44558421/154641791-51dcdafe-a737-462d-9da0-c59b745ff9e9.jpg)

**Comment by Quorafind** [comment]
无法复现，请查看是否是自己的主题问题

**Comment by Wizarderror** [comment]
这就有点难受了，那这是不是意味着ios用户要正常显示的话，只能从更新版本的ios(如iOS 13)访问才行，或者后期会有对ios低版本的适配嘛？

**Comment by Quorafind** [comment]
应该不会主动修复，主要是我的设备已经升级，降级的话很麻烦
