### ISSUE TITLE
[Feature Request] Sort Memos

### ISSUE THREAD

**Issue by rapatel0** [Quorafind/Obsidian-Thino#131]
It would be great if memos could be sorted in the UI. 
- Sort by numerical filter `{#Priority/1-Low, #Priority/2-Medium,#Priority/3-High}` - #Priority/3-High Is on top followed by the rest. 
- Sort the presence of a text string (aribrtrary string or tag). `{#Personal, #Work}` - If #Personal exists, move to top.

**Comment by Quorafind** [comment]
Maybe, we need a sort method to sort memos when filter. Nice idea, will use another method to support this.

**Comment by Quorafind** [comment]
Available when you using table mode of thino.
