### ISSUE TITLE
添加内链预览效果

### ISSUE THREAD

**Issue by AiurArtanis** [Quorafind/Obsidian-Thino#132]
@Quorafind 

---

## 建议

目前**Ob-Memos**的主窗口和Daily Memos窗口都没有内链预览功能，如下图：
![image](https://user-images.githubusercontent.com/98091664/154932014-f9ed88de-c400-442e-839c-8f4a776736d4.png)
_Daily Memos_
![image](https://user-images.githubusercontent.com/98091664/154932383-73d122cd-5f84-41f3-b1ad-84480ec527b5.png)
_Memos_

希望能在Memos的主窗口和Daily Memos页面增加内链预览功能或者是按住`Ctrl`/`Command`进行预览

## 环境

操作系统：win 10
Obsidian：v0.13.23
Ob-Memos：v1.8.0

**Comment by Quorafind** [comment]
后续重构解析器后会再支持

**Comment by Quorafind** [comment]
已支持。
