### ISSUE TITLE
[Feature Request] Folder of memos (one memo per file)

### ISSUE THREAD

**Issue by rapatel0** [Quorafind/Obsidian-Thino#136]
It would be really nice to have a single file per memo instead of the memo per line. My daily notes file get's really cluttered with the current setup. 

If we could specify a folder, where memos would be saved to individual files, that would be ideal.

**Comment by Quorafind** [comment]
Will add an option in 1.9.0.

**Comment by jzhang-brex** [comment]
Is this already released? How do I configure this?
