### ISSUE TITLE
引用问题

### ISSUE THREAD

**Issue by wxy56** [Quorafind/Obsidian-Thino#137]
我点击[@MEMO](202202281809001)链接后，在电脑端为什么会出现跳转到别的app的链接窗口呢？

问题：是否会考虑设置复制链接的按键呢？像flomo一样

**Comment by Quorafind** [comment]
链接需要等我注册 Obsidian 的链接，等 1.9.0； 到时候应该也可以支持复制对应 Memo 的链接

**Comment by wxy56** [comment]
好的，感谢您的回复，您是否有微信呢？能否加您，方便交流




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Quorafind/Obsidian-Memos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 晚上6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Quorafind/Obsidian-Memos] 引用问题 (Issue #137)





 
链接需要等我注册 Obsidian 的链接，等 1.9.0； 到时候应该也可以支持复制对应 Memo 的链接
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Quorafind** [comment]
已修复
