### ISSUE TITLE
Use -hh:mm instead of - hh:mm

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Thino#14]
I think the plugin has great potential to create a more interesting journal than what obsidian currently offers. It could become something like journey or day one journal.

![journey app](https://user-images.githubusercontent.com/7627504/148244121-97d78bdb-f1ab-4859-af1b-76701d920106.png)

I know that the initial intention is not this, but with very few settings or optional configuration you could get something similar and privately, without external servers.

The main problem I see is that when based on the format "- hh:mm" does not allow you to have empty lines and forces you to add <br> in each line break. With this the structure of the note is confused.

If there is an option is in the configuration so that it allows the "-hh:mm" format, the original markdown format could be respected. The end of each entry would be to detect another "-hh: mm". 
Ideally, this is that heading # Memo goes at the end of the note.

**Comment by Quorafind** [comment]
How about support Template? Like people could use -{time:HH:mm} {Text} to recognize things

**Comment by javiavid** [comment]
Maybe you don't need to use -hh:mm if you think it might be a problem, you could use something custom, for example:
//hh:mm {text}
{text}

{text}

//hh:mm

**Comment by Quorafind** [comment]
Actually it should be doable while use - HH:mm
And have this:
- HH:mm
abcdedfg

blabla
- HH:mm

**Comment by Quorafind** [comment]
But why I used - HH:mm is for compatiable with Big Calendar, you could use it to view agenda and see them in weekly view

**Comment by javiavid** [comment]
> But why I used - HH:mm is for compatiable with Big Calendar, you could use it to view agenda and see them in weekly view

Thanks for the explanation

**Comment by javiavid** [comment]
> Actually it should be doable while use - HH:mm And have this:
> 
> * HH:mm
>   abcdedfg
> 
> blabla
> 
> * HH:mm

I have tried the example you wrote me and it does not work.
Do you mean a new version?

**Comment by Quorafind** [comment]
Yes, I have to think a way to make one line work with multiline better

**Comment by Quorafind** [comment]
Maybe an option about this is need
