### ISSUE TITLE
待办事项的想法，能否添加一个完成的按钮？The idea of a to-do list, can you add a done button?

### ISSUE THREAD

**Issue by MILKMILKKING** [Quorafind/Obsidian-Thino#140]
待办事项现在似乎没有完成的选项，如果可以新增一个完成的按钮，并且完成后显示文字中间横线划去的效果或者隐藏，这样方便待办事项的管理。
感谢你的辛勤努力，感觉这个插件挺棒的!

It seems that there is no option to complete the to-do list, if it is possible to add a button to complete the list and show the effect of crossing out the middle of the text or hide it after completion, it will be convenient to manage the to-do list.
Thanks for your hard work, I feel this plugin is pretty great!

**Comment by wenlzhang** [comment]
The following issue may be related to this: https://github.com/Quorafind/Obsidian-Memos/issues/32

**Comment by Quorafind** [comment]
已支持。
