### ISSUE TITLE
BUG：在检索式中输入了文本检索条件： - [ ] ，保存后，只要一点这个待办事项，插件就无法打开了。

### ISSUE THREAD

**Issue by MILKMILKKING** [Quorafind/Obsidian-Thino#141]
在检索式中输入了文本的检索条件为： - [ ] ，保存后，只要一点这个待办事项，插件就无法打开了。
本来是想要试试能不能搜索memos中的待办事项的，结果插件就死掉了，这似乎是一个BUG。

**Comment by Quorafind** [comment]
我检查一下
