### ISSUE TITLE
添加第二个Memos试图重新创建文件

### ISSUE THREAD

**Issue by charles-sun0v0** [Quorafind/Obsidian-Thino#143]
![image](https://user-images.githubusercontent.com/14788898/156971295-35d99178-036e-47cf-94ac-efbbe0d2ee7d.png)

**Comment by charles-sun0v0** [comment]
我想我找到了原因：我的日记标题格式为 `YYYY-DDDo-MM-DD-ddd` 看上去似乎 `DDDo` 导致Memos 不能找到对应的文件，Calendar 插件也找不到

**Comment by Quorafind** [comment]
😂 估计是 Moment 包的bug导致的

**Comment by Quorafind** [comment]
请查看是否还有类似的问题，如果还有的话，请重新打开 issue。
