### ISSUE TITLE
引用失效

### ISSUE THREAD

**Issue by stormbuf** [Quorafind/Obsidian-Thino#147]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/37621593/159329219-f535c333-d0b8-4e0f-b197-dcdb9fae35c8.png">

如图，引用失效，没有显示引用内用，也无法跳转到引用的memo。

可能有用的信息：
操作系统：macos Monterey v12.3
Obsidian 版本：v0.13.33
插件版本：v1.8.1

**Comment by Quorafind** [comment]
这个问题出自于 Obsidian 监控了默认的链接点击行为，需要一些努力才能解决这个问题，由于这个功能目前我使用较少，所以优先级并没有排得很高，等 2.0

**Comment by flyflypeng** [comment]
我也遇到了相同的问题，期待可以早日修复这个bug

**Comment by Eli-Ven** [comment]
这是我的临时方案：
https://github.com/Quorafind/Obsidian-Memos/issues/319#issuecomment-1509492084
存在已知bug：会影响memos的评论功能
欢迎帮助修改。

**Comment by Quorafind** [comment]
已修复
