### ISSUE TITLE
MAC版本，鼠须管输入法闪烁无法使用

### ISSUE THREAD

**Issue by stone3724** [Quorafind/Obsidian-Thino#149]
您好！MEMO是一个非常好的插件，填补了我很多的空白，我特别将它用在移动端，我认为可以快速帮我手机重要的想法。

但在使用时，我发现了一个问题，所以特别向您反映。当我使用MAC的鼠须管输入法时，我发现无法在MEMO的对话框中输入文字，我敲击键盘，可以看到选字框闪动，但无法看到具体的字符，因此无法键入内容。换成MAC自带的拼音输入法，则可以解决。

可否请您帮忙查看一下？谢谢！

**Comment by stone3724** [comment]
使用几天后，又有一个问题，请教您：
在memo的对话框中键入内链会有点问题。在对话框开头输入[[ ]]，可以正常显示数据库中已有的内容，直接选择。而如果在文本的中段输入[[ ]]，则无法引用，只能自己输入，就很容易输错。
插件版本：1.18.1
Obsidian版本：0.13.3
系统：MAC 12.0.1

**Comment by Quorafind** [comment]
好的，我这边之前已经收到一个关于输入法无法正常输入的问题，后续我装上观察一下

**Comment by kimonoki** [comment]
我用windows 小狼毫也无法输入

**Comment by kimonoki** [comment]
https://www.tangshuang.net/7840.html

是不是这个原因，想研究下不过跑不起来现在的代码

**Comment by Quorafind** [comment]
已修复。
