### ISSUE TITLE
Number of words

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Thino#15]
Option to limit the number of words displayed in each entry, with very large entries or for the mobile version would be very useful.

**Comment by Quorafind** [comment]
Nice idea, will be added in next version

**Comment by Quorafind** [comment]
not yet on #20 , but will add soon.

**Comment by lkadre** [comment]
Wanted to upvote this feature request, limiting the number of words/characters/lines in each entry would be very helpful.

**Comment by Quorafind** [comment]
Supported in latest  verison of Thino(Obsidian Memos)
