### ISSUE TITLE
再加入标签的时候，希望可以在#前面多加一个空格。这样在搜索无标签的memos时候可以排出。

### ISSUE THREAD

**Issue by 3Stoness** [Quorafind/Obsidian-Thino#150]
这里例子里面 就是#研究 前面没有空格导致的
![Uploading 3DBC1ECD-79FA-46E4-BC2A-F12C92DAFE00.png…]()

**Comment by 3Stoness** [comment]
![Uploading BAA00335-488C-4DAC-84F4-5C9D0ACDCD72.png…]()

**Comment by Quorafind** [comment]
已经加上了，等更新吧
