### ISSUE TITLE
能否增加一个判断，开启 Obsidian 时自动打开 Memos 只在移动端生效

### ISSUE THREAD

**Issue by scomper** [Quorafind/Obsidian-Thino#153]
能否增加一个判断，「开启 Obsidian 时自动打开 Memos」 只在移动端生效。
移动端打开时能方便的使用 Memos，PC 端打开 Obsidian 不自动加载 Memos。

**Comment by Quorafind** [comment]
好

**Comment by Quorafind** [comment]
需要 1.9.1 再加支持了，不好意思。
