### ISSUE TITLE
Latex is not supported

### ISSUE THREAD

**Issue by woodwm** [Quorafind/Obsidian-Thino#154]
Hi, Obsidian support latex, but Memos does not. Hope to support it.

**Comment by Quorafind** [comment]
I will use markedjs/Katexjs in next version, how it can works well

**Comment by woodwm** [comment]
Hi, that should be a good choice. Logseq use Katex as well.

**Comment by Quorafind** [comment]
I'm very sorry for not replying to you for so long. The latest version of Thino (Obsidian Memos) now supports this feature.
