### ISSUE TITLE
Add tab or special words after copy to dailynote

### ISSUE THREAD

**Issue by zdway10** [Quorafind/Obsidian-Thino#155]
复制到dailynote的时候，能不能加个tab键 或 特殊符号？ 是对应 这个变量吗？ DefaultMemoComposition，谢谢。

**Comment by Quorafind** [comment]
不明白 复制到 这个是什么行为

**Comment by zdway10** [comment]
就是memos 复制到daily note时，默认前缀是hh:mm 或者 todolist，能用其他格式吗？如默认前缀hh:mm前面加个tab 或者 -，谢谢。

> 不明白 复制到 这个是什么行为

**Comment by Quorafind** [comment]
应该不会支持，可以考虑使用单文件模式，更好地自定义你所需要的内容。https://thino.pkmer.net/thino/02_thino-advanced/thino-multi-souce/
