### ISSUE TITLE
[Feature Request] Alternate Checkbox Types (Minimal Theme)

### ISSUE THREAD

**Issue by juicybox** [Quorafind/Obsidian-Thino#158]
Please add support for **alternate checkbox types**, like the one from the **Minimal Theme**.

![image](https://user-images.githubusercontent.com/3801775/161825717-5f4d8c2a-2d79-4994-8a15-ae58cbaed041.png)
https://minimal.guide/Block+types/Checklists

## MVP

Would be great to have the possibility to enter a task text with the checkbox type you want to use (like `[/]` or `[f]`, ..) instead of the default on `[ ]`

### Input
```
[/] sample task title (for incomplete) 
```

### Output
```
 - [/] 17:33 sample task title (for incomplete) 
```

## Better Experience

![Screenshot - 2022-04-05 20 58 47](https://user-images.githubusercontent.com/3801775/161830300-eb57a634-46c2-498a-a66f-3fd21fddf10c.png)

-> A choice option (dropdown, a button group or a combination of both) (Note 1)
-> An icon that show the task type in the list (Note 2)
-> A setting page to define your preferred types (only) with icon and color.

## Off topic

I'm using a customized stylesheet for this plugin and the Minimal Theme.

My Daily Note looks like this:

![Screenshot - 2022-04-05 21 28 59](https://user-images.githubusercontent.com/3801775/161834776-17038f42-26fb-43a5-b725-4dc3a9256dff.png)

**Comment by Quorafind** [comment]
I'm very sorry for not replying to you for so long. The latest version of Thino (Obsidian Memos) now supports this feature.
