### ISSUE TITLE
Star with favorite ideas

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Thino#16]
If you are visualizing a lot of ideas, you might want to work on the most interesting ones. You can mark a star (for example) and then have a query for favorites.

![image](https://user-images.githubusercontent.com/7627504/148246974-9cfb8034-c6fa-4f80-8f36-e52d6637829d.png)

**Comment by Quorafind** [comment]
Starring memo is a good idea, I think

**Comment by Quorafind** [comment]
You can use query and pin the query now if you really need a mark, you can use tag to mark a star thing I guess

**Comment by javiavid** [comment]
The tags option is very useful to classify the posts when you create them. 

The favorites idea can be used when you do a quick review of ideas to dig into.  It is much faster to click on star without opening the entry and type a tag.

The star can be used as a temporary thing.

**Comment by Quorafind** [comment]
Now you can pin or unpin (or mark it )
