### ISSUE TITLE
Failed to load memos with version 1.9.0

### ISSUE THREAD

**Issue by wenlzhang** [Quorafind/Obsidian-Thino#167]
Just updated to 1.9.0. However, when I tried to load memos, it first said that "Open Memos successfully" then "Fetch error". After this, no memos were loaded. In the Obsidian console, nothing special was found.

**Comment by Quorafind** [comment]
Did you installed dataview or open periodic notes && daily note plugin at the same time?

**Comment by Quorafind** [comment]
You can use command: Show Debug Info and paste here to help me with this

**Comment by wenlzhang** [comment]
I have Dataview installed. Also, I disabled the Daily notes plugin and only enabled Periodic notes.

Here is the debug info:
```
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.5
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 21.4.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: BRAT-kepano----obsidian-minimal
	Snippets enabled: 3
	Safe mode: off
	Plugins installed: 41
	Plugins enabled: 32
		1: Advanced URI
		2: Tasks
		3: File Explorer Note Count
		4: Outliner
		5: Custom window title
		6: Recent Files
		7: Pane Relief
		8: Hotkeys++
		9: Advanced Mobile Toolbar
		10: Shortcuts extender
		11: Daily Stats
		12: Hotkey Helper
		13: Calendar
		14: Dataview
		15: Task Collector (TC)
		16: Customizable Sidebar
		17: Workspaces Plus
		18: Hider
		19: Customizable Menu
		20: Copy Block Link
		21: Minimal Theme Settings
		22: Style Settings
		23: Auto Link Title
		24: Obsidian42 - BRAT
		25: Obsidian Memos
		26: Code Editor Shortcuts
		27: Key Promoter
		28: RSS Reader
		29: Periodic Notes
		30: Emails
		31: Lapel
		32: Hover Editor

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

```

**Comment by wenlzhang** [comment]
On a second try, if I only enable the Periodic notes plugin and disable the Daily notes plugin, it works. Periodic notes plugin is more powerful and useful to me, though.

**Comment by Quorafind** [comment]
Now it only support one of them. And when you enable Periodic notes plugin, it won't ask for daily note plugin anymore. So could you just use Periodic notes plugin?

**Comment by wenlzhang** [comment]
Sorry for the last comment. I meant to say that if I disable the Periodic notes plugin and only enable the Daily notes plugin, it works, not the other way around.

**Comment by Quorafind** [comment]
Maybe you need to install the 1.0.0 perdioc note plugin to make this works.

**Comment by wenlzhang** [comment]
With the Periodic notes plugin version 1.0.0-beta.3, Memos works now.

It can be very slow for Memos to load content, though. For example, when I initialize Memos or add new Memos directly in the daily note, it can take around 10 seconds for Memos to start or identify the new Memos. In the previous version of Memos, it was much faster.

By the way, in the tests above, I haven't turned on the option to load Memos from notes other than Daily notes.

**Comment by Quorafind** [comment]
https://user-images.githubusercontent.com/13215013/163788417-f1eec990-d6d6-4275-b011-b1e49c3af6ee.mp4

HmmmHmmmm, it is weird that I didn't have same question. And I tried it in my huge vault too.

**Comment by wenlzhang** [comment]
I see. In my vault, there are around 320 daily notes. In this vault, it mainly contains daily notes and the total notes are around 470.

If your vault is for testing purpose, is it possible to send it to me for testing? Or, can you recommend a method to generate such a test vault to test Memos? I am not sure if it is related to things like computer, Obsidian, plugin installation, etc.

It would be great if this issue can be resolved, as I use Memos frequently every day for managing my thoughts, project notes, etc., before they are completed or processed as permanent notes.

Here is the what my Memos interface looks like:
<img width="220" alt="Screenshot 2022-04-18 at 12 31 07" src="https://user-images.githubusercontent.com/44930227/163796525-ff40906b-2404-46b5-a9ac-016645441fed.png">

**Comment by Quorafind** [comment]
Sure, do you use discord? DM me there or send email to me bonopengate@gmail.com

**Comment by wenlzhang** [comment]
> Sure, do you use discord? DM me there or send email to me [bonopengate@gmail.com](mailto:bonopengate@gmail.com)

Great! Already DMed you on Discord.

**Comment by shunnkou** [comment]
Hello, I'm wondering if there's any updates on Obsidian being slow/laggy? I'm having the same issue with Memos and the behavior is the same with the new features turned off and on. The Popover Memos is slow as well.

**Comment by wenlzhang** [comment]
> Hello, I'm wondering if there's any updates on Obsidian being slow/laggy? I'm having the same issue with Memos and the behavior is the same with the new features turned off and on. The Popover Memos is slow as well.
> 
> 

Not yet. The developer is probably asleep now. 😀

**Comment by Quorafind** [comment]
I am trying to find the bug itself, won't need too long, sorry for waiting.

**Comment by Quorafind** [comment]
I'm very sorry for not replying to you for so long. The latest version of Thino (Obsidian Memos) should handle this amount of Thinos.
