### ISSUE TITLE
快速筛选的标签无法选中

### ISSUE THREAD

**Issue by shanyang121** [Quorafind/Obsidian-Thino#175]
如下图，我想选择无标签的选项，但是鼠标一从搜索框移开，这个黑框就会消失，无法点到我想要的“无标签”选项。
![image](https://user-images.githubusercontent.com/80085868/163899863-376cb285-539f-4d9c-9b02-7c1d33d2fdf7.png)

**Comment by Quorafind** [comment]
下个版本修复

**Comment by Quorafind** [comment]
再看一下是否有类似的情况
