### ISSUE TITLE
contributions graph 自动隐藏了

### ISSUE THREAD

**Issue by zdway10** [Quorafind/Obsidian-Thino#179]
contributions graph 自动隐藏了，是Memos插件自己的配置问题还是Obsidian配置的问题？
图片1：自动隐藏了
<img width="452" alt="5" src="https://user-images.githubusercontent.com/38562346/164134127-2b975827-2bb6-418d-9669-143bdcf72f25.png">
图片2：正常（希望一直是这个）
<img width="481" alt="6" src="https://user-images.githubusercontent.com/38562346/164134154-8ced868d-4503-4def-a328-09582355999c.png">

**Comment by Quorafind** [comment]
根据大小自动适配，你想要下图的话，将 Memos 的页面拉到大概 14寸笔记屏的半屏大小即可。

**Comment by zdway10** [comment]
方便做个配置开关吗？希望一直有下图的效果：）谢谢。

> 根据大小自动适配，你想要下图的话，将 Memos 的页面拉到大概 14寸笔记屏的半屏大小即可。
