### ISSUE TITLE
[问题] 点击分享时，合成卡片样式出错

### ISSUE THREAD

**Issue by biorz** [Quorafind/Obsidian-Thino#182]
点击分享时

![image](https://user-images.githubusercontent.com/15077010/164159012-a21a9e59-1d85-47a0-9515-c0a997002eae.png)

点击分享复制到剪贴板后

![image](https://user-images.githubusercontent.com/15077010/164159093-00363d15-1d32-4ace-b3e0-123f3b117a75.png)

**Comment by biorz** [comment]
第一次总是出错， 关闭后再点击正常。
当切换到其他的页面， 在返回 memo 主页，点击分享可以再次复现。

**Comment by Quorafind** [comment]
在再次出错的情况下，请按一下 Ctrl+P 输入显示调试信息，然后粘贴在这里我查看一下。

**Comment by biorz** [comment]
obsidian.md-1650503665317.log

**Comment by Quorafind** [comment]
😂 我需要的是这样的一个信息 
![image](https://user-images.githubusercontent.com/13215013/164352460-36ccbfab-4c25-4be9-899f-7be2003f7d6a.png)

**Comment by biorz** [comment]
![image](https://user-images.githubusercontent.com/15077010/164352376-2732d946-425d-4128-a4d7-2f311b129157.png)

生成的base64有点问题，下面是原图

![image](https://user-images.githubusercontent.com/15077010/164352463-9001d1a3-d157-4beb-affd-7891ec586bcd.png)

**Comment by biorz** [comment]
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.5
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 21.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 39
	Plugins enabled: 37
		1: Advanced Tables
		2: Kanban
		3: Dataview
		4: Excalidraw
		5: Templater
		6: Outliner
		7: Sliding Panes (Andy's Mode)
		8: Mind Map
		9: Editor Syntax Highlight
		10: Note Refactor
		11: QuickAdd
		12: Emoji Toolbar
		13: Tasks
		14: Dictionary
		15: Local REST API
		16: Advanced URI
		17: Metadata Extractor
		18: Day Planner
		19: Natural Language Dates
		20: Tag Wrangler
		21: Obsidian Charts
		22: Annotator
		23: Privacy Glasses
		24: Auto Link Title
		25: MetaEdit
		26: Calendar
		27: Obsidian Git
		28: Tracker
		29: Periodic Notes
		30: Pane Relief
		31: Reminder
		32: Hider
		33: Checklist
		34: Minimal Theme Settings
		35: Style Settings
		36: Citations
		37: Obsidian Memos

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by Quorafind** [comment]
好谢谢。感觉确实是图片或者生成的时候导致的，因为我这边还没遇到类似的问题，我跟踪测试一下。

**Comment by biorz** [comment]
大佬 针对该问题提了 PR， 帮忙看看哈

**Comment by Quorafind** [comment]
我合并且发布了，看一下发布后的版本还有没有同样的情况 @biorz
