### ISSUE TITLE
手机客户端无法安装memo插件

### ISSUE THREAD

**Issue by harrisonzhou** [Quorafind/Obsidian-Thino#187]
手机客户端无法安装最新的memo插件，版本1.9.4，提示“no appropriate vesion provide”
![微信图片_20220422154202](https://user-images.githubusercontent.com/23709952/164635008-4b2d3117-859f-45b7-ac9a-482763706167.jpg)

**Comment by Quorafind** [comment]
根据调查，估计是因为 0.14.4 所对应的版本还没有更新到移动端，而 Memos 依赖于这个版本以后的某些特性，所以。。

**Comment by harrisonzhou** [comment]
> 根据调查，估计是因为 0.14.4 所对应的版本还没有更新到移动端，而 Memos 依赖于这个版本以后的某些特性，所以。。

我用电脑端把文件同步到手机端是能用的。。。

**Comment by Quorafind** [comment]
因为某个部分是还没有被 Ob 正式公开的 API ，如果低于这个版本我也不能确保稳定性。。
