### ISSUE TITLE
Multiple columns

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Thino#188]
Computer monitors have a lot of horizontal space.
Could you add an option for multiple columns?

**Comment by Quorafind** [comment]
I don't know what do you mean😂

**Comment by javiavid** [comment]
😄 Something similar a cards interface in Minimal theme
![image](https://user-images.githubusercontent.com/7627504/164705608-0662459b-9eff-437e-9e26-2b828dca126e.png)

**Comment by javiavid** [comment]
Maybe 2 or 3 is enough

**Comment by Quorafind** [comment]
I'm very sorry for not replying to you for so long. The latest version of Thino (Obsidian Memos) now supports this feature in Pro version.
