### ISSUE TITLE
从文件获取memo报拉取失败

### ISSUE THREAD

**Issue by goldenages1989** [Quorafind/Obsidian-Thino#192]
看issue里面有报相同问题的，但是在我这里还是报错
我已经1. 把periodic notes禁用了，2. 把所有的插件都禁用，只剩下memos插件，还是报错。

**Comment by Quorafind** [comment]
关闭任何插件后，需要重启插件。另外您的目前 Memos 版本是？

**Comment by goldenages1989** [comment]
> 关闭任何插件后，需要重启插件。另外您的目前 Memos 版本是？

我把obsidian重启了，现在的版本是1.9.4

**Comment by Quorafind** [comment]
请查看是否还有类似的问题，如果还有的话，请重新打开 issue
