### ISSUE TITLE
[issue]memos could not create a memo if the daily notes of that day were not created before

### ISSUE THREAD

**Issue by Ravenclawer** [Quorafind/Obsidian-Thino#195]
reproduce:
open obsidian and enter memos interface directly, type in some notes and press NOTEIT then the following information will prop out
![image](https://user-images.githubusercontent.com/73892411/164895628-62af9008-e864-4c13-a6b3-5d0b63ba4968.png)
solution:
enable the open daily notes on startup option in the daily notes CORE plugin OR disable periodic notes plugin

**Comment by tinyblckc00000al** [comment]
I have a exactly same problem.

**Comment by briandbezerra** [comment]
Same here.
