### ISSUE TITLE
分享memos时报错

### ISSUE THREAD

**Issue by lenxvp** [Quorafind/Obsidian-Thino#198]
分享一条Memos点击分享无反应，多次重启和改设置也没反应，Console输出如下：
![Snipaste_2022-04-24_09-50-16](https://user-images.githubusercontent.com/14134959/164952346-568e6ee1-e527-449b-be7a-70b145ecad53.png)
分享相关设置如下：
![Snipaste_2022-04-24_09-50-07](https://user-images.githubusercontent.com/14134959/164952343-c8b815de-7c2d-4547-8c86-65c2ea766996.png)
软件和插件版本如下
![Snipaste_2022-04-24_09-50-44](https://user-images.githubusercontent.com/14134959/164952347-2ab2e8f5-f2a6-4a48-8ee0-c7dec074b71f.png)
![Snipaste_2022-04-24_09-50-51](https://user-images.githubusercontent.com/14134959/164952350-d5bc295c-08e8-479b-b7f8-a9592f1d08c9.png)

**Comment by Quorafind** [comment]
下个版本修复。

**Comment by Quorafind** [comment]
已修复。
