### ISSUE TITLE
【BUG】Flomo导入功能问题

### ISSUE THREAD

**Issue by AiurArtanis** [Quorafind/Obsidian-Thino#204]
@Quorafind 

---

## 问题

**Memos**导入flomo导出的html文件后会出现下列2个问题：
1. **段落符的处理有误**：`<p>content</p>`   最终会被识别成`<p>content`  
  + 建议识别成`content<br>`
2. **对于多行+空格+空行的笔记导入有误**：如果某条笔记是多行+空格+空行，则导入后，从这条开始之后每一条的笔记都会被合并至该条上，以及会有其他的问题
  - 已经私发你问题的笔记

## 环境

Obsidian：v0.14.6
Ob-Memos：1.9.4

## 最后

私信估计你会忘，补个issue

**Comment by MooWantFree** [comment]
而且好像无法导入图片?
Obsidian：v0.14.6
Ob-Memos：1.9.6

**Comment by AiurArtanis** [comment]
> 而且好像无法导入图片?

Bon佬自己说的附件不支持导入

**Comment by ycbrd** [comment]
顶，希望导入问题可以得到作者的关注，感谢(*￣︶￣)

**Comment by Quorafind** [comment]
图片
