### ISSUE TITLE
“允许Memos从笔记中获取Memo”获取失败

### ISSUE THREAD

**Issue by CLOUDUH** [Quorafind/Obsidian-Thino#207]
关闭此选项时候，memos自动从dailynote文件夹打开memos
打开此选项时，提示memo获取失败，并且memos里面为0

**Comment by KeisonChem** [comment]
> 关闭此选项时候，memos自动从dailynote文件夹打开memos 打开此选项时，提示memo获取失败，并且memos里面为0
我也遇到了相同的问题

**Comment by shanyang121** [comment]
![image](https://user-images.githubusercontent.com/80085868/167367709-d7c4c975-a059-466c-8bed-7026c545f736.png)
设置中实验项目里这个选项要打开，好像需要beta版的dataview，默认插件市场里的是旧版的，需要自己更新成beta版本的

**Comment by shanyang121** [comment]
好像是需要你在文件中输入#memo后才可以被检索到，检索关键词你可以在上图的输入框里改
