### ISSUE TITLE
能否实现memo编辑时的时间管理：1.时段检索；2.设置编发时间

### ISSUE THREAD

**Issue by vimbackground** [Quorafind/Obsidian-Thino#209]
## 时段检索

**需求描述**：内容检索希望能支持时段检索，即查看类似2022.01.01-2022.01.07的内容
**应用场景**：做定期信息汇总，或者回顾一段时间的记录时，需要查询一段时间内编写的相关内容

## 设置编发时间

**需求描述**：在记录（或编辑）一个memo时，能直接设置该memo的时间戳，希望能精确到分
**应用场景**：原始记录不在obsidian内，而是其它工具，在obsidian汇总时，要该原始记录时间登记，现在只能在原始页面和memos界面中来回切换，不太方便

**Comment by Quorafind** [comment]
第一个，用

-time: 2022-01-01 2022-01-07

来检索。

第二个，建议在输入法阶段就插入时间

**Comment by vimbackground** [comment]
第一个问题不大，虽然多点了几下鼠标，不经常用，问题也还好。

第二个不太适用，以我的使用场景来说：我平时的memo都会随手记到我的typecho上（类似evernote的用法，用其它笔记软件一样），然后1-2周整理一次，这时候是没法直接插入时间的，之前的做法是在obsidan中自建对应日期的memo文件，然后再在源文件中手动填时间——结果memos插件只是作为单纯的展示用途了，还不如直接改源文件方便……

以上，用法不知道有没有一定的普遍性，提出来，供参考

**Comment by Quorafind** [comment]
已支持。筛选的情况下，可以动态选择开始和结束时间。
