### ISSUE TITLE
BUG反馈：块引用点击无效&MD样式无效

### ISSUE THREAD

**Issue by fantasyzyc** [Quorafind/Obsidian-Thino#213]
首先非常感谢作者开发的MEMO，非常好用，使用过程中遇到两个问题：
1.文章引用可以正常打开，但是块引用如 [[2022-05-01#test]]点击后没反应，链接是有的
2.MEMO中 #一级标题，==内容==，列表 等markdown样式都不支持，后续是否会支持？

**Comment by Quorafind** [comment]
1. 和2. 的问题都会在采用官方渲染器以后确定

**Comment by Eli-Ven** [comment]
这是我的临时方案：
https://github.com/Quorafind/Obsidian-Memos/issues/319#issuecomment-1509492084
存在已知bug：会影响memos的评论功能
欢迎帮助修改。

**Comment by Quorafind** [comment]
已经修复。
