### ISSUE TITLE
是否能通过aflred来实现快速输入到memos当中？

### ISSUE THREAD

**Issue by martinwong248yoyo** [Quorafind/Obsidian-Thino#214]

**Comment by 7enChan** [comment]
可以通过这个实现workflow实现，配置一下daily note的格式就行：https://github.com/chrisgrieser/shimmering-obsidian

**Comment by martinwong248yoyo** [comment]
太感谢了，之前尝试在daily当中直接写一条memo，结果在memos里没有反应。这下肯定了可行之后，发现原来是忽略了需要带上时间。这些可玩性又高了不少

**Comment by Quorafind** [comment]
现阶段如果你是 Pro 用户，也可以考虑通过 Local Server 的方式请求

```
POST

http://localhost:43999/create

application/json

{text: "内容", isList: boolean, type: "DAILY"} 
```
