### ISSUE TITLE
请问Obsidian 的分享问题

### ISSUE THREAD

**Issue by VerneWei** [Quorafind/Obsidian-Thino#225]
请问，Obsidian中 分享后 出现这样的字【Send to clipboard successfully】
但不知道分享的图片去哪里了？

**Comment by shipengfish** [comment]
> 请问，Obsidian中 分享后 出现这样的字【Send to clipboard successfully】
> 但不知道分享的图片去哪里了？

在剪贴板里，粘贴即可。

**Comment by VerneWei** [comment]
谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月1日(周三) 下午5:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Quorafind/Obsidian-Memos] 请问Obsidian 的分享问题 (Issue #225)




  
请问，Obsidian中 分享后 出现这样的字【Send to clipboard successfully】
 但不知道分享的图片去哪里了？
  
在剪贴板里，粘贴即可。

**Comment by MingchaoShi** [comment]
手机端点了分享后，出现了copy to clipboard successful的提示，但是去其它APP里，比如微信或TG，都无法黏贴出来。

**Comment by Quorafind** [comment]
需要开启图片保存的设置。
