### ISSUE TITLE
随机回顾和同步后评论不显示

### ISSUE THREAD

**Issue by LuoChenLC** [Quorafind/Obsidian-Thino#227]
辛苦大佬
1.希望增加一个随机回顾按钮，增加笔记复现的几率。
2.版本1.9.7中使用评论功能，在手机和PC端进行同步后在源文件中有评论语句，但在Memos中无法读取。

**Comment by Chenk94** [comment]
同样出现了评论不显示的问题，重启软件后评论即不可见。本来想代替引用功能（因为引用功能并不能引用到原条目）

**Comment by txchen** [comment]
遇到了同样的问题, 重启 obsidian 以后, 评论不可见.

**Comment by WystanW** [comment]
我直接就是评论没法显示，还没同步

**Comment by Quorafind** [comment]
随机回顾已支持。
评论功能会在计划后重构上线。暂时关闭 Issue
