### ISSUE TITLE
query搜索功能

### ISSUE THREAD

**Issue by hellspector** [Quorafind/Obsidian-Thino#228]
memos最重要的两大功能是：无压力记录与随时搜索查看
希望能在filter里面加两个功能，
1. 忽略英文的大小写（现在的搜索是要完全匹配才能显示，不方便，很难记清当时是用了大写还是小写）
2.查看结果关键字匹配 （有的时候搜索出来的memo是一段文字的，也不知道搜索的关键字是显示在哪里了）
如果能增加上面两个功能，那在查找的时候会如虎添翼。

附：
最近发现这个memos，非常好用，感谢开发者，如果有微信或者支付宝码，愿意支持开发者。

**Comment by Quorafind** [comment]
你的建议会考虑。

在仓库的右边 Sponsor 链接里面有支付宝以及微信的二维码

**Comment by hellspector** [comment]
> 你的建议会考虑。
> 
> 在仓库的右边 Sponsor 链接里面有支付宝以及微信的二维码

好的，已经支持。
还有另外一个问题，不知道是不是要重新开一个issue，先说一下吧。

**Comment by Quorafind** [comment]
已修复。
