### ISSUE TITLE
请问设置MEMO组成的语法是什么呢？改为时间戳在第一行、内容另起一行且有缩进， `- {TIME}\n    - {CONTENT}`不起作用

### ISSUE THREAD

**Issue by vvwantspeed** [Quorafind/Obsidian-Thino#237]
开发者你好~
我希望将MEMO在日记页面里的显示如下，也就是内容可以另起一行、并且缩进变成时间戳的下级块：
```
- 10:10
    - 这是一条memo的内容
```
在设置里看到有「设置MEMO组成」的选项，但试图用`\n`回车换行和`-`以及空格来设置格式，不起作用。
请问是否可以在这里设置换行的格式哇？可以的话，应该怎么设置呢？
如果不可以直接设置，需要修改源码的话，可以麻烦给个大概关键字or定位到相关功能模块代码不？俺去瞅瞅JS啥的看能不能自己改。
非常感谢！

**Comment by Quorafind** [comment]
已支持
