### ISSUE TITLE
两个错误枚举 

### ISSUE THREAD

**Issue by zhuhaisto** [Quorafind/Obsidian-Thino#242]
模拟下产生问题的过程
1.  我先打开侧边里面的memos （我需要关掉那个窗口他才会显示
![图片](https://user-images.githubusercontent.com/108032980/180763236-62e3b551-1870-487a-a255-261ea307bbd9.png)
2. 然后我移动到新窗口
![图片](https://user-images.githubusercontent.com/108032980/180763343-e9ec5d69-94cf-4c53-9609-d00fdacfe992.png)
3. 第一个问题 shift+# 打这个＃号 他就这样了 但是这个问题如果不新窗口是没有的
![图片](https://user-images.githubusercontent.com/108032980/180763556-4124b7fb-ec9b-499b-ab55-8a60b160ff91.png)
4. 然后下一个问题 我看了下来源（新窗口下看的）
![图片](https://user-images.githubusercontent.com/108032980/180763646-51b2357b-7968-466e-b2f7-083313690ee9.png)
然后他就
![图片](https://user-images.githubusercontent.com/108032980/180763731-f16add43-441c-43ed-adae-5183ee8e9a06.png)
这个是下面那个窗口 就这样了 我看了下这个是 工作区那个配置文件的问题把他删了就恢复了 
不在新窗口看是没问题的

**Comment by cumany** [comment]
https://github.com/Quorafind/Obsidian-Memos/blob/858fba6cd16bc2e7e326279225f7a55b35be8a94/main.js#L13098
这行代码注释了就正常了

**Comment by cumany** [comment]
> 这算是bug吧 最好大佬提供插件升级才是道理吧 一个不会看代码的人 这样修修补补怕崩溃啊

肯定算bug了 不过你看issue 已经一百了 bon佬还在搞其他插件 无暇东顾了  我今天排查了一下这样可以先解决问题

**Comment by Quorafind** [comment]
已修复。
