### ISSUE TITLE
Memos get deleted automatically

### ISSUE THREAD

**Issue by psyguy** [Quorafind/Obsidian-Thino#243]
Hi,

Thanks for the plugin! I am using the plugin on Obsidian `v0.15.9` on Windows 10. I can add a new memo:

![image](https://user-images.githubusercontent.com/8527082/181235363-76835306-e97f-4706-91c6-45a3da3fd245.png)

But it soon disappears from the Memo page (and is added to my daily notes):

![image](https://user-images.githubusercontent.com/8527082/181235682-faea8aa1-9bdb-4267-9dd2-4d0296fad1db.png)

I didn't have this issue before updating Obsidian (from `v0.14.xx`). How can it be remedied?

Thanks in advance.

**Comment by psyguy** [comment]
A restart helped. I'm closing this issue, and sorry for spamming!

**Comment by psyguy** [comment]
I am opening this issue as I am still facing the same problem: Within 1-2 seconds, a noted Memo is removed from the memo list and is added to daily notes. I need to have my notes in the Memo page as well.

**Comment by dragos240** [comment]
You are not the only one. I'm getting this issue too.

**Comment by Woynert** [comment]
I don't know what the cause might be, but I solved it by deleting the `.obsidian` folder from my vault and recreating it with obsidian as "Open folder as vault".

This will erase all your configs of course.

**Comment by Quorafind** [comment]
Get fixed.
