### ISSUE TITLE
[Bug] 关于搜索框的问题

### ISSUE THREAD

**Issue by ycbrd** [Quorafind/Obsidian-Thino#245]
类型后面的“有链接”“无链接”……是按钮吗？鼠标还没过去就消失了（无论是否输入了检索内容）

https://user-images.githubusercontent.com/105804326/182146153-d613d23d-8bce-4efb-8e36-3a0126a11d2b.mp4

**Comment by MingchaoShi** [comment]
是按钮，我这儿是可以正常点击的，不会消失。

**Comment by ycbrd** [comment]
https://github.com/Quorafind/Obsidian-Memos/issues/245#issuecomment-1203376683
那么我遇到的可能是bug？

**Comment by MingchaoShi** [comment]
> [#245 (comment)](https://github.com/Quorafind/Obsidian-Memos/issues/245#issuecomment-1203376683) 那么我遇到的可能是bug？

你试试把主题设置成默认，然后关闭掉一些第三方插件，看看是不是哪里冲突了。

**Comment by ycbrd** [comment]
> 你试试把主题设置成默认，然后关闭掉一些第三方插件，看看是不是哪里冲突了。

主题是默认，其他第三方逐个关闭试验，没有发现冲突，bug来自插件本身。

**Comment by Dave-pan** [comment]
> > 你试试把主题设置成默认，然后关闭掉一些第三方插件，看看是不是哪里冲突了。
> 
> 主题是默认，其他第三方逐个关闭试验，没有发现冲突， bug (臭虫) 来自插件本身。

你是不是向下还原窗口了？我也发现了这个问题。最大化是正常的。

**Comment by ycbrd** [comment]
> > > 你试试把主题设置成默认，然后关闭掉一些第三方插件，看看是不是哪里冲突了。
> > 主题是默认，其他第三方逐个关闭试验，没有发现冲突， bug (臭虫) 来自插件本身。
> 你是不是向下还原窗口了？我也发现了这个问题。最大化是正常的。

我把ob的配置文件删了重新设置了一遍，没有事了，窗口不最大化不影响。这办法挺花时间。

**Comment by ycbrd** [comment]
窗口有足够的空间展开侧栏就没有关系，大概是bug，求作者大大修复。 @MingchaoShi

**Comment by MingchaoShi** [comment]
<img width="296" alt="Snipaste_2022-08-15_17-08-01" src="https://user-images.githubusercontent.com/47729630/184608304-3990a096-0360-41ca-b6d5-43d77f8a7746.png">
我即使把窗口缩到很小，也仍然正常，窗口最大化也是正常的。

**Comment by ycbrd** [comment]
> 我即使把窗口缩到很小，也仍然正常，窗口最大化也是正常的。

很遗憾您不能复现该问题，但我确信我的电脑上存在该问题。我的分辨率是2376*1824，系统缩放250%。
我在沙箱库中运行memos插件，问题依然如故。但是当侧栏完全显示（窗口足够宽时），问题确实立刻消失了。

https://user-images.githubusercontent.com/105804326/184831512-3411c075-f659-450b-892c-c257a849eab1.mp4

**Comment by cumany** [comment]
> <img alt="Snipaste_2022-08-15_17-08-01" width="296" src="https://user-images.githubusercontent.com/47729630/184608304-3990a096-0360-41ca-b6d5-43d77f8a7746.png">
> 
> 我即使把窗口缩到很小，也仍然正常，窗口最大化也是正常的。

Blue topa主题针对memos 特殊修复了 所以你的没有问题
