### ISSUE TITLE
[Feature Request] 使用时间戳生成器核心插件，将每条memo保存为一个笔记文件

### ISSUE THREAD

**Issue by ycbrd** [Quorafind/Obsidian-Thino#249]
时间戳生成器也叫unique note creator. 目前支持用日记插件或periodic notes. 如果使用时间戳生成器插件将每条memo保存为一条笔记，可以使用wiki链接memos，也可以关系图谱展示memo之间的引用关系。请您考虑。

**Comment by Quorafind** [comment]
现在 Pro 功能支持生成多文件 Thino，相关信息： https://thino.pkmer.net/thino/02_thino-advanced/thino-multi-souce/
