### ISSUE TITLE
代码中建议加上normalizePath

### ISSUE THREAD

**Issue by Max-Tortoise** [Quorafind/Obsidian-Thino#253]
# 可能会出现问题的代码
下面这段代码，首先读取日记插件中设置的文件夹位置，然后和query文件拼接，最后得到query文件的完整路径。
https://github.com/Quorafind/Obsidian-Memos/blob/858fba6cd16bc2e7e326279225f7a55b35be8a94/src/obComponents/obGetQueries.ts#L11-L14

如果在日记插件中文件夹设置成'/'或者'/DailyNote'这种，上面这段代码就不能正确的读取到query文件和delete文件。

<img width="853" alt="image" src="https://user-images.githubusercontent.com/104265685/186165421-c36e8704-a247-4e06-ad46-a388c9f3bde3.png">

# 为什么会将日记插件的文件夹设置成'/'
刚下载好Obsidian-Memos插件之后，在侧边栏点开Memos，会提示我们日记插件或者Periodic没有设置文件夹。而我的日记文件就在根目录，所以就很自然的将文件夹设置成'/'。

# 可以改进的地方
项目中有很多地方和这个类似，我觉得可以加上normalizePath，这样就可以解决路径设置成'/'或着'/DailyNote'的情况。
```ts
const absolutePath = normalizePath(filePath + '/' + QueryFileName + '.md');
```

# Related Issues
https://github.com/Quorafind/Obsidian-Memos/issues/146#issuecomment-1078586070

**Comment by Quorafind** [comment]
已修复
