### ISSUE TITLE
不完美的Flomo导入方案

### ISSUE THREAD

**Issue by CLOUDUH** [Quorafind/Obsidian-Thino#254]
### 通过批量替换的方法稍微不完美地导入flomo的html文件

从flomo导出的文档只有html格式
在使用此插件界面上的导入功能时，不能识别flomo中`<p>文本文本</p>`的格式
对于多空格段乱的适配也并不好

我目前的解决方案是：
用vscode打开flomo的html文件

- 把`<p>`全部替换消失
- 把`</p>`全部替换成`<br>`
- 把`<div class="content">`(含换行和五个制表位)全部替换成`<div class="content">`(含换行和四个制表位)

<img width="198" alt="image" src="https://user-images.githubusercontent.com/66972658/186379198-b103008b-40d3-4678-b9f8-8a503a615967.png">

然后再使用本插件导入即可

**Comment by Quorafind** [comment]
已修复。
