### ISSUE TITLE
是否可以将 memos 识别标识改为行末 locator 式样的时间戳？

### ISSUE THREAD

**Issue by Yubuxin** [Quorafind/Obsidian-Thino#256]
如题。

目前 memos 的识别标识为行首的 {TIME}，样式为 {HH:mm}，但这样一者会造成嵌入单条 memo 时出现无关信息，再者在 Obsidian 已提供了 locator 这样的识别机制时，再维护一个自有的机制是否略显麻烦？

所以我想，能否把插件的默认标识改为行末的 ^{YYYYMMDDHHmm} 这种样式，以与 Obsidian 整体的识别和引用机制统一？

而且这样在其他文档中嵌入时也可以最大程度地排除无关信息，因为 locator 并不会显示在预览中。

个人意见，仅供参考。

**Comment by Quorafind** [comment]
保留现在的形式的主要原因是，日记的标题已经包含了日期的信息了，所以才只需要用 HH:mm 的形式来记录当前分钟即可。而且如果用了 Ob 的块引用标记符，那么未来如果不用 Ob 或者用别的软件打开这些文档，就会很突兀了

**Comment by Yubuxin** [comment]
@Quorafind 感谢回复！

了解了，所以目前的方案是为了维护源文件数据的简洁和可读性。这也有道理，只是嵌入其他文档时会出现正文无关的时间戳，终究有点逼死强迫症😂，不知道日后能不能研究出什么折衷的办法。

还有一个疑问，为什么 memos 的源文件会自动生成一个开头的换行符？这个换行符有保存的必要吗？因为 linter 和 pangu 等语法检查插件会自动删除文首的换行符，不知道会不会造成冲突。
