### ISSUE TITLE
因OB与LOG合并库时原来的Memos记录丢失问题？

### ISSUE THREAD

**Issue by kubulo** [Quorafind/Obsidian-Thino#259]
我在设置OB与LOG合同同一库时，把日记有转移，这部分包括了部分由Memos生成的日记。

由于要实现两个软件同步一个库，需要把日记放在“日记/journals”文件夹下，现在重新日记文件夹为库，重新新开一个窗口打开这个“日记”库，这个库下面有以下文件夹：
1、assets，是放指定图片的文件夹。
2、journals，这个文件夹的文件与logseq同步的同一文件夹，是日记.md各个文件，我也想让OB上的memos插件来新建的日记。
3、logseq，这个是LOG软件生成的系统配置文件夹，跟OB无关。
4、page，是原来由OB的memos插件生成的过往的日记。
现在我的需求是需要把由OB的Memos插件新建的日记放在“日记/journals”文件夹下，方便同步于LOG软件中。请问怎样设置才不出错。现在的出错信息如图。

<img width="592" alt="Memos错误提示_2022-09-13_21-03-14" src="https://user-images.githubusercontent.com/74105898/189911668-110ba9f1-8d7a-412b-aa3b-11e8845a2cbd.png">

**Comment by Quorafind** [comment]
因为 Logseq 处理过的文件中会包含logbook类似的标记元素，所以会对原来 Memos 的相关实现产生影响，看一下后边更改获取手段后是否还是一样的情况吧
