### ISSUE TITLE
memos同步问题

### ISSUE THREAD

**Issue by hadwinn** [Quorafind/Obsidian-Thino#260]
在使用obsidian官方同步功能的情况下，在ios端对memos评论后，PC端没有同步评论。

**Comment by hadwinn** [comment]
> 在使用obsidian官方同步功能的情况下，在ios端对memos评论后，PC端没有同步评论。

更正：PC端会同步评论，但是在memos页面不会显示评论，只有在日记页面可见。

**Comment by Ton-yi** [comment]
有安装dataview吗
我使用remotely save时遇到相同问题，后安装dataview解决了
