### ISSUE TITLE
当天记录第一条时，只生成了当天新的日记，而无法将记录内容保存其中。

### ISSUE THREAD

**Issue by raindog116** [Quorafind/Obsidian-Thino#262]
如题目，这几天在使用memos时，当天第一次记录内容时，只能生成新日记文件，而无法将记录内容一同保存在其中。不知道是什么原因。

**Comment by shipengfish** [comment]
> 如题目，这几天在使用memos时，当天第一次记录内容时，只能生成新日记文件，而无法将记录内容一同保存在其中。不知道是什么原因。

需要先创建当天的笔记才行，不然首次记录时，会先生成当天的笔记。

**Comment by Quorafind** [comment]
已修复。
