### ISSUE TITLE
Memos conflicts with sliding panes 

### ISSUE THREAD

**Issue by library0012** [Quorafind/Obsidian-Thino#267]
Memos small conflicts with Sliding Panes 
when set rotated headers in Sliding Panes, creating a new memo will open an additional blank windows like this
![image](https://user-images.githubusercontent.com/66898712/195355216-cb2ea259-2517-42f8-90e7-5aecf53b7d2e.png)

**Comment by Quorafind** [comment]
Please tell me your memos version and also obsidian version.

**Comment by library0012** [comment]
Memos version 1.9.7 
Obisdian version：the last version before 1.0.0，
It seems that the new version doesn't have this bug.
