### ISSUE TITLE
QoL tweak

### ISSUE THREAD

**Issue by menagerie198** [Quorafind/Obsidian-Thino#270]
Could we have this little 'quality of life' styling tweak please - the ability to have the memo render in the Daily as a flat line, ie no bullet?

Also the ability to have more flexibility in the styling of that memo render. Specifically, what I would like is
```
## {TIME}
{{CONTENT}
```
in the 'Experimental>Default Memo Composition' section of 'Settings'. Not important - but would be nice :-)

**Comment by Quorafind** [comment]
I don't think ti is possible now, but I will look into it.
