### ISSUE TITLE
[Bug]: 移动端输入法适配问题

### ISSUE THREAD

**Issue by huangduzhang** [Quorafind/Obsidian-Thino#277]
### Bug Description

文字超过半屏，输入法会挡住光标，无法看到输入的文字。

IOS 16.1
appversion : 1.4.1

### Relevant Screenshot

![IMG_3381](https://user-images.githubusercontent.com/2094098/199903162-fed7f85a-088f-4d04-8e45-835312d33e3e.jpg)

### Obsidian Version

1.4.1(83)

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
开启全屏编辑以后可以解决这个问题。https://thino.pkmer.net/thino/01_thino-basic/thino-editor/
