### ISSUE TITLE
图片上传功能能否支持图床？

### ISSUE THREAD

**Issue by huangduzhang** [Quorafind/Obsidian-Thino#283]
### Feature Requested

rt

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by FeiLZX3Km** [comment]
我认为这个功能需求挺好的，我在写普通笔记的时候，拖入图片都能上传至图床，但用memos写日记时添加的图片却仅为本地上传，如果能够支持插入图片后直接上传至图床就好了，也省得我再次以普通视力打开日记，手动上传图片。

**Comment by Quorafind** [comment]
现在配合 [PicGo Image Uploader](obsidian://show-plugin?id=obsidian-image-auto-upload-plugin) 可以直接上传到图床
