### ISSUE TITLE
[Bug]: Theming irregularity

### ISSUE THREAD

**Issue by Sriramgireesh** [Quorafind/Obsidian-Thino#285]
### Bug Description

Following the v.1.0 update, there a jutting white/black segment that is visible on the on  the left of the memos section when it is placed in the sidebar. 

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/66196487/203480306-af0c1714-bea1-4a9a-9251-2603f82e825d.png)
![image](https://user-images.githubusercontent.com/66196487/203480406-69fb26e4-b599-45b9-8364-68f785a3534b.png)

### To Reproduce

1. Open Memos
2. Place the Memos in the sidebar

### Obsidian Version

1.0

### Which editor are you using?

- [x] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Fixed already.
