### ISSUE TITLE
[Bug]: Memo获取失败，实在是不知道什么原因，求大神帮忙看看

### ISSUE THREAD

**Issue by OMGljy** [Quorafind/Obsidian-Thino#287]
### Bug Description

已经打开“日记”插件，并且使用正常，也设置了日记路径，但是memo无法获取，百思不得其解😂
![image](https://user-images.githubusercontent.com/30697056/204483826-3262871c-3dd1-446b-9b35-b602ffdcda1e.png)

### Obsidian Version

Version 1.0.3 (Installer 1.0.0)

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by HYDlink** [comment]
查了一下，在 FetchAllMemos 这个函数里面，调用了 getAPI() 这个函数，
修改代码以后看到了 stack trace
（为啥 fetchAllMemos 这里的 promise 不把报错信息也给 catch 并且打印出来？这谁知道为啥 Fetch Error）
```
TypeError: Cannot read properties of undefined (reading 'version')
    at getMemosFromDailyNote (plugin:obsidian-memos:9609:62)
    at async getMemos (plugin:obsidian-memos:9837:7)
    at async Object.getMyMemos (plugin:obsidian-memos:10457:12)
    at async MemoService.fetchAllMemos (plugin:obsidian-memos:10621:18)
```
代码如下，就是在访问 `DataviewAPI` 这里，我把 dataview 插件关了，所以返回了个 undefined。
```js
const getAPI = (app2) => {
  var _a;
  if (app2)
    return (_a = app2.plugins.plugins.dataview) === null || _a === void 0 ? void 0 : _a.api;
  else
    return window["DataviewAPI"];
};
```

**解决方案**：启用 DataView 插件

**Comment by SPTAU** [comment]
我也遇到了相同的问题

**解决方案**：
1. 查看_日记_设置中_新建日记的存放位置_
2. 在库中新建对应文件夹

**Comment by Curry30huang** [comment]
主要原因就是没有创建这个文件夹或者之前创建这个文件夹了但是后面改名字，而memos不会同步改名，所以需要自己重新定位一下即可。

**Comment by Quorafind** [comment]
请查看是否还有同样的问题，如果有的话，可以再基于 2.3 以后的版本确定一下复现步骤。
