### ISSUE TITLE
Feature Request: Image inserter command support

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Thino#288]
### Feature Requested

I use the image inserter plugin to illustrate the notes I write, but when I use Memos the commands of this plugin do not appear when I use the command palette.
If I am going to edit the note in the normal way (outside of memos) they do appear.

Are they blocked for some reason?

https://github.com/cloudy9101/obsidian-image-inserter

### Relevant Screenshot

Memos command palette

![image](https://user-images.githubusercontent.com/7627504/205605546-8fffadca-502a-4150-b37d-2a4e350a82d4.png)

Note command palette inside note

![image](https://user-images.githubusercontent.com/7627504/205605694-eae641e0-dedf-46c1-b4d8-1e2213240f19.png)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Supported in latest version.
