### ISSUE TITLE
[Bug]: Four bugs > No comments are saved, no deleted memos are saved in the delete file, memos get sorted randomly, and more!

### ISSUE THREAD

**Issue by m-primo** [Quorafind/Obsidian-Thino#290]
### Bug Description

I have 4 bugs:
1. When I comment on a memo, it's shown in the memo, but when I close the memos and get back again, I found nothing!!
2. When I delete a memo, if the `delete` file doesn't exist, it deletes without an issue, but if the file does exist (if I deleted a memo first time, and this is the second time), it shows `Unable to create new file. Cannot read properties of undefined (reading 'saving')`!!
3. When I create memos at the same minute, the memos gets sorted randomly.
4. (I don't know if this is a bug or not) Search is case sensitive.

### To Reproduce

- Make a comment, close the memos, open it again.. here you go.
- Delete the file `delete` if exists. Delete a note, delete another note.. here you go.
- Create 2-3 memos at the same minute, wait milliseconds, you'll notice they get sorted randomly.
- Create a memo with `Test`, search for `test`.. here you go, nothing found!

### Obsidian Version

1.0.3

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Qm-jmz** [comment]
I have meet the same bug (bug1).

**Comment by Qm-jmz** [comment]
this is same as issue[#227](https://github.com/Quorafind/Obsidian-Memos/issues/227) and pull[#250](https://github.com/Quorafind/Obsidian-Memos/pull/250)

**Comment by Quorafind** [comment]
Now this should be fixed. But the commend feature is gone in current version.
