### ISSUE TITLE
[Bug]: Invalid Date when pulling memo from another note

### ISSUE THREAD

**Issue by jiamingz42** [Quorafind/Obsidian-Thino#291]
### Bug Description

I am able to pull memos from another note tagged with #memo.

However, the date is shown as "Invalid Date".

I tried to put a date as the header. For example

```
# 2022-12-01
```

It is still showning Invalid Date.

### Relevant Screenshot

![14E3F8DE-8BEB-4DA8-B46C-E49F100A120E|400](https://user-images.githubusercontent.com/1160963/206861657-3b23763b-a45e-41cb-8771-27cc14e1691f.png)

### Obsidian Version

1.4.1

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by jzhang-brex** [comment]
I get rid of the invalid date error if I change from

```
# 2022-12-10

- 10:00 Some note
- 11:00 Some note 2
```

to

```
# 2022-12-10

- Some note
- Some note 2
```

However, the Memo plugin will assume all these notes is written in **2022-12-10 00:00:00**. I can't figure out a way to provide the timestamp information.

**Comment by Quorafind** [comment]
Will be fixed in next release.
