### ISSUE TITLE
[Bug]: 无法正确显示评论

### ISSUE THREAD

**Issue by vapensmianm149s** [Quorafind/Obsidian-Thino#294]
### Bug Description

Obsidian-Memos版本1.9.7
Obsidian V1.1.9
评论无法显示，重启后消失

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/7703758/210165639-548a3521-c8fd-47ab-bd09-d6b6fe2a7a6d.png)
![image](https://user-images.githubusercontent.com/7703758/210165666-bd285208-b247-400d-a9d0-f92e43bdc9a3.png)

### To Reproduce

偶然可以显示，重启后消失

### Obsidian Version

1.19

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
下个版本修复 #282

**Comment by hi-yiyang** [comment]
请问修复进度如何？最近发现开启“在原文后评论”选项后memos无法显示评论；关闭该选项插件也不会自动创建block reference。

**Comment by NicodeLee** [comment]
关注+1

**Comment by Quorafind** [comment]
目前该功能已于 v2 版本中暂时去除。等待该功能重新上线后如果还有相关问题，请再打开该 issue。
