### ISSUE TITLE
Feature Request: 侧面板中memos触发的日期面板显示不全

### ISSUE THREAD

**Issue by ku-zhen** [Quorafind/Obsidian-Thino#296]
### Feature Requested

在侧边栏通过@触发的日期选择面板不置顶，会被编辑器面板掩盖。具体请看截图，谢谢~

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/61906420/210550900-c50d4496-a42d-4af7-8e3d-e0013a449e75.png)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
下个版本修复

**Comment by Quorafind** [comment]
已修复。
