### ISSUE TITLE
Feature Request: Insert above ^block-links

### ISSUE THREAD

**Issue by dang1507** [Quorafind/Obsidian-Thino#300]
### Feature Requested

Currently when you insert a memo, it always inserts below the last line in the header section

![image](https://user-images.githubusercontent.com/60278428/212494088-337600fe-171d-4640-a222-1e9b0f23f4c0.png)

It would be nice if there was an option to account for link markers and either insert immediately above the marker, or treat markers as headers so that it doesn't require manual intervention.

![image](https://user-images.githubusercontent.com/60278428/212494098-df368a1b-606d-445b-8147-1d1f21f965b8.png)

Thank you for this add-in. It's really cool. 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
fixed
