### ISSUE TITLE
[Bug]: cannot use HH:mm:ss as time format

### ISSUE THREAD

**Issue by torytatsumaki** [Quorafind/Obsidian-Thino#303]
### Bug Description

[Bug]: cannot use HH:mm:ss as time format please support https://momentjs.com/ formating for time and date

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/56187753/213862865-a45efe3e-9280-4feb-b2c5-58a32ff44da3.png)
thats okay 

![image](https://user-images.githubusercontent.com/56187753/213862881-df25050f-20a1-4cc4-8c46-ce356b58429e.png)
this problematic

### To Reproduce

1 goto experimental options
2 default memo composition
3 try use {HH:mm:ss} 

### Obsidian Version

1.1.9

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Supported in latest version
