### ISSUE TITLE
[Bug]: 无法使用dataview查询文末添加的tag

### ISSUE THREAD

**Issue by Ton-yi** [Quorafind/Obsidian-Thino#305]
### Bug Description

无法使用dataview查询文末或换行时添加的tag

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/73752817/214536047-c852532b-32ad-428a-85f1-b596ff494a04.png)

### To Reproduce

尝试在文末以及换行处多添加一个空格即可，希望能自动识别添加

### Obsidian Version

1.1.9

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
已修复
