### ISSUE TITLE
[Bug]: t is not defined

### ISSUE THREAD

**Issue by MotionEri** [Quorafind/Obsidian-Thino#312]
### Bug Description

无论我添加哪种检索式，都会在右上角弹出t is not defined
并且添加不成功

### Relevant Screenshot

![Snipaste_2023-02-08_17-01-03](https://user-images.githubusercontent.com/26498948/217483108-d30c6e1d-d303-4686-8fa5-47980a16f21a.png)

### Obsidian Version

0.15.9

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by lienhui68** [comment]
I have the same issue, too.

**Comment by lienhui68** [comment]
My Obsidian version is 1.1.16

**Comment by lienhui68** [comment]
我debug了一下，是由于多次创建检索，导致创建query.md文件引起的这个错误
<img width="552" alt="image" src="https://user-images.githubusercontent.com/9602039/231644296-9fb36174-8a83-4071-bfd3-7b2c4d84a0c4.png">
但是，删掉query.md文件后，创建检索不成功显示检索按钮只是创建query.md文件，再次创建检索就又报这个错了

**Comment by lixia2993** [comment]
me too

**Comment by KeithW0726** [comment]
作者是不是已经太监了啊

**Comment by FCncdn** [comment]
我也遇到这个问题，后来发现是 日记/新建日记存放位置 多加了一个 `\` ，删掉之后就正常了

**Comment by Quorafind** [comment]
已修复。
