### ISSUE TITLE
Feature Request: 对移动端相机的支持

### ISSUE THREAD

**Issue by Rindiaco** [Quorafind/Obsidian-Thino#313]
### Feature Requested

我对memos 大部分的使用场景都是在移动端，如果我想拍张照片再去发表memos，就得先用相机拍摄，在到OBsidian里面打开memos，再去选择图片。如果能直接在memos编辑界面添加，直接跳转到相机获取照片的功能就好了。

直接通过相机拍摄图片，插入待编辑的memos

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Obsidian 并不提供该功能，可以期待未来的 Web 版本。
