### ISSUE TITLE
[Bug]: 有链接和有超链接的搜索结果都显示为空白

### ISSUE THREAD

**Issue by yoghurtdewdew** [Quorafind/Obsidian-Thino#314]
### Bug Description

bug：有链接和有超链接的搜索结果都显示为空白

另外，请教一下：
有链接和有超链接分别对应的内容是？obsidian链接和http链接？
app名称开头的 url scheme是否算链接？算哪个链接呢？

### Relevant Screenshot

搜索结果：
![image](https://user-images.githubusercontent.com/63794438/221179515-f7eaeda7-1702-46e9-9e0b-ce52a570c4af.png)
![image](https://user-images.githubusercontent.com/63794438/221179558-220b0c88-e221-48f8-9f8a-4de81ef5b576.png)

含obsidian文档链接的内容 ![image](https://user-images.githubusercontent.com/63794438/221179299-a537c49a-260f-4a45-bd36-f09e19c41ddc.png)

含其他链接的内容
![image](https://user-images.githubusercontent.com/63794438/221179449-c3524f96-7fb1-484c-8cda-a8bb99e055ed.png)

### To Reproduce

在右上角直接点击 快速筛选

### Obsidian Version

version 1.1.15（installer 1.1.9）

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
有链接指的是有内部的 thino 链接，有超链接指的是有 http 链接
