### ISSUE TITLE
[Bug]: 输入第一个中文汉字时，与中文输入法不兼容

### ISSUE THREAD

**Issue by iamfeiyu** [Quorafind/Obsidian-Thino#315]
### Bug Description

输入第一个中文汉字时，导致输入法闪屏且无法输入，只有首先存在一个字符，输入才能正常

### Relevant Screenshot

![Memos's bug](https://user-images.githubusercontent.com/25132486/223981630-15b5fe24-98ca-4c27-b393-84bb1a4c67c6.gif)

### To Reproduce

1. 安装“华宇拼音输入法”；
2. 切换为中文输入；
3. 打开Memos编辑界面；
4. 将光标焦点放在编辑框；
5. 输入中文将可以看到输入法候选列表快速闪屏，无法正常显示，也无法选择中文输入到编辑框内。

### Obsidian Version

1.1.16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by FlameTEXT** [comment]
在小狼毫输入法也遇到这个问题，但是微软的输入法就没有这个问题。
感觉这可能是输入法的问题……

**Comment by sybhdxb** [comment]
我用的手心输入法，也是这个问题，先输入一个字符，数字、标点、英文都行，然后就能正常输入中文了

**Comment by Quorafind** [comment]
已修复。

**Comment by freelixilong** [comment]
linux下 也有類似的問題 版本1.6.5， 輸入法： ibus，选择中文后，无法输入中文
