### ISSUE TITLE
[Bug]: 移动端打字卡顿感明显

### ISSUE THREAD

**Issue by Yubuxin** [Quorafind/Obsidian-Thino#316]
### Bug Description

目前最新版Obsidian（iOS 1.4.3）上的memos，输入框打字卡顿已十分明显（一般刚开始两三行没问题，再往下写就会有明显的粘滞感），再配合上输入长文后键盘遮挡的问题，几乎没法用……

### Obsidian Version

移动端为1.4.3，桌面端1.1.16，均为目前最新版本

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
已修复。
