### ISSUE TITLE
Feature Request: Change tab bar icon to look same with the rest

### ISSUE THREAD

**Issue by khanhtoan529** [Quorafind/Obsidian-Thino#317]
### Feature Requested

The icons on the tab bar of Memos look quite different to the rest of Obsidian. Can you fix it in the next release?

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/94975142/226683339-534d78d9-220f-489b-8c08-36b529197008.png)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by jackchealdang** [comment]
Agree, having same issue on mobile as well.

![image](https://github.com/Quorafind/Obsidian-Memos/assets/44298230/8e4ac03a-6fdc-4bb9-8713-5ec48fe1904e)

![image](https://github.com/Quorafind/Obsidian-Memos/assets/44298230/c46f03f1-fe65-49bc-9ad0-ef5a9d3e2083)

**Comment by Quorafind** [comment]
Fixed already
