### ISSUE TITLE
Support completing items

### ISSUE THREAD

**Issue by wenlzhang** [Quorafind/Obsidian-Thino#32]
Currently, one can `READ`, `MARK`, etc., items. It would be great if one can also mark an item as completed/checked, i.e. marking `- [ ] 19:00 in daily note.` as `- [x] 19:00 in daily note.`. This issue is also related to the following one: https://github.com/Quorafind/Obsidian-Memos/issues/31.

It would be even better if this plugin can automatically append timestamp when completing such items. For instance, when marking the item above as completed, it would become something like `- [x] 19:00 in daily note. ✅ 2022-01-12T20:00`.

**Comment by Quorafind** [comment]
I am still hesitate to add checkbox on the memo, need some good UI design to make it works.

**Comment by wenlzhang** [comment]
> need some good UI design to make it works.

By this, do you mean the way of displaying different types of items/memos? If this is the case, then maybe the UI does not need to change much/apparently.

There can be three types of items in the daily notes: List items, Unchecked task items and Checked task items. However, these three types of items can be displayed the way as they are now, i.e. only the text part of the items would display, not their types, as can be seen in the following screenshot. From this prospective, the UI does not need to change.

What I was thinking about is that there can be a command at the top right corner of each memo, e.g. `CHECK`, for marking List items and Unchecked task items as Checked task items. Again, the way of displaying the three types of items does not need to change in the UI; they only need to change in the corresponding daily notes. This way, one can process items in a more UI-friendly manner, e.g. on mobile devices.

On the other hand, in order to determine which types of items to display, there can be new query types for choosing whether to include/exclude certain types of items. For instance, one may want to hide/filter out Checked task items from the UI and heat map.

Moreover, in order to support different statuses of task items that are supported by your another plugin, once the task items are marked in the corresponding daily notes (not in the Memos GUI), whether as Checked `[x]`, Forwared `[>]` or other statuses, they can all be treated/identified/displayed the same way as Checked `[x]`. This way, there would still be three types of items/memos in total.
https://github.com/Quorafind/Obsidian-Task-Changer

<img width="1150" alt="Screenshot 2022-01-13 at 08 03 37" src="https://user-images.githubusercontent.com/44930227/149284397-bf3c42ff-daf0-4f01-a261-47e67b061e95.png">

**Comment by wenlzhang** [comment]
> I am still hesitate to add checkbox on the memo, need some good UI design to make it works.

In the future, it would be great if Memos can somewhat distinguish the three types of items in the UI, i.e. list items, uncompleted tasks and checked/completed tasks. For instance,

- For uncompleted tasks, there can be a checkbox preceding the item text, such that one can complete the task by clicking the checkbox. This is also related to the following issue: https://github.com/Quorafind/Obsidian-Memos/issues/32
- For completed tasks, the text can be strike-through and greyed out.

Of course, the above can be set in the configuration pane, in case some users do not like it.

**Comment by rapatel0** [comment]
Adding to the above comment. It would be nice to have status as part of the filtering. Completed vs non completed tasks.

**Comment by red-co** [comment]
If you use tag to mark them, what are the drawbacks? just like #-ing #-ed #-checked, 
(｡･ω･｡)ﾉ

**Comment by ksdavidc** [comment]
um, I think the discussion is making this more complicated than it needs be. The necessary UI pretty much already exists in the plugin right now. Just make the existing elements toggleable. At least that would be a good first step. Later, adding multiple states, and menu items...

<img width="291" alt="Screen Shot 2023-09-22 at 5 10 27 AM" src="https://github.com/Quorafind/Obsidian-Memos/assets/62230004/2f268ffc-70d4-49d0-8163-827167fc12a6">

Perhaps this is already in v.2, which I have not checked out, but if not, I hope it comes in. It really is a missing feature.

**Comment by Quorafind** [comment]
Supported.
