### ISSUE TITLE
Feature Request: 请问分享中的图片页脚选项

### ISSUE THREAD

**Issue by shootheart** [Quorafind/Obsidian-Thino#320]
### Feature Requested

当前只有`{UserName}`、`{UserDay}`、`{MemosNum}`三个变量可选
是否还有其他可选变量呢，或者是否考虑新增一些，比如创建时间等

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
样式已经支持创建时间。其他变量后续不一定计划，暂时关闭 issue
