### ISSUE TITLE
Thino(Memos 2.1.x) is ready for test

### ISSUE THREAD

**Issue by Quorafind** [Quorafind/Obsidian-Thino#329]
> Thino(Memos 2.1.x)  is ready for test, if you are interested in it, please contact me @Boninall via Obsidian discord OR mail: 
> [Bonopengate@gmail.com](mailto:Bonopengate@gmail.com)
> Thino(Memos 2.1.x) 正在封闭测试中，如果你对此感兴趣，请在 Obsidian discord 上联系我 @Boninall 或者邮件：[Bonopengate@gmail.com](mailto:Bonopengate@gmail.com)

> Updated: It is now in internal testing on Pkmer, and you can try it out as a Thino insider. If you have previously donated to me through Buy me coffee or other means, don't worry, I will give you a trial slot! Please feel free to message me privately.
> 更新：现在它正在 Pkmer 网站上内测发布中，你可以购买 Thino insider 来测试它，如果你之前有任意形式捐赠过我，不管数额多少，你都可以随时联系我获取 thino insidier 名额！

> If you are overseas and would like to participate in the insider program, please feel free to email me at any time!

Pkmer Website: [PKMer Thino](https://pkmer.cn/products/productDetails/)

![image](https://github.com/Quorafind/Obsidian-Memos/assets/13215013/cf816acd-e8f3-4634-9ce0-a7ae432b14db)

Releases Note: https://ob.boninall.com/
Thino doc: [Thino doc](https://ob.boninall.com/_Update/Thino/Thino+MOC)

**Comment by shiyilinxi** [comment]
今天打开 内部任务不以任务形式显示了，也不能直接点击完成

**Comment by LazyCountry** [comment]
v2.0.6 版本，连接到外部文件的memo，虽然也一样可以点击跳转到外部文件，但没有像原先编辑器里显示下划线以及特殊的颜色。

**Comment by hellspector** [comment]
不用一开始就站在道德点上说这里不能发不关于issue的事情，其它渠道发你信息你回么？这里发一条信息，不到几分钟就回了，怎么了，还想包装自己多么高大上吗？想都能想到你又在群里找安慰，说今天又发生了什么不愉快的事情，然后一堆人安慰你一下。这么稀罕你的插件，你就在那个群里用用，称称大佬就好了，发出来干啥？找人发电，还不允许别人说两句了？真是既立又立。

**Comment by Quorafind** [comment]
> This issue would be changed when a new update is released.
> 这个 Issue 会在每次内测更新的时候更新说明；

# 新功能

- #亮点 【多文件来源 for MEMOS】具体操作逻辑是设置一个文件夹，在这个文件夹下的所有 Markdown 文件都会被视作 Memos，其它的编辑、归档、删除以及双向编辑都一样；
   - 注意：目前不支持子文件夹
   - 基于上边的操作中，如果发现存在一个 Memos 没有唯一 ID 会在这个 Memos 的右上角显示一个修复按钮，而这个 Memo 因为没有唯一 ID 所以不可编辑；
       - 但是一般情况下会默认直接增加新的 ID；
- #亮点【多文件来源 for MEMOS】检索内容且复制全部 Memo 的时候，Memo 没有正确被处理；
- 编辑器按 Alt+1、2、3 切换保存位置；
- 编辑器按 Ctrl 或 CMD + L 可以快速切换当前的 MEMO 状态；
- 点击左侧栏的随机回顾按钮可以直接更新随机回顾的内容；
- #亮点 修改设置可以实时变化 Memos 的内容，目前支持用户名、保存位置（也就是解析哪个标题下、Memos 文件等）
- 重构了 Memos 的菜单，提供了一个新的选项：复制 Memos 内容以及提供了查看当前的 Memos 字数的功能；
- 只要 Memos 范围内在按 i 会聚焦到编辑器，按 o 会聚焦到搜索框、按 Esc 会退出编辑状态；

# 修复

- #亮点 Memos 首次打开的启动过慢问题，从原来的 320ms 降到 26ms；
- 检索式的标题没办法编辑；
- 筛选没有 Tag 的 Memo 的快捷路径会忽略换行后的 Tag 的 Memo；
- 给部分按钮加上 Tooltip 提示；
- Banner 上的数字过大的时候会很拥挤；

# 变更

- 暂时下线批注 memo 显示内容；
- Memo 多了四个 css 选择器，分别为：data-source-type、data-memo-id、data-memo-type 以及 Pin 与否的选择器；
- 下线了全局切换 Memo 输入状态的命令；
- 移动端不能正常启动的问题；


---

# New Features

- [Multiple File Sources for MEMOS]: The specific operation involves setting up a folder, and all Markdown files under this folder are treated as Memos. Other operations like editing, archiving, deleting, and bidirectional editing remain the same;
   - Note: Subfolders are currently not supported.
   - Based on the above operation, if a Memo is detected without a unique ID, a fix button will be displayed in its top right corner. This Memo is not editable due to the absence of a unique ID;
       - However, in most cases, a new ID will be automatically added by default.
- [Multiple File Sources for MEMOS]: When searching for content and copying all Memos, the Memo isn't processed correctly;
- In the editor, press Alt+1, 2, 3 to switch save locations;
- In the editor, press Ctrl or CMD + L to quickly toggle the current MEMO's status;
- Clicking the random review button in the left sidebar will instantly update the content of the random review;
- Changing settings will reflect real-time changes in Memos' content. Currently supports username, save location (i.e., determining under which title, Memos files, etc.)
- The Memos menu has been refactored, adding a new option: copying the content of Memos and providing a function to view the current word count of Memos;
- Within the Memos scope, pressing 'i' will focus on the editor, pressing 'o' will focus on the search box, and pressing 'Esc' will exit the editing mode;

# Fixes

- Addressed the slow startup issue when Memos are opened for the first time, reduced from 320 ms to 26 ms;
- Query title cannot be edited before;
- NO_TAG will not match memo that using tag in new line;
- Added Tooltip to parts of buttons;
- Numbers on the Banner become congested when they're too large;

# Changes

- Temporarily suspended the feature that annotated memos;
- Memo now includes four additional CSS selectors, specifically: data-source-type, data-memo-id, data-memo-type, and a selector for whether it's Pinned or not;
- The global command to toggle Memo input status has been deactivated.
- Mobile issues；

**Comment by pashashocky** [comment]
@Quorafind, heya, wondering if you'd be able to let me test this too?
