### ISSUE TITLE
Feature Request: Ability to see and change source file

### ISSUE THREAD

**Issue by ksdavidc** [Quorafind/Obsidian-Thino#342]
### Feature Requested

1. I know there is a dropdown that lets you get to the source, but I would like to see the name before I click it. 

- real bonus: if it were a proper link, I could use ctrl/command to preview it!!!

2. In fact, it would be good if we could see the source file immediately in all the memos in the main memo page, without needing the dropdown.

3. I notice that memos I create in regular notes get marked as having "invalid date". The name of the file could go here instead. That would tell me it is not a daily note, but  a regular file and let me know where it is. Bonus points if it were clickable.

4. In fact, while we are at it, the date on the memos from daily notes should also be clickable to the file. It could be formatted according to the format used in the daily note plugin.

- more bonus: If it is a proper link, I could also preview it.

5. I would like be able to move a note from one file to another. For example, I use memos in daily and regular notes. I would like to know where a certain memo is, and move it out of a daily note into a relevant regular note, or vice versa

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
May be available in 2.0.13 , if you are interested in it, I will add you into the waiting list.

**Comment by ksdavidc** [comment]
By all means, sounds lovely!

**Comment by Quorafind** [comment]
Supported in latest version. You can press `Ctrl` + `Shift` key to hover thino to see the source.
