### ISSUE TITLE
[Bug]: memo 視窗無法切換成其他視窗

### ISSUE THREAD

**Issue by kin30528** [Quorafind/Obsidian-Thino#345]
### Bug Description

您好，我在寫筆記時若有靈感會打開 memos 馬上記錄下來，但點擊 memos 寫完後，碰到以下問題：
1. 無法回到上一頁繼續寫剛才的筆記
2. 點擊檔案瀏覽區的檔案也不能切換回來

雖然不要使用筆記區域打開 memos 就能解決，但還是希望改善，其他 plugin 像是 custom frames、map view 不會有這些問題。謝謝您用心製作的 plugin

memos 版本：1.9.7

### Obsidian Version

1.4.16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
2.3.4-1 的高级设置里面已经支持，请手动开启。
