### ISSUE TITLE
Feature Request: Open note links in same view not in a split tab

### ISSUE THREAD

**Issue by smolprogress** [Quorafind/Obsidian-Thino#349]
### Feature Requested

Currently clicking on a link from a memo opens the note in a split tab. Would prefer it to be in the same view or in a new tab if for desktop

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
now it is possible when you toggle `Allow navigation from view to Thino or Thino to view` in advanced settings.
