### ISSUE TITLE
[Bug]: 笔记发布后自动删除的问题

### ISSUE THREAD

**Issue by PPsteven** [Quorafind/Obsidian-Thino#353]
### Bug Description

配置如下
![image](https://github.com/Quorafind/Obsidian-Memos/assets/35828860/a5b4021d-56d8-4f18-af65-4a7b903514f1)

Memos 在发布记录后，1s 后自动在列表中删除

# 复现流程
1. 配置 "在指定标题后插入 Memo"为 # Memos
2. 配置 "解析制定标题后的 Memo"为 # Memos
3. 发布新记录，1s后自动删除

# 原因：
Memos 是基于日记功能开发，但是生成新的日记中如果没有 # Memos这个标签，那么插件不会自动创建这个标签，从而在解析的时候是无法获取到该条日记。

# 解决方法：
用户侧：日记需要配置模板问卷，使得新建日记的时候自动创建 # Memos 标签。
产品侧：当  # Memos 标签找不到的时候，自动在日记文件中创建这个标签。

让人疑惑的是，这个bug几乎小白只要上手配置都会碰到的问题，居然没有修复。在全网搜索了大量教程后，发现很多写教程的人都是使用错误的用法，部分教程 "解析制定标题后的 Memo" 一项配置的都是空，但是 "在指定标题后插入 Memo"是有值的。这个很明显是错误的用法。README.md 也没有在这个功能上有所解释。

在2022年就有人提出这个问题 https://github.com/Quorafind/Obsidian-Memos/issues/243 

看了作者的代码后，发现作者在第一个commit的时候就考虑到这个问题，但是 createInsertAfterIfNotFound 这个函数却迟迟没有写，估计是忘记了，希望填上这个坑。

![image](https://github.com/Quorafind/Obsidian-Memos/assets/35828860/d28bdabe-d3f0-481d-927d-44764014e1fd)

### To Reproduce

1. 配置 "在指定标题后插入 Memo"为 # Memos
2. 配置 "解析制定标题后的 Memo"为 # Memos
3. 发布新记录，1s后自动删除

### Obsidian Version

1.9.7

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by PPsteven** [comment]
#243 关联issues

**Comment by juestchaos** [comment]
新版的 thino 无法复现这个问题了

**Comment by Quorafind** [comment]
请查看是否还存在这个问题，如果还存在的话，可以再提供新的复现步骤。
