### ISSUE TITLE
[FR][Thino]: 回收站里的Thino不要算到总数里

### ISSUE THREAD

**Issue by hibicious** [Quorafind/Obsidian-Thino#363]
### Feature Requested

![image](https://github.com/Quorafind/Obsidian-Memos/assets/86993516/b1979801-6031-49e7-ac1c-b4fb4320c6a8)
我把一些测试的thino删掉了，但是总数上面依然回计算。想要他不计算回收站里的Thino

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by juestchaos** [comment]
已经收入到内部讨论

**Comment by Quorafind** [comment]
最新版本已经不再显示回收站中的 thino 数量。
