### ISSUE TITLE
[Bug][Thino]: 编辑一条 thino 后会抹去由 Obsidian 生成的段引用 ID

### ISSUE THREAD

**Issue by alexinea** [Quorafind/Obsidian-Thino#366]
### Bug Description

List 模式下，每一条 thino 都是一条 List Item，如在 Daily 下创建的 Thino：

```
- 09:01 一二三四五
```

当我们通过其他笔记对该条 List Item 引用时，Obsidian 会为该条 List Item 打上段 ID：

```
- 09:01 一二三四五 ^0f817d
```

接着我们在 Thino 内编辑这条 thino record（比如在中间加一个标点），点击保存（Note It）

我们可以发现，`^0f817d` 被覆盖了，其他笔记对这条 List Item 的嵌入式引用就失效了。

### To Reproduce

1. 写一条 thino，LIST 模式，写进 daily note 中
2. 在一个笔记（假设代号 A）中使用 `![[2023-12-25^0f817d]]` 嵌入式引用
3. 编辑这条 thino，保存
4. 这条 thino 尾部的 `^0f817d` 丢失
5. 笔记 A 的嵌入式引用失效

### Obsidian Version

0.4.16

### Thino Version

2.1.4

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by alexinea** [comment]
刚才测试发现，在老版本的 Obsidian Memos（Memos 插件市场最后一个版本）是没有的 🫨

**Comment by juestchaos** [comment]
未能复现 ,改动之后 对应 blockid 会变化
![image](https://github.com/Quorafind/Obsidian-Memos/assets/241007/c0b8dda8-f607-4186-bd02-a9953fb51e7b)

**Comment by Quorafind** [comment]
最新版本已修复。如果还有问题请重新打开 Issue 且提供复现步骤。
