### ISSUE TITLE
[FR][Thino]: 希望可以对输出到日记的任务复选框，指定到某标题下

### ISSUE THREAD

**Issue by AyuHero** [Quorafind/Obsidian-Thino#367]
### Feature Requested

因为输入是文字和任务换着输入的，文字和任务混杂在一起一个标题下，很难清晰的看清楚输入的想法和要做的任务，希望可以对输入的任务增加一个可以指定标题的选项，输入的文字是一个标题下，输入的任务是另一个标题下

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
已支持，Pro 用户可以自由设置任务插入的位置
