### ISSUE TITLE
[Bug][Thino]: 卡片置顶取消置顶反复操作之后会提示不存在

### ISSUE THREAD

**Issue by jjtenger** [Quorafind/Obsidian-Thino#368]
### Bug Description

存储位置设置为日记时，对多张卡片反复执行置顶取消置顶操作后，会提示卡片不存在

### Obsidian Version

1.5.3

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
已经收入内部讨论

**Comment by juestchaos** [comment]
未能复现

**Comment by juestchaos** [comment]
未能复现，辛苦提供更多信息

**Comment by juestchaos** [comment]
未能复现，辛苦提供更多信息

**Comment by juestchaos** [comment]
请问是否是因为开启了同步引发的？

**Comment by Quorafind** [comment]
请提供更多信息再重新打开 Issue
