### ISSUE TITLE
[Bug][Thino]: Failed to find daily notes folder

### ISSUE THREAD

**Issue by jjtenger** [Quorafind/Obsidian-Thino#369]
### Bug Description

存储位置从日记切换到多文件之后，点主页顶部的刷新按钮，提示：Failed to find daily notes folder。
PS：日记文件夹是被我删掉了，但是多文件模式下不应该检查日记文件夹了吧。

### Obsidian Version

1.5.3

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
已经收入到内部链接

**Comment by juestchaos** [comment]
我测试了下，好像切换模式时候第一条才会有这个提示，等待模式对应文件和文件夹建立后，不会出现此内容

**Comment by Quorafind** [comment]
2.3.2 如果你启用 pro 版本且去除 daily note 的监测的话，那么不会再监测日记文件夹。
