### ISSUE TITLE
[Bug][Thino]: 当天日记文件已存在，无法插入新memo；刷新后也不显示历史记录

### ISSUE THREAD

**Issue by hongsi466474** [Quorafind/Obsidian-Thino#371]
### Bug Description

今天才开始用memos和thino，两个都出现能自己新建当天的日记文件并记录第一次的memo，然后就无法插入第二条了，说是“无法创建日记，请检查是否存在文件夹”。

并且对于已创建的第一条memo，在memos/thino页面点击刷新后就没有记录了：已存在的日记文件没有变动，但memos/thino页面热力图、以及上面的三个数值都归零了。

（今天更新了obsidian版本，在更新前是v1.4.16，出现了这两个问题才想看看更新会不会解决，所以更新到了v1.5.3，还是有这俩问题）

（尝试了前面 https://github.com/Quorafind/Obsidian-Memos/issues/355 这个的修复方法，没起作用）

### Relevant Screenshot

能新建第一条mome
![image](https://github.com/Quorafind/Obsidian-Memos/assets/147518186/ec68b26d-83e6-42de-b517-54dd2773b9d3)
继续写第二条报错
![image](https://github.com/Quorafind/Obsidian-Memos/assets/147518186/d6102842-0bc9-4ed8-a901-7accecc5f133)
刷新后归零，但日记还在
![image](https://github.com/Quorafind/Obsidian-Memos/assets/147518186/60d44ba3-43e9-4b7c-bd13-2df3cb21a63b)
再想创建memo同样报错
![image](https://github.com/Quorafind/Obsidian-Memos/assets/147518186/b6f0e11c-096b-40bb-a6a6-bab543952658)

### Obsidian Version

v1.4.16和v1.5.3

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
你是独立使用，还是一起开启的？
另外日记插件时如何设置，能否提供下

**Comment by hongsi466474** [comment]
> 你是独立使用，还是一起开启的？ 另外日记插件时如何设置，能否提供下

一起开过，也独立用过，都有问题。以上截图是只开了thino。
日记设置如下
![image](https://github.com/Quorafind/Obsidian-Memos/assets/147518186/572335ca-e8aa-442c-86ad-cdf8d19d5db4)
模板跟着知乎写的
![image](https://github.com/Quorafind/Obsidian-Memos/assets/147518186/2fdbbf0e-16f8-47a4-b032-e076fd35affd)
由thino创建的日记
![image](https://github.com/Quorafind/Obsidian-Memos/assets/147518186/ddd53c11-b7cf-4061-96d8-8736ed28393a)

**Comment by juestchaos** [comment]
没法复现，或者你可以通过，pkmer 个人中心的二维码，联系我，给我一份你的库配置

**Comment by hongsi466474** [comment]
> 没法复现，或者你可以通过，pkmer 个人中心的二维码，联系我，给我一份你的库配置

不好意思，我没有找到pkmer 个人中心有二维码，是我理解有误吗？还想请教一下分享库配置是指分享.obsidian这个文件夹吗？

**Comment by juestchaos** [comment]
是有的，你可以个人中心，或者联系qq 群群主，都可以联系到我

**Comment by TaoTaoTaos** [comment]
我也遇到了同样的问题，也许是插件冲突？我也是在有日记模板的情况下，memo插件似乎不能在已有日记里自动加记录了

**Comment by juestchaos** [comment]
请提供更多信息，当前信息无法判断问题
