### ISSUE TITLE
[FR][Thino]: 增加加密控制显示的个人隐私库功能

### ISSUE THREAD

**Issue by aiyou9** [Quorafind/Obsidian-Thino#372]
### Feature Requested

在记录时，能够勾选存入隐私库，在ui上是隐藏的，显示需要勾选显示隐私库，并输入密码

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by juestchaos** [comment]
测试 2.3.10-12

**Comment by Quorafind** [comment]
已经支持
