### ISSUE TITLE
[FR][Thino]: 增加读取ob库中已有文件，文件夹，白板的功能，可以导入thino，或者单独作为thino的其他存储库，进行管理

### ISSUE THREAD

**Issue by aiyou9** [Quorafind/Obsidian-Thino#373]
### Feature Requested

这样可以，更好将其他文件中的文本，用thino后面出的各种ui界面，进行展示，提高插件的开放性

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
不支持导入的原因是因为对应的数据中不包含时间属性，会导致只能强行加上时间属性。
