### ISSUE TITLE
Feature Request: Support different insert locations for memos and tasks

### ISSUE THREAD

**Issue by harrystuart** [Quorafind/Obsidian-Thino#377]
### Feature Requested

If my daily note has two subheadings `memos` and `tasks`, I would like to be able to insert text-memos beneath `memos` and task-memos beneath `tasks`. If there is already a way to do this, please let me know.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Available in latest version for pro users.
