### ISSUE TITLE
[Bug]: spellcheck turned off but red underline

### ISSUE THREAD

**Issue by strongMuscle110** [Quorafind/Obsidian-Thino#379]
### Bug Description

although spellcheck is turned off inside obsidian
there will be red underlines. 
For instance writing "sss" will result... with a red underline.  
It seems obsidian in fact disabled spellchecker e.g. creating new native obsidian note writing and then writing  ''sss''... no red underline. 

So I believe there need to be some tweaking made in this plugin. In order to completely disable spellchecker in this context. Meaning only if I write or edit a memo, there are red underlines. but after finishing the memo the red line will disappear or when in memo-read-mode.

TLTR:

- [X] -  Setting: Spellcheck global off
- [x] - Read/Edit obsidian note: Spellcheck off
- [x] - Finished memos: Spellcheck off
- [x] - Read memo: Spellcheck off
- [ ] - Write memo: Spellcheck on
- [ ] - Edit memo: Spellcheck on

### Relevant Screenshot

![image](https://github.com/Quorafind/Obsidian-Memos/assets/155840154/672fe5b0-e1a5-45f1-a542-eab232b1b8dd)

### To Reproduce

option/ editor/ behaviour/ spellcheck (off)

### Obsidian Version

1.5.3

### Which editor are you using?

- [x] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Could you try the lastest release?

**Comment by Quorafind** [comment]
If you still have any issue about this, please open this again.
