### ISSUE TITLE
[Bug][Thino]: 默认打开方式触发不稳定，希望增加该设置项

### ISSUE THREAD

**Issue by DanShui-Yu** [Quorafind/Obsidian-Thino#382]
### Bug Description

现在的交互好像有点混乱，左键点按钮是在当前页面直接跳转（并且不能通过后退回到原来的界面，一旦误操作很麻烦！），全局打开快捷键似乎是遵循最后一次右键的打开方式，但如果最后一次用的是float window或者center那么快捷键打开会变成在右侧分屏。

### To Reproduce

反复测试后发现如下情况可稳定复现：
1. 打开ob
2. 右键点击图标以float window打开thino，thino为完整界面
4. 关闭thino
5. 全局快捷键呼出thino
6. thino以float window样式打开，但为简化界面
7. 关闭thino
8. float window关闭，但**thino界面又在左侧sidebar打开了！**
9. 关闭sidebar上的thino
10. 全局快捷键呼出thino，thino在左侧sidebar打开
11. 关闭thino
12. 再次鼠标右键点击图标以float window打开thino，thino为完整界面
13. 关闭thino
14. 全局快捷键呼出thino
15. **thino变为在右侧分屏打开**
16. 重复11-14步，结果始终为15。
17. 如关闭ob重启，再用快捷键呼出，则从第6步开始重复

### Obsidian Version

1.5.3

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
现在应该不会再贸然新建一个视图
