### ISSUE TITLE
[Bug]: 置顶后,笔记无法操作，无法取消置顶

### ISSUE THREAD

**Issue by Kiss-World** [Quorafind/Obsidian-Thino#383]
### Bug Description

显示笔记不存在。
win11
ob1.5.3
(手动到元数据里面删除的内容)
同时在桌面端和手机端，都出现过数据被删除的情况，令信任感大大降低~

### Obsidian Version

1.5.3

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
没有版本信息
提供下截图或者你的操作步骤

**Comment by juestchaos** [comment]
没有版本信息
提供下截图或者你的操作步骤

**Comment by Quorafind** [comment]
如果还有复现步骤的话，请重新开启
