### ISSUE TITLE
Feature Request: 从daily note新建memo的话，不能读到HH:mm:ss格式

### ISSUE THREAD

**Issue by lzz66** [Quorafind/Obsidian-Thino#385]
### Feature Requested

问题是：现在的thino从daily note新建memo的话，不能读到HH:mm:ss格式，只能读HH:mm格式，这样会带来两个问题:1.丢失了ss秒的信息，2.我同一分钟内输入多段话的时候，显示的顺序在daily note（自上而下）和memos（应该是自下而上）实际上是相同的，而理论上应该是相反的。

所以能不能帮我实现读取daily note里面秒的信息到memos主界面啊，万分感谢

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Ami-Nous** [comment]
同一分钟内笔记的显示顺序确实是反的，很不方便，参见 #380

**Comment by Quorafind** [comment]
已支持
