### ISSUE TITLE
Feature Request: Cursor should focus in the text area

### ISSUE THREAD

**Issue by gerroon** [Quorafind/Obsidian-Thino#386]
### Feature Requested

Hi

When I call "note it" from Ctrl-P it opens Memos but it does not focus in the text area, which is a bit of friction. It would be nice "Note it" actually goes into the edit mode right away

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Could you try the latest version of thino? And see if this issue remains.
