### ISSUE TITLE
[FR][Thino]: 希望给标签添加排序功能，例如数量排序

### ISSUE THREAD

**Issue by Drmiaomiao** [Quorafind/Obsidian-Thino#390]
### Feature Requested

谢谢bonbon开发这么好用的插件，希望方便的时候能给tag添加排序功能，例如使用数量排序，或者自定义排序，这样可以清晰显示哪些tag下的笔记最多，方便笔记聚合结构化。

### Relevant Screenshot
![54866ecc832115c406192f3d203970f](https://github.com/Quorafind/Obsidian-Memos/assets/87026440/c01df8ce-d02f-4ee3-8ea7-539729d4744b)

_No response_

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by juestchaos** [comment]
![image](https://github.com/Quorafind/Obsidian-Memos/assets/241007/091987a8-1037-435c-a64d-df66a8445ffb)

**Comment by Quorafind** [comment]
已支持。
