### ISSUE TITLE
[Bug][Thino]: 使用templater时无法正确创建当天日记

### ISSUE THREAD

**Issue by Morganwan90** [Quorafind/Obsidian-Thino#392]
### Feature Requested

目前我在使用日记模式，当天如果没有笔记，将从thino中创建新笔记。但是因为我本身templater有带JS的模版，导致会出现错误。
模版文件：
![image](https://github.com/Quorafind/Obsidian-Memos/assets/61633409/433923b7-b171-457d-bc07-98c3b77b596e)

结果如下：
![image](https://github.com/Quorafind/Obsidian-Memos/assets/61633409/f9eb2986-2af7-4010-9500-f3a40694a09a)

可以看到，第一个templaters语法没有正确运行，第二个插入的位置并不在最下方（这个只有在开头有JS语法时出现，如果直接在正文中是templaters语法，位置正确在最下面，且经常会出现代码没有正确运行的情况）
感觉是不是`<%* -%>`的问题

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by juestchaos** [comment]
我测试了下，插入位置是正常的，如图

![image](https://github.com/Quorafind/Obsidian-Memos/assets/241007/6bce363c-ce0d-417b-ac41-c77121dd79d4)

**Comment by Morganwan90** [comment]
我认为这里主要的原因是“当天如果没有笔记，从thino中创建新笔记时”。

比如当天没有笔记时，创建的动图如下：
![test1](https://github.com/Quorafind/Obsidian-Memos/assets/61633409/37a64e24-73fb-44f4-90cf-6a05edd86e7d)

可以看到，出现了格式错误。

但如果我先创建了当天的日记，是可以正差插入的，动图如下：
![test2](https://github.com/Quorafind/Obsidian-Memos/assets/61633409/b963dfe4-65c6-4253-95e6-2eeac8b07f3a)

**Comment by Morganwan90** [comment]
在memos下这个情况不存在，使用良好。。。这个问题搞得我没法用thino....

**Comment by wiiwdt** [comment]
这个问题我也存在，只有先创建当日日记，后在 Thino 里面输入的记录才能保存。
否则输入了当日第一条，当日的日记也能创建了，但是第一条无法保存，日记里面的Thino 记录是空的。

**Comment by Quorafind** [comment]
已修复
