### ISSUE TITLE
[Bug]: 去年写的内容日记里还能查到，但是memo里没有加载

### ISSUE THREAD

**Issue by duskgale** [Quorafind/Obsidian-Thino#394]
### Bug Description

[如图，今年确实是第一次用，去年写了老多都没有检索到

### Relevant Screenshot

![微信截图_20240130175402](https://github.com/Quorafind/Obsidian-Memos/assets/7758117/046480d9-c8db-40be-a978-ba66243b39b4)

### Obsidian Version

1.5.3

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by juestchaos** [comment]
memos 应该没有更新了，如果有问题，可以提供下细节。
后续 会使用 thino 进行更新

**Comment by juestchaos** [comment]
我复测了 thino 2.x 版本，没有你同的这个问题，你可以提供更多信息

**Comment by duskgale** [comment]
> 我复测了 thino 2.x 版本，没有你同的这个问题，你可以提供更多信息

thino是什么？那可能是我插件用的老版本，我再试试，谢谢

**Comment by juestchaos** [comment]
memos 按照官方要求会更名，参见：https://github.com/Quorafind/Obsidian-Memos/issues/395
且此工作已经在 2023年开始

**Comment by Quorafind** [comment]
请更新后查看是否还有一样的问题。

**Comment by duskgale** [comment]
> 请更新后查看是否还有一样的问题。

始终不行,使用Thino也只能拉取到今年的

**Comment by Quorafind** [comment]
> > 请更新后查看是否还有一样的问题。
> 
> 始终不行,使用Thino也只能拉取到今年的

查看下是否是设置的问题，此外，你可以测试一下将一个去年的文件改成今年的日期，看看是否就能拉取到

**Comment by duskgale** [comment]
> > > 请更新后查看是否还有一样的问题。
> > 
> > 
> > 始终不行,使用Thino也只能拉取到今年的
> 
> 查看下是否是设置的问题，此外，你可以测试一下将一个去年的文件改成今年的日期，看看是否就能拉取到

改成今年的日期就可以，改回去又不行了

**Comment by juestchaos** [comment]
能联系我，让我看下实际情况吗？
在 pkmer 群里，或者 thino 内购群里都可以联系到我

**Comment by Quorafind** [comment]
如果还有复现办法或者能提供更多的信息，请直接回复，暂作关闭
