### ISSUE TITLE
[Bug][Thino]: 空行不能实现

### ISSUE THREAD

**Issue by SrSh-notme** [Quorafind/Obsidian-Thino#399]
### Bug Description

Thino 回车空行无法实现 如下图所示
![image](https://github.com/Quorafind/Obsidian-Memos/assets/48594308/39130d3e-0fe1-4615-8ada-4337bc849be6)

thino 更新至2.2.3

### Obsidian Version

1.5.3

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Obsidian 渲染问题

**Comment by juestchaos** [comment]
这处理存在对 br 和 /n 处理的问题，如果单纯处理 br 或者 /n 就要进行替换。
但是ob 的换行处理有两种，一种是 callout 还有 latex 这样语法的内部结构，还有一种是用户自己使用 html <br>，还有写在代码块的里面标记语言
这种多来源换行表达的方法， ob 没有向开发者提供明确的识别能力。
真多所有情况识别，显然无法穷尽。
