### ISSUE TITLE
[Bug][Thino]: 归档按钮点击无反应以及标签统计个数有误

### ISSUE THREAD

**Issue by lllcccwww** [Quorafind/Obsidian-Thino#403]
### Bug Description

点击归档按钮无任何反应，标签的统计有误（20个才对），如下图所示：
![image](https://github.com/Quorafind/Obsidian-Memos/assets/40386392/ee322407-66e9-41f3-b154-cece7b2cf1e4)

源文件：
[2024-03-09.md](https://github.com/Quorafind/Obsidian-Memos/files/14544883/2024-03-09.md)

### Obsidian Version

1.5.8

### Which editor are you using?

- [x] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
请尝试一下最新的版本，看看还有没有一样的情况。

**Comment by lllcccwww** [comment]
> 请尝试一下最新的版本，看看还有没有一样的情况。

可以了，谢谢
