### ISSUE TITLE
[FR][Thino]: 请求增加【批量删除】或【批量剪贴】功能。

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#404]
## 功能请求
  希望能够开发【批量剪贴】、【批量删除】的功能。

## 背景信息
   现在信息记录都在thino，但是想对thino中的信息进行整理（将信息整理至其他的笔记），但目前thino只有批量复制的功能。这势必会造成复制进其他笔记，还有在thino的存储文件留档，造成双份记录的情况。

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
已支持，筛选后在筛选器的最右侧可以筛选：

![Clip_2024-03-18_22-21-50](https://github.com/Quorafind/Obsidian-Thino/assets/13215013/14f97406-6673-4b57-b1f3-702b0136f261)
