### ISSUE TITLE
Feature Request: Thino 右键菜单增加【复制】选项

### ISSUE THREAD

**Issue by SrSh-notme** [Quorafind/Obsidian-Thino#405]
### Feature Requested

希望右键菜单增加 ‘复制’ 选项

![image](https://github.com/Quorafind/Obsidian-Memos/assets/48594308/c101c628-5ef8-4b7d-a4aa-0b3c304a2dc9)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by juestchaos** [comment]
搜索后其实有个批量复制选项，不知道短期是否能解决你问题？

**Comment by SrSh-notme** [comment]
> 搜索后其实有个批量复制选项，不知道短期是否能解决你问题？

大部分时候整理memo需要一条一条来 操作过程稍显繁琐

**Comment by Quorafind** [comment]
已经支持
