### ISSUE TITLE
【功能请求】 请求对每日回顾功能增加检索条件。

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#406]
## 功能描述
感谢bonbon开发如此好用的插件！~

希望对每日回顾功能中增加一个检索条件。目前每日回顾功能非常好用，可以一键导出当日的信息，非常适合整理每日工作。 

但如果提供多一个检索条件，就可以筛选出特定的信息来一键导出。这样可读性更好，可以屏蔽一些杂乱的信息。

 **目前的效果**
![Clip_2024-03-11_23-11-20](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/b0832e1d-91b7-49b5-914b-e08c768934eb)

**期望的效果**
![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/6b83f45f-afe1-4115-8038-26a926100a4c)

**Comment by keji1115** [comment]
请求+1

**Comment by Quorafind** [comment]
已增加基础的搜索框支持。更新 2.3.10-2 即可
