### ISSUE TITLE
[Bug][Thino]: 2.3.4的一些视觉及交互问题

### ISSUE THREAD

**Issue by DanShui-Yu** [Quorafind/Obsidian-Thino#408]
1. 面板两边边距明显不等宽，左边窄了很多，瀑布流视图尤其窄，在卡片式布局的主题下尤为明显
2. 左右栏全开的情况下，宽度小于三分之二屏就没有切换视图按钮了
3. 在半屏下打开浮动窗口，再点击最大化，有一定概率弹不出左侧面板切换全屏视图
4. 刚启动时左上角Thino仍会显示为Memos

**Comment by DanShui-Yu** [comment]
此外，月视图下的条目背景色及字体颜色希望能够自定义，或者至少不要用加粗字体。。。有的主题加粗是自带颜色的，效果十分辣眼睛
![image](https://github.com/Quorafind/Obsidian-Thino/assets/69069739/b3094b47-bd2c-4fca-98ae-94111305a74a)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/69069739/ef4a8738-fc1a-4f86-8f3a-42e1be78a3b9)

**Comment by juestchaos** [comment]
使用 最新 2.3.1-4 试一试

**Comment by DanShui-Yu** [comment]
已升级到2.2.4，这些问题仍然存在

> 1. 面板两边边距明显不等宽，左边窄了很多，瀑布流视图尤其窄，在卡片式布局的主题下尤为明显

![image](https://github.com/Quorafind/Obsidian-Thino/assets/69069739/4073421c-6f46-4b3f-908c-749b63d17b3b)

这是Border主题下瀑布流视图的左边距

作为对比的右边距

![image](https://github.com/Quorafind/Obsidian-Thino/assets/69069739/7fbe514b-d95e-4ab4-934d-6b53ebb683ef)

分屏状态下除列表以外的视图也有这个问题

![image](https://github.com/Quorafind/Obsidian-Thino/assets/69069739/f0146f5a-b0a7-4214-93ad-1a5f11c02981)


> 2. 左右栏全开的情况下，宽度小于三分之二屏就没有切换视图按钮了

![image](https://github.com/Quorafind/Obsidian-Thino/assets/69069739/863aa31d-5e22-4a20-a20c-fdc571d950ce)

好像不是三分之二而是四分之三，不太理解这样设计的意图

> 3. 在半屏下打开浮动窗口，再点击最大化，有一定概率弹不出左侧面板切换全屏视图

我这里触发概率相当高，连续切换窗口大小的话复现率能达到一半以上，有时甚至一直出不来

> 4. 刚启动时左上角Thino仍会显示为Memos

这是个小问题影响不大

另外还发现一些比较影响使用体验的小毛病：

5. 浮动窗口下周视图表格容易错位，有时过个几秒~几十秒能对齐，一切换又会重新错位，有时几分钟过去了也对不齐

![image](https://github.com/Quorafind/Obsidian-Thino/assets/69069739/23508f73-6167-4374-aaa8-17d85f2c007a)

6.切换视图后，无论是分屏还是到新窗口，有时会自动转回列表视图（但有时又能正常保持原界面）

**Comment by fumaye1** [comment]
> 此外，月视图下的条目背景色及字体颜色希望能够自定义，或者至少不要用加粗字体。。。有的主题加粗是自带颜色的，效果十分辣眼睛 ![image](https://private-user-images.githubusercontent.com/69069739/311777359-b3094b47-bd2c-4fca-98ae-94111305a74a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODQzNzcsIm5iZiI6MTcxMDM4NDA3NywicGF0aCI6Ii82OTA2OTczOS8zMTE3NzczNTktYjMwOTRiNDctYmQyYy00ZmNhLTk4YWUtOTQxMTEzMDVhNzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyNDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNjBhMDUwOTI2YzM5OGU1Yjg5NTM0YjUyMmJhZDlmNzlmYzA1MTBjMGQzMzdhYmFkZWIxMTUyNjdkODhkNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jQhtYCUE3gy2kZZHt3SA2qjLjpemCIxhrCFdy_AMkds) ![image](https://private-user-images.githubusercontent.com/69069739/311777493-ef4a8738-fc1a-4f86-8f3a-42e1be78a3b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODQzNzcsIm5iZiI6MTcxMDM4NDA3NywicGF0aCI6Ii82OTA2OTczOS8zMTE3Nzc0OTMtZWY0YTg3MzgtZmMxYS00Zjg2LThmM2EtNDJlMWJlNzhhM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyNDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YmFmNjYyZjczZTU1NjRiYzMyYjc4MGRiOGY3Y2I4YmQyNDUzYTY1MTZkMjkwY2UxOGFkMzc4ZWVhYzhkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T8WPrxBdMYCbkQUNwOkrcbinsIuxGaFJmDfa2j7NreA)

这是个问题，字太大，还加粗了。

**Comment by DanShui-Yu** [comment]
![image](https://github.com/Quorafind/Obsidian-Thino/assets/69069739/f12ead16-b412-435a-b835-6b9afcdea6fe)

输入内容仅有一行的情况下，选中文本弹出的工具栏会被遮挡

**Comment by Quorafind** [comment]
均已修复。其中提供了不管宽度多大都能切换视图的选项。
