### ISSUE TITLE
[Bug][Thino] 随机回顾模式下，鼠标右键点击编辑无法使用

### ISSUE THREAD

**Issue by keji1115** [Quorafind/Obsidian-Thino#409]
![微信图片_20240312114430](https://github.com/Quorafind/Obsidian-Thino/assets/97817881/84e26ecd-255f-4454-b733-b160374b7ce2)

两个红框的位置都不能编辑

**Comment by Quorafind** [comment]
更新 2.3.2 以后看一下是否还有一样的情况

**Comment by Quorafind** [comment]
如果还有问题请重新打开 Issue。
