### ISSUE TITLE
Feature Request: 快速筛选栏能够不区分大小写搜索

### ISSUE THREAD

**Issue by Laels** [Quorafind/Obsidian-Thino#411]
### Feature Requested | 请求的功能

快速筛选栏添加不区分大小写按钮

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/105426329/fe1c7a98-afb3-4a59-924f-ccccd9f67287)
类似于这种

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
目前已经修改为不区分大小写，按钮功能后续会加上（如有必要）
