### ISSUE TITLE
Feature Request: 表格视图下：①建议新增jouranl图标，以区分3种类型； ②修改切换Thino类型时的逻辑

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#414]
### Feature Requested | 请求的功能

热烈庆祝2.3版本上线，关于表格视图提2个小小的意见，请bon看看是否合适：

意见1：增加Thino类型的jouranl图标区分
在表格视图下，目前Thino的类型图标只有 【task-todo】、【todo-done】、不知道【jouranl】这个图标是否能做个区分？

![Clip_2024-03-13_19-32-39](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/f7ab65e9-950b-4963-92e8-83148240a765)

意见2：修改Thino类型的选择切换逻辑
在标题视图下，当选定一种Thino类型后，比如选定task-todo，想要切换成task-done类型时，无法直接在下拉框选取，而是要通过手动删除task-todo后再选取。逻辑上稍微麻烦了一些。

![recording](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/e71a0d5b-e7dc-42da-b385-2eb5da400b49)

### Relevant Screenshot | 相关截图

意见1：增加Thino类型的jouranl图标区分

![Clip_2024-03-13_19-32-39](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/f7ab65e9-950b-4963-92e8-83148240a765)

意见2：修改Thino类型的选择切换逻辑

![recording](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/e71a0d5b-e7dc-42da-b385-2eb5da400b49)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
收到

**Comment by Quorafind** [comment]
2.3.9-0 已支持。
