### ISSUE TITLE
[Bug]: 分享功能依然无法实现自定义分享背景

### ISSUE THREAD

**Issue by heliang12369** [Quorafind/Obsidian-Thino#416]
### Bug Description | BUG 描述

在设置里自定义分享背景后，重启Ob，在Thino中进行分享时，会看到自定义的背景图，但是那个背景图是一闪而过的，最终还是灰色的背景
<img width="416" alt="iShot_2024-03-14_11 30 57" src="https://github.com/Quorafind/Obsidian-Thino/assets/23696213/7241696d-7f77-4ded-b9d4-72d393ba0ccf">

### Obsidian Version | Obsidian 版本

2.3.4

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复
