### ISSUE TITLE
Feature Request: 批量对多条thino增删标签

### ISSUE THREAD

**Issue by MTL321** [Quorafind/Obsidian-Thino#418]
### Feature Requested | 请求的功能

批量对多条thino增删标签。
标签体系调整的情况下，需要对很多条记录的标签做调整。

### Relevant Screenshot | 相关截图

暂无截图

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by MTL321** [comment]
你好，我是潘然，邮件已收到，谢谢。

**Comment by Quorafind** [comment]
已支持。

**Comment by MTL321** [comment]
大佬威武。接下来能支持memos去重吗？
&nbsp;


潘然
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月21日(星期四) 下午3:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Quorafind/Obsidian-Thino] Feature Request: 批量对多条thino增删标签 (Issue #418)





 
已支持。

**Comment by MTL321** [comment]
好的👌



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月21日(周四) 下午3:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Quorafind/Obsidian-Thino] Feature Request: 批量对多条thino增删标签 (Issue #418)




 
Closed #418 as completed.
