### ISSUE TITLE
Feature Request: 桌面端增加锁定功能

### ISSUE THREAD

**Issue by MTL321** [Quorafind/Obsidian-Thino#419]
### Feature Requested | 请求的功能

桌面端增加锁定功能，防止信息外泄

### Relevant Screenshot | 相关截图

暂无

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by yankai19900930** [comment]
朋友，你好！

我跟你一样，想把公司电脑进行锁定，防止信息外漏。我后面找到了一个更好的办法实现。希望对你有帮助！

不知道你是否有quicker，quicker有个动作可以一键隐藏obsidian，可以更好的解决你这个问题，他相当于跳过了密码输入，只有自己能看到这个库。

## 实现的演示

1. 【隐藏】可以设定快捷键（我的演示中是用鼠标手势），一键隐藏obsidian，并且这个obsidian是在任务栏都找不到，即使打开obsidian这个库也会无反应。
2、【恢复】只有按了自己设定的快捷键才能恢复。

这个方法的优点：①当我离开办公位就可以一键隐藏，即使别人找到我的库也打不开。 ②看到有人走近我，我一键隐藏，不需要去关闭、也不怕对方去点开这个库。

![recording](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/a54de8af-1eae-413f-acb7-d8fbe02fc3ef)

**Comment by MTL321** [comment]
之前用过几天quicker，没深入使用，找时间再研究一下。谢谢哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月17日(周日) 中午12:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Quorafind/Obsidian-Thino] Feature Request: 桌面端增加锁定功能 (Issue #419)




 
朋友，你好！
 
我跟你一样，想把公司电脑进行锁定，防止信息外漏。我后面找到了一个更好的办法实现。希望对你有帮助！
 
不知道你是否有quicker，quicker有个动作可以一键隐藏obsidian，可以更好的解决你这个问题，他相当于跳过了密码输入，只有自己能看到这个库。
 
实现的演示
  
【隐藏】可以设定快捷键（我的演示中是用鼠标手势），一键隐藏obsidian，并且这个obsidian是在任务栏都找不到，即使打开obsidian这个库也会无反应。
 2、【恢复】只有按了自己设定的快捷键才能恢复。
  
这个方法的优点：①当我离开办公位就可以一键隐藏，即使别人找到我的库也打不开。 ②看到有人走近我，我一键隐藏，不需要去关闭、也不怕对方去点开这个库。
 
recording.gif (view on web)

**Comment by yankai19900930** [comment]
真的，一定一定要使用quicker，太有用了。 

我先发这个quicker动作的地址给你。花10分钟研究一下，即解决你的问题，真的比加密好用太多，因为这个是纯隐藏（一键），没有任何人能知道，即使找到你的库也打不开。

我上个月花了一个礼拜测试各种软件锁定密码软件，后面发现这个是最好用的。  请你务必要花10分钟时间去学习一下。 如有问题，可以给我留言，我都可以帮你解决。

动作地址：https://getquicker.net/Sharedaction?code=b222c2da-645a-472b-84fa-08d6f2099a1f

**Comment by Quorafind** [comment]
已经支持，2.3.10-8
