### ISSUE TITLE
[Bug]: Word count seems wrong

### ISSUE THREAD

**Issue by Kageetai** [Quorafind/Obsidian-Thino#421]
### Bug Description | BUG 描述

The word count being shown in the menu on a single note looks wrong and seemingly shows random numbers. Other entries also show way higher numbers than the words present.

### Relevant Screenshot | 相关截图

![Screenshot 2024-03-14 at 14 12 33](https://github.com/Quorafind/Obsidian-Thino/assets/1738309/f2498e43-5be2-4fc4-8578-4341ee8e1006)

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
Fixed in latest version.
