### ISSUE TITLE
[Bug]: 2.3.4 PC端归档模式不能使用

### ISSUE THREAD

**Issue by keji1115** [Quorafind/Obsidian-Thino#422]
### Bug Description | BUG 描述

归档了，重启之后又返回原来保存的位置了，归档无效

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/97817881/f7f2ad73-beae-4fe1-9a76-927fbbdbe29c)

### Obsidian Version | Obsidian 版本

1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
我测试了下对应情况，并未复现是否能提供更多信息
或者在个人中 thino 加群的位置，可以联系到我

我这里没去复现步骤
操作一个thino 卡片归档，归档后重启ob，再次查看归档，目前看是正常的

**Comment by juestchaos** [comment]
请使用 2.3.10-5之后的版本测试
