### ISSUE TITLE
[Bug]: 我用syncthing同步发现会员不能用

### ISSUE THREAD

**Issue by keji1115** [Quorafind/Obsidian-Thino#423]
### Bug Description | BUG 描述

我现在主电脑、手机、辅电脑三台设备，常用的是主+手机
但是每次主电脑设置好会员的时候，手机会员自动掉线，但是也显示权限已经使用了
所有的都是最新版本 2.3.4+1.5.8

### Obsidian Version | Obsidian 版本

1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
请尝试 2.3.8 版本

**Comment by Quorafind** [comment]
如果还有问题则重新开启 issue
