### ISSUE TITLE
[Bug]: 全局唤醒模式中，当在编辑框中全选 CTRL+A，会无法选中

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#424]
### Bug Description | BUG 描述

Obsidian版本：1.5.11

Thino版本：2.3.4-8

全局唤醒模式中，当在编辑框中全选 CTRL+A，会无法选中，如动图所示。

### Relevant Screenshot | 相关截图

![recording](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/1ec60cb6-2d78-429d-be34-c7ad0abf17ad)

### Obsidian Version | Obsidian 版本

当前版本：1.5.11；  安装版本：1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
更新后再测试一下
