### ISSUE TITLE
[FR] 增加@日历弹框提醒功能 

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#425]
### Feature Requested | 请求的功能

感谢新版上线，有thino又有了质的提升。

## 功能描述
每日工作中有很多临时要记录的事情都记录在thino，但通常这其中伴随很多待办需要强提醒——弹框。

想法：
1、不知道thino是否可以增加@日历的弹框功能？
2、或者编辑器能否支持“reminder插件”，实现全局弹框。——经测试，目前thino中按照reminder插件写入的内容，无法弹框。

## reminder插件功能介绍

该插件的功能： 只要在todo中加入（@），即可弹框日期选择，并且会在约定日期有强弹框提醒。
 
![recording](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/135b081e-35e1-40b0-bee9-5eaac55fa16f)

### Relevant Screenshot | 相关截图

![recording](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/135b081e-35e1-40b0-bee9-5eaac55fa16f)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by juestchaos** [comment]
尝试下 2.3.10-10

**Comment by yankai19900930** [comment]
juestchaos：
   大佬，thino中的@是可以弹出日历选择时间的。  我的issue请求的功能是希望这个时间可以有更强的功能，实现到时间后会在ob中弹出提醒框。

**Comment by Quorafind** [comment]
经过测试可以和 reminder 配合使用。
