### ISSUE TITLE
Feature Request: 日历组件增加点击日期跳转到具体日期的功能

### ISSUE THREAD

**Issue by rdself** [Quorafind/Obsidian-Thino#426]
### Feature Requested | 请求的功能

目前日历组件不能像热点图一样点击一下就跳转，对于查找以往的日记不是很方便，希望能增加点击日期跳转到具体日期的功能，感谢！

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
应该是已经支持的，您这边可以描述一下具体是点击哪里吗？

**Comment by Quorafind** [comment]
您更新一下可能已经修复。这个情况一般是因为某些数据被错误显示了。

**Comment by Quorafind** [comment]
请确认是否情况仍然存在

**Comment by Quorafind** [comment]
日历组件下，只会显示未归档、删除的部分内容，你确定一下这个内容是否存在理解区别
