### ISSUE TITLE
Feature Request: 列表视图支持按月聚合

### ISSUE THREAD

**Issue by RogerProSelf** [Quorafind/Obsidian-Thino#427]
### Feature Requested | 请求的功能

目前列表视图的聚合功能只能按每日，希望能加入按月聚合的功能，对于每天只记录1-2条的日记的用户来说更有实用价值，谢谢！

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已支持。
