### ISSUE TITLE
Feature Request: 每条日历的时间轴显示加上星期几

### ISSUE THREAD

**Issue by RogerProSelf** [Quorafind/Obsidian-Thino#428]
### Feature Requested | 请求的功能

希望能够在显示时间轴日期的旁边也显示星期几，毕竟星期对于日记来说还是很重要的一个属性，更加方便识别，谢谢！

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已支持
