### ISSUE TITLE
Feature Request: 归档页面中增加关键词等筛选功能

### ISSUE THREAD

**Issue by newfyu** [Quorafind/Obsidian-Thino#429]
### Feature Requested | 请求的功能

归档页面中增加关键词等筛选功能，方便从归档中查找内容

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
2.3.10-2 已支持
