### ISSUE TITLE
Feature Request:  日历模式的日程视图排序能否从前到后的

### ISSUE THREAD

**Issue by PandaNocturne** [Quorafind/Obsidian-Thino#430]
### Feature Requested | 请求的功能

日历模式的日程视图排序是由从后到前的，即 2024-02-26➡2024-03-27 最上面的显示是 2024-02-26 号开始，能不能改为 2024-03-27➡2024-02-26 循序排序体验应该要好点

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by yankai19900930** [comment]
+1

**Comment by Quorafind** [comment]
已支持。点击agenda中的
![Clip_2024-03-19_11-55-54](https://github.com/Quorafind/Obsidian-Thino/assets/13215013/06ba1a9f-b28c-4c35-bbf5-6ad1e8b92013)
会更换顺序
