### ISSUE TITLE
[Bug][Thino]: 编辑框下方的【列表与任务】的切换图标不符逻辑 

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#431]
### Bug Description | BUG 描述

编辑框下方的【列表与任务】的切换图标不符逻辑。

正常情况下，应该是所见即所得，例如：
①附件:显示的是附件，代表点击就是上传附件；
②标签：显示的是标签，代表点击就是输入标签；

唯独【列表与任务】是反过来。

我猜想是想给写入task的人提醒，点击此处即切换task。但是这种逻辑对于thino熟悉的人很别扭，并且与上述所说的整体逻辑不符。

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/79e6856e-60f9-46fb-8612-6ed367ec2c94)

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修改。
