### ISSUE TITLE
[Bug][Thino]:  日历与日历说明的显示逻辑不符

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#432]
### Bug Description | BUG 描述

详见图片：
日历中：在前的是任务（浅色：更少）
说明中：在前的是列表（17个：更多）

是否将两者逻辑变更一致：日历中是列表在前，说明也是列表在前。

这样一眼看就知道：任务多，还是列表多。当前感觉是反过来的。

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/66400902-4eb4-4675-9fa1-c9cbea29b3ab)

### Obsidian Version | Obsidian 版本

当前版本：1.5.11；  安装版本：1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修改
