### ISSUE TITLE
Feature Request: 增加自定义字体功能

### ISSUE THREAD

**Issue by RogerProSelf** [Quorafind/Obsidian-Thino#433]
### Feature Requested | 请求的功能

Obsidian作为一个综合性比较强的app，在配置主题的时候字体选择往往是优先考虑中英文的可读性，但是Thino作为日记插件，还是希望能选择其他更加美观的字体样式。市面上的日记app都有自选字体的功能，但是obsidian内各个日记类插件还没有类似功能，加入自定义字体的功能是能增加对用户吸引力的。谢谢！

![Screenshot 2024-03-19 at 01 18 57](https://github.com/Quorafind/Obsidian-Thino/assets/55005611/a61f6a80-8bb4-49b5-a8ea-059c872e01e7)
![Screenshot 2024-03-19 at 01 18 26](https://github.com/Quorafind/Obsidian-Thino/assets/55005611/055dd248-fee7-473d-8f2f-a8f73139a59e)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
由于 Thino 本身并不包含字体数据，而且如果将字体数据打包进来也会存在用户意外将不能商用的字体用来商用的情况，会导致 Thino 也会被影响；所以现阶段你可以通过简单的 css 配置就能实现自定义字体：

```
.memo-background .markdown-rendered {
    font-family: 'Caveat',cursive !important; /* 这里设置你所有的字体名称 */
    font-size: 17px !important; /* 这里设置字体大小 */
    font-weight: 500; /* 这里设置你字重 */
}
```
