### ISSUE TITLE
[Bug]: 新版本word拖不进去Thino

### ISSUE THREAD

**Issue by mooz-droid** [Quorafind/Obsidian-Thino#434]
### Bug Description | BUG 描述

我刚在Github下载了最新的Thino2.3.10-19，这个无法通过OB官方市场更新，出现word拖不进去的问题，昨天的2.3.9版本没有出现这个问题

### Relevant Screenshot | 相关截图

![新版Thino2 3 10-19拖不了文件](https://github.com/Quorafind/Obsidian-Thino/assets/126145155/f7f7575f-98c1-4993-a947-7fe305a1e1b5)
![Thino2 3 9可以拖文件](https://github.com/Quorafind/Obsidian-Thino/assets/126145155/ad868dc8-2b11-4816-b9e8-c06b374a2eb0)

### Obsidian Version | Obsidian 版本

v1.5.3

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
你可以试下 2.3.10-20

**Comment by mooz-droid** [comment]
已解决
