### ISSUE TITLE
[Bug]: thino手机端记录内容后，会出现重复内容

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#435]
### Bug Description | BUG 描述

# 问题描述
一直存在的同步bug，在手机端thino记录信息后，经常性会出现重复内容，两条信息的时间戳完全一致（详见截图），在删除其中一个信息后，另一个也一同被删除。

# 信息补充
同步机制：官方同步，且开启thino的同步。

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/f3a3ef8e-281e-4187-8d05-464f56034ea9)

### Obsidian Version | Obsidian 版本

当前版本：1.5.11；  安装版本：1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
你开了其他同步吧？

**Comment by yankai19900930** [comment]
使用的是ob官方同步，另外就是thino的同步也打开。

不知道要如何设置才好呢？

**Comment by juestchaos** [comment]
似乎在很多群里都回过你了，希望您能认真看下，并对应操作下
