### ISSUE TITLE
Feature Request: 请求对于高频使用“多文件”记录模块的用户，增加可以解析properties里面标签的功能。

### ISSUE THREAD

**Issue by kine56** [Quorafind/Obsidian-Thino#438]
### Feature Requested | 请求的功能

对于使用“多文件”模式的用户，将标签放在properties内部，比如官方默认的“tags”，是最合理的，实现文本内容和metadata数据的分离。希望Thino能够支持这一点，谢谢开发者。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by kine56** [comment]
希望能够完整支持”多文件”的prosperity内的标签属性，包括读取、写入、查询等。

**Comment by kine56** [comment]
希望能够完整支持”多文件”的prosperity内的标签属性，包括读取、写入、查询等。

**Comment by Quorafind** [comment]
已支持显示以及基于标签筛选。但是短期内应该也不会支持编辑。
