### ISSUE TITLE
[Bug]: 更新thino-2.3.10-24版本后，编辑框会出现无法输入的情况

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#439]
### Bug Description | BUG 描述

更新thino-2.3.10-24版本后，编辑框会出现无法输入的情况

### Relevant Screenshot | 相关截图

![20240320093604](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/a222f725-0ab2-470f-8fdd-ac978111570a)

![b00d6534e18a36517346917007e2904](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/bb43c73c-6e7b-48f2-ba80-b8c2ae31ccf0)

### Obsidian Version | Obsidian 版本

当前版本：1.5.11；  安装版本：1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复
