### ISSUE TITLE
Feature Request: 建议针对【点击日程的日期/时间表头时，可调整排序顺序；】功能，增加排序图片

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#440]
### Feature Requested | 请求的功能

建议针对【点击日程的日期/时间表头时，可调整排序顺序；】功能，增加排序图片。

当前在日程的表头点击以后，由于数据较多，要等一会才切换，可能容易忽略是否已切换排序。 建议像表格模式一样增加一个排序图标，就非常好辨识。

### Relevant Screenshot | 相关截图

![d72257ea53964d5ed5d113ce5953557](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/e0e0b6f3-5bbf-4e3a-a048-6eb721ed8027)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by KANGYUWANG** [comment]
这个也挺实用的

**Comment by Quorafind** [comment]
已增加。
