### ISSUE TITLE
Feature Request: 希望增加拖入Thino的文件默认没有预览

### ISSUE THREAD

**Issue by mooz-droid** [Quorafind/Obsidian-Thino#444]
### Feature Requested | 请求的功能

目前我把桌面上的图片,PDF文件拖入Thino，默认会有预览，显示![[xxx.pdf]]，我目前的解决方法是手动删除!，但是有些麻烦，希望在设置里增加一个选项，可以改为拖进去就没有预览。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
由于现在依赖的是 ob 的编辑器，所以所有行为跟随 obsidian 的情况，你可以观察该功能的请求进展： https://forum.obsidian.md/t/drag-and-drop-pdf-to-create-wikilink-not-embed/49212/23

但是目前来看，Thino 如果修改这个默认行为，有可能会导致全局变化，所以不会主动去修改这个默认行为
