### ISSUE TITLE
Feature Request: 如何在thino和md笔记中显示出比较好的层级关系

### ISSUE THREAD

**Issue by linfengtongxue70** [Quorafind/Obsidian-Thino#445]
### Feature Requested | 请求的功能

开发者早上好^_^
如题，我发现目前无法在thino和md笔记同时获得比较好的层级关系。我分别尝试了列表和单纯用tab键来表示缩进，前者可以在thino显示而无法在md笔记中被渲染，可能的原因是采用```<br>```换行而不是enter；后者在md笔记中呈现出层级关系，但在thino内无法区分。
是否有其他方法来表示层级关系呢？我还蛮需要的hhh

### Relevant Screenshot | 相关截图

![19edfcb3a63c70acb4cb20cbdfd2f20](https://github.com/Quorafind/Obsidian-Thino/assets/91956234/79a4c532-7453-431a-aa31-afe08b369e5d)
![2da59f74e4bfc60426ba87b60d05ec1](https://github.com/Quorafind/Obsidian-Thino/assets/91956234/06439d70-622b-4c93-a150-2fc7ec3ed176)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已修复。
