### ISSUE TITLE
[Bug]: Thino “Chat” 模式下，创建 thino 后页面回到最上方

### ISSUE THREAD

**Issue by alexinea** [Quorafind/Obsidian-Thino#446]
### Bug Description | BUG 描述

如题。正常模式下，页面内容是按创建时间到排序的，也就是「越早发送的信息，在越下方」；而 Chat 模式是按时间正排序，即「越早发送的信息，在越上方」。在 Chat 模式下，提交一条 thino 后，页面会回到最上方；刚才提交的 thino，则在最下方，需要重新滚屏回到下面才能看到。

desktop

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by alexinea** [comment]
嗷，看到群里已经有人提这个问题了。

**Comment by Quorafind** [comment]
更新 2.17-2 看一下是否解决了

**Comment by alexinea** [comment]
已解决：）
