### ISSUE TITLE
Feature Request: thino是否可以增加一个批量导出所有thino内含有某个标签的内容集合在一个图片上

### ISSUE THREAD

**Issue by Suny256888-sy** [Quorafind/Obsidian-Thino#447]
### Feature Requested | 请求的功能

thino是否可以增加一个批量导出所有thino内含有某个标签的内容集合在一个图片上，比如我想导出thino中含有11个含有#科研/仿生标签的图片，但是目前我发现无法同时导出含有11个含有这个标签的内容到一个图片中

### Relevant Screenshot | 相关截图

<img width="963" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/73524145/d603d494-2b2f-47ce-b566-b4da1ee4c43f">

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
目前日程视图支持该功能，可以筛选后再导出，右键点击日程视图的标题

**Comment by Quorafind** [comment]
已经支持
