### ISSUE TITLE
Feature Request: 能否选择打开原始页面（Source）的行为？

### ISSUE THREAD

**Issue by Moyf** [Quorafind/Obsidian-Thino#448]
### Feature Requested | 请求的功能

如图，将 Thino 放置在中间区域的页面的话，打开 Souce 的时候再次切割，两边会挤得非常小。
有办法修改这个行为，改成【直接打开】（或者说在中央最大的视图打开），而不是是【Right Split】吗？

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/4013062/c1507fa4-b04f-47ef-a114-abd944b81fdf)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Moyf** [comment]
> 在设置中，启用 ![Clip_2024-03-22_19-43-30](https://private-user-images.githubusercontent.com/13215013/315996157-2050acb3-ee1d-4737-9cae-afdacce56e4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjAyMDUsIm5iZiI6MTcxMTExOTkwNSwicGF0aCI6Ii8xMzIxNTAxMy8zMTU5OTYxNTctMjA1MGFjYjMtZWUxZC00NzM3LTljYWUtYWZkYWNjZTU2ZTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE1MDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NDhiMzdiYzYzMTAyMDI4NjlmOGI4M2M1MzJhZmQyZWEzNWU5NTVjMTIyY2U4NWRmMzIwZThjNWU3NzRiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GmvOHR8ESt8fploq5miUri_Qsr4ryPbvffkbqSFQ_Lc)

原来如此，感谢！

**Comment by Moyf** [comment]
![image](https://github.com/Quorafind/Obsidian-Thino/assets/4013062/71e5a463-806a-4090-9d4c-1f350b46267b)

打开之后试了一下，还是原先的行为诶 _(:з」∠)_

**Comment by cumany** [comment]
是不是没重启ob

**Comment by Moyf** [comment]
> 是不是没重启ob

重启过的，还是会 Split……


DayPlanner 插件在 V18.0 更新（https://github.com/ivan-lednev/obsidian-day-planner/releases/tag/0.18.0）添加了一个特性：**如果将要打开的页面当前已经存在，直接复用而不开一个新页面**
<img width="913" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/4013062/eac68f96-6a57-4da6-82d1-2d4a13c8625c">

我这边 DailyNote 平时也会常驻，可以考虑加上这个特性吗？可以有效避免多开重复的页面！


---

另外有个不太重要的事儿，这边顺便提一嘴吧，就不单独开 issue 了：
英文版本的 RECYCLE BIN 字符会超出长度，有点破坏整体的美观
<img width="160" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/4013062/982df564-88e2-42f5-af4d-299659eaf74e">

**Comment by Quorafind** [comment]
2.3.45

默认会从leaf打开，而不再是 split；
默认会打开已经打开的笔记，而不是重新打开。
