### ISSUE TITLE
[Bug]: chat视图fluent样式下callout样式颜色改变

### ISSUE THREAD

**Issue by xiaoxiang01a** [Quorafind/Obsidian-Thino#449]
### Bug Description | BUG 描述

chat视图fluent样式下callout样式颜色改变
thino版本：2.3.17

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/73389963/df485eab-ab3c-4f96-952a-a41a0cbc8fa6)

### Obsidian Version | Obsidian 版本

1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
默认行为

**Comment by xiaoxiang01a** [comment]
> 默认行为

好的，bon佬回复真快啊🤩

**Comment by Quorafind** [comment]
已修复
