### ISSUE TITLE
[Bug]: 上传图片无法显示

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#450]
### Bug Description | BUG 描述

在thino中上传图片无法显示。（图片来源：在群里发的那种茶叶图）

![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/34486b9d-ec2f-4573-a79d-86c87858c87d)

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/506bad2e-2a7f-4f0c-bbf8-a16fe2093776)

### Obsidian Version | Obsidian 版本

当前版本：1.5.11；  安装版本：1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
你可以贴一下链接，看看是什么情况

**Comment by yankai19900930** [comment]
请问贴哪个链接？

下面这个？
![[Pasted Image 20240323103115.jpeg]]

**Comment by Quorafind** [comment]
可以检查下图片有没有实际在库里面

**Comment by juestchaos** [comment]
看起来这个库没有实际在库里，导致ob 里面就找不到
你是不是有什么修改 附件名称的插件？

**Comment by yankai19900930** [comment]
没有修改附件的，其他插入的图片都能正常。唯独这张照片奇怪，非常长的截图、并且很小。

可能是图片问题。毕竟其他都正常。

**Comment by juestchaos** [comment]
你能找到这张图片在本地存储的位置吗？

**Comment by yankai19900930** [comment]
该issue先行关闭把。暂时只有这张图会这样，感觉是图的问题。
