### ISSUE TITLE
[Bug]: 手机端thino（2.3.17版本）在聊天视图下，当选择【Fluent】、【Inline】时，其“发送按钮“显示不正常

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#451]
### Bug Description | BUG 描述

手机thino（2.3.17版本）在聊天视图下，当选择【Fluent】、【Inline】时，其“发送按钮“显示不正常，详见下图。

备注：①电脑端均正常；②手机端【Default】正常

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/5c636a24-4d45-49bc-b725-43b323f40778)

### Obsidian Version | Obsidian 版本

当前版本：1.5.11；  安装版本：1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
你至少需要设置一个内容到原先保存按钮的文本上，现在是空白状态了

**Comment by yankai19900930** [comment]
保存按钮的文本是默认的NOTE，仍出现上述情况。

我现将NOTE改成NO，问题未得到解决

**Comment by Quorafind** [comment]
请复测看看是否还是不正常

**Comment by juestchaos** [comment]
我这里未能复现
建议用户，先升级到 ob 移动端 1.5.11 和 插件的 2.3.25 测试下
我在这个环境和用户一个配置未能复现

**Comment by yankai19900930** [comment]
重新更换手机后，正常。
