### ISSUE TITLE
Feature Request: ①可否实现【微信读书】分享标注至thino；②APP分享至thino，可否自动带出 #标签

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#452]
### Feature Requested | 请求的功能

# 功能请求：①可否实现【微信读书】分享标注至thino；
   皮皮大佬分享静读天下实现标注一键转至thino，微信读书作为更大的用户群体，可否实现在微信读书一键标注转至thino功能？

# 功能请求：②APP分享至thino，可否自动带出 #标签
   今日测试，在【语雀】分享至thino，发现分享至thino的内容没有像微信一样带有 #收集/微信。    不知道是否可对来自不同APP均带有 #收集/APP 功能？

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by windily-cloud** [comment]
微信读书实际没有主动推送的能力，需要手动获取，其原理和那个微信读书插件一致。

API如下：https://github.com/malinkang/weread2notion/blob/main/scripts/weread.py

所以这玩意儿和静读天下原理不一致，需要客户端主动获取。

**Comment by Quorafind** [comment]
已支持设定分享进来的标签。但 ob 对待分享进来的内容没有获取对应的来源，所以没办法处理这一层。

**Comment by lzz66** [comment]
”皮皮大佬分享静读天下实现标注一键转至thino“，请问op知道转存的thino的默认格式怎么修改吗？
![PixPin_2024-04-07_23-20-54](https://github.com/Quorafind/Obsidian-Thino/assets/47048565/59cc1d2b-3d86-47ee-9eda-bc4ae1c7b618)
现在会有标签和两个空行，但是我都不想要。
