### ISSUE TITLE
[Bug]: 【随机回顾】的检索数量与实际不符

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#454]
### Bug Description | BUG 描述

【随机回顾】的检索数量与实际不符，详见截图

实际上有检索有59条笔记，但随机回顾中只出现2条笔记。

### Relevant Screenshot | 相关截图

![recording](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/88b740a5-6269-46b0-9241-328140c1d4c2)

### Obsidian Version | Obsidian 版本

当前版本：1.5.11；  安装版本：1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
随机回顾目前还不支持检索。

**Comment by Quorafind** [comment]
已修复
