### ISSUE TITLE
[Bug]: 【2.3.18】【动态视图】点击卡片上的 更多按钮，会直接跳转到 thino 插件设置

### ISSUE THREAD

**Issue by juestchaos** [Quorafind/Obsidian-Thino#455]
### Bug Description | BUG 描述

点击动态视图，thino 卡片上更多按钮都会跳转到 编辑框

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复

**Comment by juestchaos** [comment]
测试通过
