### ISSUE TITLE
[Bug]: 手机端thino右上角检索条件布局不合理

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#456]
### Bug Description | BUG 描述

手机端thino右上角检索条件布局不合理，详见截图

1、or 和 and：图片太靠边，无法点击
2、增加检索条件：按钮太紧凑，无法点击

### Relevant Screenshot | 相关截图

![Uploading 20240324_143728_607_copy.png…]()

### Obsidian Version | Obsidian 版本

当前版本：1.5.11；  安装版本：1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
图片没上传成功

**Comment by Quorafind** [comment]
请查看最新版本 Thino 以及最新版本 Obsidian 是否还有一样的情况

**Comment by juestchaos** [comment]
@yankai19900930 你原问题描述的图片没有上传成功，需要再次上传下，看到具体问题现象

**Comment by yankai19900930** [comment]
更换手机后正常显示。本issue关闭。
