### ISSUE TITLE
[Bug]: chat视图点击右侧标签筛选再关闭时，不会返回到最底部

### ISSUE THREAD

**Issue by xiaoxiang01a** [Quorafind/Obsidian-Thino#458]
### Bug Description | BUG 描述

chat视图点击右侧标签筛选再关闭时，不会返回到最底部
thino：2.3.20

### Relevant Screenshot | 相关截图

![PixPin_2024-03-24_20-30-58](https://github.com/Quorafind/Obsidian-Thino/assets/73389963/fa43758b-08d0-4a53-82a6-e36643323ca4)

### Obsidian Version | Obsidian 版本

1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复

**Comment by xiaoxiang01a** [comment]
> 已修复

@Quorafind ，辛苦bon佬的及时修复，但是我更新2.3.23版本后，发现还是存在该现象，只是取消标签筛选后停留的时间不一样了，另外我还发现有些标签取消后是可以回滚到底部的，有些又不行
