### ISSUE TITLE
[Bug]: 表格视图在浮动窗口非最大化下不能自适应宽度

### ISSUE THREAD

**Issue by DanShui-Yu** [Quorafind/Obsidian-Thino#459]
### Bug Description | BUG 描述

最右边会看不见，也没法横向滚动

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/69069739/c190e863-5c05-4880-a840-27c2af567341)

### Obsidian Version | Obsidian 版本

1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
在表格上应该是可以横向滚动的

**Comment by DanShui-Yu** [comment]
滚不动呢，根本没有滚动条

**Comment by juestchaos** [comment]
可以使用中键，点击后鼠标向左右滑动来完成横向滚动

**Comment by Quorafind** [comment]
请复查一下现在是否还是不能滚动

**Comment by Quorafind** [comment]
无法复现

**Comment by DanShui-Yu** [comment]
能滚了，但还是不能滚到头

![559cfbb4-f14b-46aa-9ed6-b9fbecd22565](https://github.com/Quorafind/Obsidian-Thino/assets/69069739/1a309a59-5a2f-4d13-958c-7d042c184b6a)
