### ISSUE TITLE
[Bug]: 引用功能不能正常跳转

### ISSUE THREAD

**Issue by Feng-Xiaohan** [Quorafind/Obsidian-Thino#462]
### Bug Description | BUG 描述

点击被引用的 Thino 链接进入阅读模式，在阅读模式下点击其他卡片，无法正常跳转至其他卡片（左上角的时间改变了，但内容依旧是最初的内容）

### Relevant Screenshot | 相关截图

https://github.com/Quorafind/Obsidian-Thino/assets/63276191/c78553e8-c75b-4876-a6fd-8c369ae568cb

### To Reproduce | 重现问题

1. 创建一条 Thino 1
2. 新写一条 Thino 2，并引用 Thino 1
3. 在 2 中点击所引用链接，弹出的阅读模式中显示为 1，阅读模式下显示 2 引用了 1
4. 点击下方的 2，可发现阅读模式中显示的依旧是 1

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复
