### ISSUE TITLE
[Bug]: 同一内容重复输入

### ISSUE THREAD

**Issue by Feng-Xiaohan** [Quorafind/Obsidian-Thino#463]
### Bug Description | BUG 描述

当较快输入内容时，会出现同一内容被重复输入的情况。

关于我的同步：
我 Thino 的默认输入方式为**日记**，同步方式为**单文件**同步，同时我用其他同步功能同步**单文件以外**的 obsidian 库。
![image](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/055a4004-ddef-43b0-9448-355e1640d02e)
我想我的个人同步和 Thino 的同步应该是并不冲突的。

下方截图中我的输入是顺着输入了 1-5，但明显出现了重复现象。

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/1780c0dd-c5b1-4a92-bd2a-7d804fde0aaa)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/70844603-18e8-43cc-871e-1a3ceaa9a8d0)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/7495ed5a-aa70-4ccb-9a19-0a0d83ee34d9)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/5339c84f-cc69-40f7-b36a-b96d86dc7525)

### To Reproduce | 重现问题

在用其他功能同步 obsidian 库的同时，快速输入 1-5

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
【同时我用其他同步功能同步单文件以外的 obsidian 库。】
所以日记文件是靠其他其他同步在进行同步对吧？

**Comment by Feng-Xiaohan** [comment]
已解决：“以单文件方式同步”并不是指“只同步单文件”，还是会同步所有文件，从而会造成冲突
解决方式：禁用个人同步软件中所有 日记 的同步
