### ISSUE TITLE
[Bug]: 在更新新版本 Thino 前，用 memo 创建的卡片无法被正常解析

### ISSUE THREAD

**Issue by Feng-Xiaohan** [Quorafind/Obsidian-Thino#464]
### Bug Description | BUG 描述

当设定：日记 - 解析指定标题后的 Thino 后，更新至新版本前创建的 Thino 卡片无法被正常解析，解析出更新后的。
但是，更新前我同样使用了此功能（只解析指定后的 Thino），并且之前此功能也一直是正常的。
我的日记始终是通过同一模板创建的，在更新前后未修改过模板，理应不会出现只能解析更新后内容的问题？

### Relevant Screenshot | 相关截图

不使用”解析指定标题后的 Thino“：
![image](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/25cdd909-f5a4-43f5-8ee3-50654f06db77)
使用”解析zhi'ding指定标题后的 Thino“：
![image](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/3c5b8aff-d4e4-4a91-8c0a-513ef32a3c88)

我的设置：
![image](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/8fe5dccb-0010-4e58-bb75-0b7570caf8d6)
一个无法被解析的页面截图：
![image](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/eaef8b6f-c392-4e48-a4ff-9ce82bee28a8)

### To Reproduce | 重现问题

将设置改为”解析指定标题后的内容“，然后在更新新版前的日记里加入相应标题
当天 Thino 应该就无法被正常解析了

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
需要填入标题，而不是标签，如果以前可以填入标签的话，那是一个历史悠久的 BUG

你这里填入：
```
# 记录
```
即可正常解析

**Comment by Feng-Xiaohan** [comment]
> 需要填入标题，而不是标签，如果以前可以填入标签的话，那是一个历史悠久的 BUG
> 
> 你这里填入：
> 
> ```
> # 记录
> ```
> 
> 即可正常解析

测试了，貌似依旧不可以。
甚至用 `#memo` 还可以看到更新后新输入的内容（这居然是 bug），但换成记录后直接空掉了。
![Screenshot_2024-03-26-01-28-25-329_md obsidian](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/082cb2f7-84eb-4eaa-ac83-b435bdcb6383)
![Screenshot_2024-03-26-01-26-25-214_md obsidian](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/f29a468a-6b85-4237-a8e9-989c4119956f)
![Screenshot_2024-03-26-01-28-32-696_md obsidian](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/cc30301a-f04c-4219-bb1b-deaaeb6cc9bc)

**Comment by Quorafind** [comment]
> > 需要填入标题，而不是标签，如果以前可以填入标签的话，那是一个历史悠久的 BUG
> > 
> > 你这里填入：
> > 
> > ```
> > # 记录
> > ```
> > 
> > 即可正常解析
> 
> 测试了，貌似依旧不可以。
> 甚至用 `#memo` 还可以看到更新后新输入的内容（这居然是 bug），但换成记录后直接空掉了。
> ![Screenshot_2024-03-26-01-28-25-329_md obsidian](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/082cb2f7-84eb-4eaa-ac83-b435bdcb6383)
> ![Screenshot_2024-03-26-01-26-25-214_md obsidian](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/f29a468a-6b85-4237-a8e9-989c4119956f)
> ![Screenshot_2024-03-26-01-28-32-696_md obsidian](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/cc30301a-f04c-4219-bb1b-deaaeb6cc9bc)
> 

你这里的记录是几级标题？

**Comment by Feng-Xiaohan** [comment]
> > > 需要填入标题，而不是标签，如果以前可以填入标签的话，那是一个历史悠久的 BUG
> > > 你这里填入：
> > > ```
> > > # 记录
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 即可正常解析
> > 
> > 
> > 测试了，貌似依旧不可以。
> > 甚至用 `#memo` 还可以看到更新后新输入的内容（这居然是 bug），但换成记录后直接空掉了。
> > ![Screenshot_2024-03-26-01-28-25-329_md obsidian](https://private-user-images.githubusercontent.com/63276191/316595632-082cb2f7-84eb-4eaa-ac83-b435bdcb6383.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTE3MTQsIm5iZiI6MTcxMTQxMTQxNCwicGF0aCI6Ii82MzI3NjE5MS8zMTY1OTU2MzItMDgyY2IyZjctODRlYi00ZWFhLWFjODMtYjQzNWJkY2I2MzgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAwMDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNmFmNzYzNzNkZWFhMzIxNTVjNDEzOTQwMWU1NmFkMmY4ZGMyZjE0Mjg4Y2JkOGNjOWQ2ZTU5NWU0YzgwMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.baJi_A7Hoh0vhbB0B4lYDi4tdHbrOJKzju-gVXc2TfY)
> > ![Screenshot_2024-03-26-01-26-25-214_md obsidian](https://private-user-images.githubusercontent.com/63276191/316595166-f29a468a-6b85-4237-a8e9-989c4119956f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTE3MTQsIm5iZiI6MTcxMTQxMTQxNCwicGF0aCI6Ii82MzI3NjE5MS8zMTY1OTUxNjYtZjI5YTQ2OGEtNmI4NS00MjM3LWE4ZTktOTg5YzQxMTk5NTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAwMDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NjlmYWZiZTRkZTQwM2JhYjFlMjY4NzhjY2MxZDFiYmE3MDkwZWEwMzMyZTE0MzQ5YjJiMzExOWQzNjRjYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8NQmyWyn9Mg2IKvZEDUodwVUpHu62Cna_UDOCOYAcjk)
> > ![Screenshot_2024-03-26-01-28-32-696_md obsidian](https://private-user-images.githubusercontent.com/63276191/316595700-cc30301a-f04c-4219-bb1b-deaaeb6cc9bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTE3MTQsIm5iZiI6MTcxMTQxMTQxNCwicGF0aCI6Ii82MzI3NjE5MS8zMTY1OTU3MDAtY2MzMDMwMWEtZjA0Yy00MjE5LWJiMWItZGVhYWViNmNjOWJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAwMDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NDk5N2ZiOTUyYzQ1N2JkZjFhMzllMWM4ZGNjYTQ0ZDFhN2FiMDEyZDI0MTdlZmNkZGJkNTNjMTgxNWRlYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gnMkiSIhVUs1P33-mvucQLgHBaxzSmpniKO55Bz7ytU)
> 
> 你这里的记录是几级标题？

我多数文档的记录用的是二级标题，所以我专门修改了一个文档中的记录（改成了一级标题）（前文图2），但这条依旧没有被解析。
我也尝试过在输入页面输入 `## 记录`，依旧没有效果。

**Comment by Quorafind** [comment]
你设置为空的情况下会被解析吗

**Comment by Feng-Xiaohan** [comment]
> 你设置为空的情况下会被解析吗

会，我整理一下。
设置为空：更新新版前和更新新版后，均可被正常解析
设置为 `#memo`：更新后新输入的内容可以，更新前内容不可以
设置为 `## 记录`（我的记录为二级标题）：均不可以
设置为 `# 记录`：修改了一个页面为二级标题，不可以解析

**Comment by Quorafind** [comment]
`#` 标题的形式，只支持百分百匹配，不向下兼容

而且为了避免有些情况下的失效，连多一个空格都会匹配，所以要留意这一点

**Comment by Feng-Xiaohan** [comment]
一个视频，为空时**都可以解析**，为 `#memo` 时，**新输入**的内容可被解析（是因为近期又进行过一次更新？），往期内容无法解析。

https://github.com/Quorafind/Obsidian-Thino/assets/63276191/046b5316-9312-4f02-a50e-3bba17ddb731

两个记录的，我们会议开始了来不及录了。

**Comment by Feng-Xiaohan** [comment]
> `#` 标题的形式，只支持百分百匹配，不向下兼容
> 
> 而且为了避免有些情况下的失效，连多一个空格都会匹配，所以要留意这一点

嗯嗯，了解的，刚刚专门去检查了一下，我的标题结尾没带空格

**Comment by Quorafind** [comment]
我研究下

**Comment by Quorafind** [comment]
无法正式复现，请更新版本后，复制一下调试信息

**Comment by juestchaos** [comment]
用户反馈自己也无法复现了

**Comment by Feng-Xiaohan** [comment]
> 无法正式复现，请更新版本后，复制一下调试信息

{
  "settings": {
    "StartDate": "Sunday",
    "InsertAfter": "#memo",
    "UserName": "晓寒",
    "ProcessEntriesBelow": "# 记录",
    "Language": "en",
    "SaveMemoButtonLabel": "保存",
    "SaveMemoButtonIcon": "✒️",
    "ShareFooterStart": "我与我周旋久",
    "ShareFooterEnd": "✒️ by {UserName}",
    "DefaultPrefix": "List",
    "UseDailyOrPeriodic": "Daily",
    "InsertDateFormat": "Dataview",
    "DefaultEditorLocation": "Top",
    "UseButtonToShowEditor": false,
    "FocusOnEditor": true,
    "OpenDailyMemosWithMemos": true,
    "HideDoneTasks": false,
    "ShowTaskLabel": false,
    "MobileAndDesktop": "All",
    "OpenMemosAutomatically": true,
    "ShowTime": true,
    "ShowDate": true,
    "AddBlankLineWhenDate": false,
    "AutoSaveWhenOnMobile": true,
    "DeleteFileName": "delete",
    "QueryFileName": "query",
    "UseVaultTags": true,
    "SetCustomBackgroundImage": false,
    "SetCustomMemoFooter": true,
    "DefaultLightBackgroundImage": "",
    "DefaultDarkBackgroundImage": "",
    "DefaultMemoComposition": "{TIME} {CONTENT}",
    "CommentOnMemos": true,
    "CommentsInOriginalNotes": true,
    "FetchMemosMark": "#memo",
    "FetchMemosFromNote": false,
    "ShowCommentOnMemos": true,
    "ShowLeftSideBar": true,
    "MemoListView": "list",
    "MemoSaveLocation": "DAILY",
    "MemoOtherSaveLocation": {
      "MemoDefaultCanvasPath": "附件/Thino画布.thino.canvas",
      "MemoDefaultMultiFilePath": "日记日程/Thino/多文件",
      "MemoDefaultSingleFilePath": "日记日程/Thino/单文件.thino.md"
    },
    "MemoDailyTarget": 5,
    "HeatmapColorScheme": "gray",
    "EnabledHttpApi": false,
    "HttpApiIpType": "localhost",
    "HttpApiPort": "43999",
    "AutoDownloadImage": false,
    "EditorType": "obsidian",
    "EnabledLocationList": [
      {
        "value": "DAILY",
        "target": "ProcessEntriesBelow",
        "insert": "InsertAfter"
      },
      {
        "value": "MULTI",
        "target": "MemoDefaultMultiFilePath"
      }
    ],
    "DeleteThinoDirectly": true,
    "CaptureKey": {
      "EnableCaptureKey": true,
      "OpenThinoGlobally": "Control+Shift+T",
      "ShowNearMouse": true
    },
    "startSync": false,
    "tokenForVerify": "***",
    "saveThinoType": "DAILY",
    "showDayMark": true,
    "dayMarkRange": "day",
    "navigation": true,
    "password": "",
    "needVerify": false,
    "addTagAutomatically": true,
    "addTagPosition": "Beginning",
    "addTagWithNewline": true,
    "chatViewStyle": "fluent",
    "MomentsBackgroundImage": "http://www.cj7112.xyz:2380/data/我与我周旋久.png",
    "MomentsIcon": "http://www.cj7112.xyz:2380/data/头像.png",
    "MomentsQuote": "我与我周旋久",
    "DefaultThemeForThino": "classic",
    "LastUpdatedVersion": "2.3.26"
  },
  "manifest": {
    "id": "obsidian-memos",
    "name": "Thino",
    "description": "Capturing ideas and save them into daily notes.",
    "version": "2.3.26",
    "author": "Boninall",
    "authorUrl": "https://github.com/Quorafind/",
    "isDesktopOnly": false,
    "minAppVersion": "1.0.0",
    "dir": ".obsidian/plugins/obsidian-memos"
  },
  "platform": "app://4a7e0ceef6e714bb12c9cc6b56b820d643ae/"
}
![9ef9337d0f2672719d8db271d7089160](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/8ec200de-b6a0-4245-b3b9-6dd2c8e1735b)
![3a5e7993258e1ca7bdc340b6c533682f](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/907b0721-9fc3-4f25-94e5-1bea98c16f60)

**Comment by Quorafind** [comment]
可以提供以下你的日记插件的设置吗？

**Comment by Quorafind** [comment]
另外可否提供一两个日记文本（去掉隐私信息后）

**Comment by Feng-Xiaohan** [comment]
> 可以提供以下你的日记插件的设置吗？

可以，设置要哪些？或者是需要我一个个截图？还是说，我直接把我的日记插件打包进压缩包发上来可以吗？

**Comment by Feng-Xiaohan** [comment]
> 另外可否提供一两个日记文本（去掉隐私信息后）

可以，我来打包几个。

**Comment by Quorafind** [comment]
截图日记插件界面，然后日记文本打包

**Comment by Quorafind** [comment]
请更新新版，应该修复了。

**Comment by Feng-Xiaohan** [comment]
> 截图日记插件界面，然后日记文本打包

[20240328.md](https://github.com/Quorafind/Obsidian-Thino/files/14783825/20240328.md)
没有放更多，所以没打包，，这个文件我已经确定了可复现。

日记插件界面是这个吗？
![thino](https://github.com/Quorafind/Obsidian-Thino/assets/63276191/2fe443c4-cb5d-43f7-b94e-7ec985383ede)

**Comment by Quorafind** [comment]
没事，应该已经修复，更新就好

**Comment by Feng-Xiaohan** [comment]
> 没事，应该已经修复，更新就好

已修复！解决了！
