### ISSUE TITLE
Feature Request: 增加表格页面的“导出”功能，

### ISSUE THREAD

**Issue by yliing** [Quorafind/Obsidian-Thino#467]
### Feature Requested | 请求的功能

目前，表格页面，只有内容展示，无导出功能。
<img width="942" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/60873827/eca65a44-67e6-4fe6-9150-8822c79fbe38">

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by juestchaos** [comment]
导出是想导出图片？还是导出 excel？
导出是否支持跨页？是否允许选择具体的信息项导出？

**Comment by Quorafind** [comment]
已经支持导出为截图

**Comment by yliing** [comment]
如果能导出为excel是比较理想的。因为笔记本身在不同的文件格式下（比如单文件、多文件、画布）等等，如果要进一步进行处理，会非常不便。现在笔记列表能显示的是属性和内容，能支持这些导出对用户来说就是比较大的帮助。
至于是否有选项，可以默认勾选，导出文件之后用户可以自动选择需要的恩荣。

**Comment by yliing** [comment]
> 导出是想导出图片？还是导出 excel？ 导出是否支持跨页？是否允许选择具体的信息项导出？

如果能导出为excel是比较理想的。因为笔记本身在不同的文件格式下（比如单文件、多文件、画布）等等，如果要进一步进行处理，会非常不便。现在笔记列表能显示的是属性和内容，能支持这些导出对用户来说就是比较大的帮助。
至于是否有选项，可以默认勾选，导出文件之后用户可以自动选择需要的内容
