### ISSUE TITLE
[Bug]: 和attachment management插件冲突

### ISSUE THREAD

**Issue by linfengtongxue70** [Quorafind/Obsidian-Thino#468]
### Bug Description | BUG 描述

插入图片到thino时会被attachmentmanagement插件重命名，导致
- 编辑界面仍然是之前的地址，无法显示图片
- 退出编辑界面后因为检索而又把图片展示出来了 

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
如果使用的是单文件模式，attachment management 插件，重名文件时候
会修改 callout 结构里面内容，且修改是错误的。
导致如图，原文被 attachment management

这是因为 attachment management 在 thino 写入同步id 时，也同时去操作写入
到时 破坏了 thino 写入的单文件结构


下图是 单文件修改异常的问题
![image](https://github.com/Quorafind/Obsidian-Thino/assets/241007/fc946892-b28e-4d3d-80b6-e48e51c5cf0e)

![image](https://github.com/Quorafind/Obsidian-Thino/assets/241007/55ab1099-089e-4ed0-808e-075c6be6bf40)

**Comment by Quorafind** [comment]
看起来似乎是 attachment management 单方面的问题，暂时不考虑修复。
