### ISSUE TITLE
[Bug]: 编辑后保存无效

### ISSUE THREAD

**Issue by Feng-Xiaohan** [Quorafind/Obsidian-Thino#469]
### Bug Description | BUG 描述

编辑后点击保存，内容依旧是编辑前内容。  
  
测试时补充：未开启同步。  
  
具体视频如下。

### Relevant Screenshot | 相关截图

https://github.com/Quorafind/Obsidian-Thino/assets/63276191/69b4595d-cf5d-41bd-8355-eb86e8f07d1a

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
请更新 2.3.26 后使用命令，复制调试信息，然后粘贴信息到这里，谢谢

**Comment by Feng-Xiaohan** [comment]
> 请更新 2.3.26 后使用命令，复制调试信息，然后粘贴信息到这里，谢谢

在收到信息后我进行了插件的更新，但抱歉，更新后我似乎无法复现这个 bug 了——哪怕编辑视频中那一条 thino 我也未能复现本 bug。
将来再发现类似情况我会将调试信息复制至此。
还是说，哪怕没有复现，依旧可以把信息复制过来？

**Comment by Quorafind** [comment]
可以等复现再重新贴过来
