### ISSUE TITLE
[Feature Request]: Modern主题中，筛选后点击最活跃的一天应当跳转

### ISSUE THREAD

**Issue by xiaomingyu-git** [Quorafind/Obsidian-Thino#471]
### Bug Description | BUG 描述

![6a77eae94c14e2461054644c9742bfe](https://github.com/Quorafind/Obsidian-Thino/assets/44595719/5ee5f6b7-3088-4afa-82bb-539bd09031c5)
最新版本，换成这个主题。点使用天数，再点活跃的一天
![2817037a62ca4339feaf4de06b4c473](https://github.com/Quorafind/Obsidian-Thino/assets/44595719/3f8918c3-4a41-42f0-8da4-b0b17926637d)

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
默认行为，需求视为功能请求
