### ISSUE TITLE
请求新增一个“动态模式下”点击“照相机按钮”的替代命令。

### ISSUE THREAD

**Issue by wopanda** [Quorafind/Obsidian-Thino#472]
### Feature Requested | 请求的功能

在手机端，更希望能够通过下拉，实现快速便捷输入，特别是在动态模式下，而不是通过点击“照相机按钮”实现输入。

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/61578085/593905cb-126e-41b1-bdab-d9ef6f2593d6)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by juestchaos** [comment]
有一个快速浮窗编辑器的明亮，可以在 ob 快捷键中绑定

**Comment by wopanda** [comment]
> 有一个快速浮窗编辑器的明亮，可以在 ob 快捷键中绑定

但是，这个功能并没有把编辑器释放出来，仅是弹出thino界面。

**Comment by Quorafind** [comment]
已支持，移动端搜索`显示编辑器`
