### ISSUE TITLE
[issue]: 单文件和多文件模式相关问题

### ISSUE THREAD

**Issue by keji1115** [Quorafind/Obsidian-Thino#473]
### Bug Description | BUG 描述

我在thino里创建了“[[双链]]” 就会在根目录显示（图1）;如果我把它移动到thino里并且点击刷新，就会出现一个[[双链]]+一个[[双链里的内容]]。
我只想要一个双链就可以了，不想在把双链里面的内容显示出来，并且我想创建双链直接显示在一个文件夹而不是跟目录里，
请问该怎么操作？

### Relevant Screenshot | 相关截图

![](https://kgaocn.oss-cn-hangzhou.aliyuncs.com/img/202403280942180.png)

![image](https://github.com/Quorafind/Obsidian-Thino/assets/97817881/fedd9ff3-d0dc-45f3-b96a-d96529560d6d)

### Obsidian Version | Obsidian 版本

1.5.8 和2.3.29

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
多文件模式中设置文件夹为你需要的文件夹，举个例子：

folder1/folder2，用 `/` 拆分路径

**Comment by Quorafind** [comment]
同时请检查是否是单文件意外放置到了多文件的文件夹中。
