### ISSUE TITLE
[Bug]: Checkbox 点击异常

### ISSUE THREAD

**Issue by DearTang** [Quorafind/Obsidian-Thino#476]
### Bug Description | BUG 描述

thino版本：2.3.33
添加checkList，只能在方框和文字中间点击才可以选中，点方框或者文字都不行

### Relevant Screenshot | 相关截图

![图片](https://github.com/Quorafind/Obsidian-Thino/assets/26248654/8042ae30-0375-4ab6-8e81-0514c9d28c60)

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
请检查是否是主题影响

**Comment by DearTang** [comment]
确认为主题导致，修改为默认主题正常。经过对比，编辑文档里面的选框不受主题影响
