### ISSUE TITLE
Feature Request: 希望将主界面的标签筛选改为可以多选，实现组合标签过滤。

### ISSUE THREAD

**Issue by Thinkbond** [Quorafind/Obsidian-Thino#478]
### Feature Requested | 请求的功能

如题，建议把标签过滤改为**可**多选的模式，便于精确定位。

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/9856020/16d8ef6e-43ab-4142-a36f-0c7e80851282)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by yankai19900930** [comment]
可以使用检索那个，这个常用标签可能单选跳转更快些？

![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/f0d3caae-7ca2-4ed4-beba-4a99ae60e2d0)

**Comment by Thinkbond** [comment]
更新日志无法点击x关闭
![IMG_2263](https://github.com/Quorafind/Obsidian-Thino/assets/9856020/7ef94a1a-9f27-49d6-a7c8-68e8217335ae)

**Comment by Quorafind** [comment]
查看是否是主题影响，你的关闭标签在右上角

**Comment by Thinkbond** [comment]
Prism主题，iOS17
更新日志窗口没法再打开了（强制退出后台了

**Comment by Quorafind** [comment]
> Prism主题，iOS17
> 更新日志窗口没法再打开了（强制退出后台了

在设置菜单中可以重复点击查看

![Screenshot_2024-03-30-08-01-18-679_md.obsidian.jpg](https://github.com/Quorafind/Obsidian-Thino/assets/13215013/5964a5b0-9fed-476f-8665-b2796d760b12)

**Comment by Thinkbond** [comment]
![IMG_2265](https://github.com/Quorafind/Obsidian-Thino/assets/9856020/ba0f1eac-bb1c-4e32-afd9-3b3a98df6855)
![IMG_2264](https://github.com/Quorafind/Obsidian-Thino/assets/9856020/4e19f43f-b669-4f07-a60c-59e4d721ab99)
分别在默认主题和AnuPpuccin主题下测试。外观选项下也已关闭了各种自定义css。iPhone为5.8寸。是不是可以通过把更新日志标题缩小防止整个界面缩放？

**Comment by Quorafind** [comment]
你可以看一下别的类似弹窗窗口会不会有同样问题，例如插件下载窗口等

**Comment by Thinkbond** [comment]
应该主要是配图导致的，另外我把obsidian外观里的字号等缩放也调整成默认值，还是会撑满整个屏幕。

**Comment by Thinkbond** [comment]
![Uploading IMG_2266.png…]()

**Comment by Thinkbond** [comment]
![IMG_2266](https://github.com/Quorafind/Obsidian-Thino/assets/9856020/b50eea82-6ea0-4119-bf33-445c5ea6ef72)

**Comment by Quorafind** [comment]
好的，我要验证下

**Comment by Thinkbond** [comment]
> ![IMG_2266](https://private-user-images.githubusercontent.com/9856020/318155111-b50eea82-6ea0-4119-bf33-445c5ea6ef72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NTg4NzAsIm5iZiI6MTcxMTc1ODU3MCwicGF0aCI6Ii85ODU2MDIwLzMxODE1NTExMS1iNTBlZWE4Mi02ZWEwLTQxMTktYmYzMy00NDVjNWVhNmVmNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMDAyOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M3NzJhMmJmYTkyZjk2N2IyMzRmODE1Nzg1MzI2ZDQ2M2JkMjYyZjgzYTI2YjRjNTQzOTRjNzIxMDFlYWFkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lLAryyfbivSSkKKI9CPBnDFfXvn1kw58Xm1GEtZ5kb8)

大叔这个插件在右下角加了close按钮

**Comment by Thinkbond** [comment]
> ![IMG_2266](https://private-user-images.githubusercontent.com/9856020/318155111-b50eea82-6ea0-4119-bf33-445c5ea6ef72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NTg4NzAsIm5iZiI6MTcxMTc1ODU3MCwicGF0aCI6Ii85ODU2MDIwLzMxODE1NTExMS1iNTBlZWE4Mi02ZWEwLTQxMTktYmYzMy00NDVjNWVhNmVmNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMDAyOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M3NzJhMmJmYTkyZjk2N2IyMzRmODE1Nzg1MzI2ZDQ2M2JkMjYyZjgzYTI2YjRjNTQzOTRjNzIxMDFlYWFkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lLAryyfbivSSkKKI9CPBnDFfXvn1kw58Xm1GEtZ5kb8)

大叔这个插件在右下角加了close按钮。

**Comment by Thinkbond** [comment]
![IMG_2302](https://github.com/Quorafind/Obsidian-Thino/assets/9856020/172bb41d-491b-4cac-9c61-7555f741029c)
新版已解决👍

**Comment by SummerMoreSummer** [comment]
> 已支持，PRO 用户按住 ctrl 或者 meta 键去点击多个即可

- 希望考虑 点击一个 tag, 则过滤出的卡片集合 里 所有其他标签 能够显示加粗, 然后用户 再次按下 ctrl + 其他标签,
可以快速 过滤为 tag 1 and tag 2 (目前的逻辑是 tag1 or tag2)
