### ISSUE TITLE
Feature Request: 图片预览界面增加拖动功能

### ISSUE THREAD

**Issue by Ami-Nous** [Quorafind/Obsidian-Thino#479]
### Feature Requested | 请求的功能

点击图片弹出预览界面，放大图片到超出屏幕之后，图片会强制左对齐，不能拖动查看右边的部分。

希望图片预览界面增加拖动图片功能。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
按住 shift 可以滚动到右边查看
