### ISSUE TITLE
[Bug]:  Canvas模式的卡片重叠

### ISSUE THREAD

**Issue by yliing** [Quorafind/Obsidian-Thino#480]
### Bug Description | BUG 描述

在Canvas模式下，如果调整了卡片的大小，新生成的卡片就会变得和原来的卡片一样大。
并且如果卡片之间还会重叠。
![image](https://github.com/Quorafind/Obsidian-Thino/assets/60873827/106933b3-53ec-47c6-86a7-eddad0077a3e)

### Obsidian Version | Obsidian 版本

最新

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
默认行为，这个会依赖于最后的卡片大小
