### ISSUE TITLE
Feature Request: 修改checkbox的情况下，快速双击会进入编辑模式、从而导致正在编辑的内容丢失。

### ISSUE THREAD

**Issue by xiaomingyu-git** [Quorafind/Obsidian-Thino#481]
### Feature Requested | 请求的功能

提供一个不会错误进入编辑模式的方法。比如可以让用户关闭 双击进入编辑模式的功能（）
或者在双击编辑的时候，如果输入框中有内容，给予提示，让用户选择是否继续进行编辑

### Relevant Screenshot | 相关截图

https://github.com/Quorafind/Obsidian-Thino/assets/44595719/4c968033-1501-4ada-a87c-81a6bd454d58

1.快速点击checkbox导致的错误进入编辑模式

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已修复
