### ISSUE TITLE
[Feature Request]: Issues related to moments view

### ISSUE THREAD

**Issue by xiaoxiang01a** [Quorafind/Obsidian-Thino#482]
### Bug Description | BUG 描述

ob主题为默认主题
多标签在末尾显示不好：
![image](https://github.com/Quorafind/Obsidian-Thino/assets/73389963/41f988e8-f919-4f9c-abf2-fb47cfda4886)
可以参考看板这个插件

图片的九宫格会导致原有图片被裁剪问题
![image](https://github.com/Quorafind/Obsidian-Thino/assets/73389963/56a0b4e9-9862-42e4-a9f6-b10ffcfd03c8)

动态视图置顶取消不了
![2_new](https://github.com/Quorafind/Obsidian-Thino/assets/73389963/cc63d610-97e6-4484-a9dd-861f9966146b)

### Obsidian Version | Obsidian 版本

1.5.8

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by cumany** [comment]
收到  下一版还会优化

**Comment by Quorafind** [comment]
置顶问题已修复

**Comment by Quorafind** [comment]
裁剪问题已修复
