### ISSUE TITLE
Feature Request: Custom local images for background or icon in Moments view 

### ISSUE THREAD

**Issue by dangguizai** [Quorafind/Obsidian-Thino#483]
### Feature Requested | 请求的功能

现在动态视图的背景图和头像图片似乎只能用URL，但是我是希望直接用Obsidian附件里面的图片

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/67644146/617e2973-6881-47dd-aace-3da354de47f6)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
了解，会考虑

**Comment by Quorafind** [comment]
已支持
