### ISSUE TITLE
[Feature request]:  Thino count number issues

### ISSUE THREAD

**Issue by whong1618** [Quorafind/Obsidian-Thino#484]
### Bug Description | BUG 描述

Thino 支持多级标签。

帮助文档中提到：【数字显示】当你使用标签功能的时候，会发现标签的右侧会展示其计数，其基于这个标签有被多少个 Thino 卡片使用过来进行计算。

当我编辑一个 Thino 卡片时，使用了多级便签，比如 #tag1/tag2/tag3 ，那么这个 Thino 卡片同时使用了 tag1、tag2 和 tag3 三个标签，逻辑上 tag1、tag2 和 tag3 三个标签的数字计数都应该增 1，然而目前的 Thino 版本，实际上只有最后一级的 tag3 标签的计数会增 1。

既然支持多级标签，那么计数的逻辑最好也能匹配多级标签的设计，这样标签的数字显示可以更好地体现该标签实际被 Thino 卡片使用的次数。

希望开发者能够解决这个问题，期待中……

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
我认为这个应该算是一个改进需求，会考虑实现

**Comment by Quorafind** [comment]
已支持
