### ISSUE TITLE
[Bug]: Style issue with `webid` render

### ISSUE THREAD

**Issue by Yubuxin** [Quorafind/Obsidian-Thino#485]
### Bug Description | BUG 描述

同步后的 thino 的 webid 字符串在所见即所得模式下，应显示为一个地球小图标，但我的桌面端 Obsidian 中依旧显示为一条字符串（移动端倒是正常显示）。
因为已经实验过关闭全部插件（Obsidian 安全模式）、使用默认主题，依旧无效，该问题应该不是由与其他插件冲突所致。
虽然是个很小的问题，无伤大雅，但既然遇到了感觉还是提一下比较好。谢谢！

### Relevant Screenshot | 相关截图

<img width="705" alt="截屏2024-03-31 14 18 20" src="https://github.com/Quorafind/Obsidian-Thino/assets/87011715/5ad3ecfd-104b-4026-a379-43042d0ab3f2">

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
你可以在 webid 的 ] 右边加一个空格测试是否能正常渲染

**Comment by juestchaos** [comment]
你是使用了查找来源，或者是直接到存储的文件位置，光标聚焦到编辑内容中了
你可以尝试回车，或者增加空格，渲染图标就生效了。
正常情况如果不是触发了编辑状态，这个会渲染成图标的
