### ISSUE TITLE
[Bug]: Cannot use Ctrl+Enter to save thino via Editor

### ISSUE THREAD

**Issue by Nirvana-Chow** [Quorafind/Obsidian-Thino#486]
### Bug Description | BUG 描述

目前版本为2.3.38
thino编辑器无法使用ctrl+enter快捷键发送笔记

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
什么主题以及什么样式

**Comment by Nirvana-Chow** [comment]
> 你所使用的是什么主题或者什么样式？以及什么场景下不能 Ctrl+Enter 来触发
minimal主题，没有其他样式，如下代码生成的编辑器，无法快捷键发送笔记
```thino
{
  editor: true
}
```

**Comment by Quorafind** [comment]
嵌入的编辑器会受到 Markdown view 的影响，你可以检查下是否是你设置了一个快捷键为 `Ctrl+Enter`

**Comment by Nirvana-Chow** [comment]
感谢 ok了 ，ob默认这个快捷键是在光标处打开新标签页 现在好了 谢谢！
