### ISSUE TITLE
[Bug]: 多文件模式下。分割线后的内容无法显示

### ISSUE THREAD

**Issue by xiaomingyu-git** [Quorafind/Obsidian-Thino#488]
### Bug Description | BUG 描述

多文件模式下。分割线后的内容无法显示，而日记模式下，分割线后的内容可以正常显示、

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/44595719/19674a40-cefc-4969-934c-875fa679239c)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/44595719/275ce0e9-1c92-4002-891c-d035a986e2dd)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/44595719/7bf7330a-7a2a-4b67-842a-023da58c263f)

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复
