### ISSUE TITLE
[Bug]: Thino type issues related to Table view

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#489]
### Bug Description | BUG 描述

表格视图的【thino类型】无法正确显示，详见截图

### Relevant Screenshot | 相关截图

![20240331_223730_774_copy](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/8d205fa7-7071-4bbe-8d6f-aa8f26a8a1ed)

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
点击这个的时候会筛选什么内容出来？

**Comment by yankai19900930** [comment]
task done

**Comment by juestchaos** [comment]
你可以看下你是什么主题，目前最新版中，没有这个问题了
![image](https://github.com/Quorafind/Obsidian-Thino/assets/241007/1509c11f-b249-4b7f-afca-13928b1f864c)
