### ISSUE TITLE
[Bug]、Feature Request: #Collection/WeChat forwarded by WeChat is automatically displayed on the first line instead of the last line.

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#490]
### Feature Requested | 请求的功能

微信转发的 #收集/微信 自动显示在第一行，而不是最后一行。原因有四处：

1、当前版本存在 #标签 与图片重叠的问题；
2、若图片过长，标签又在尾部，通常要拖到底部看下标签，再拉回来首行开始看图。若更改过来符合，先看 主题（#标签），再看内容的直觉。
3、当通过微信转发一张图片，在手机端若想再次编辑，由于是图片置顶，想要修改非常不好操作。 若是非图片（标签）则非常容易编辑。
4、若标签显示在第一行，且自动空行。这样能展现标签的最完美格式，一眼能看到主题。

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/47029689-750e-4281-abe7-a5fe6fe5b316)

![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/67235db8-93bb-488c-bc17-36d3401027ef)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by juestchaos** [comment]
个人感觉可以讨论下
从实际编辑体验看，标签放在头部是比较容易的方式
从排版角度讲，貌似放在最下面对信息阅读更高效

正常应该是等产品更加成熟，尤其微信同步更加成熟后，在 web 给用户一个自己设置的空间

建议可以飞一会儿，看看其他用户建议和习惯
