### ISSUE TITLE
[Bug]: Issue related to Multi-Files and Daily

### ISSUE THREAD

**Issue by whong1618** [Quorafind/Obsidian-Thino#491]
### Bug Description | BUG 描述

默认保存位置为日记时，当天我创建数个卡片后，当日卡片保存的那个日记md文档，Obsidian重启后，也会被Thino解析为一个卡片，造成卡片内容重复，标签数量翻倍的问题

下面截图说明：

【1】当日新创建了两个卡片：

![新创两个卡片](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/229cb70b-4aba-41c6-97d8-b3acdeda7161)

没有重启Obsidian之前，这个显示结果时正常的，也是符合预期的。

【2】当我重启Obsidian之后，Thino界面发生了变化，带日期的日记md文档也被Thino识别为一个新卡片，给加入进来，这样就导致内容重复，标签数量也翻倍了，卡片数量比我创建的2个，自动多出了一个日记md文档的那个卡片。

![日记文件的全部内容会作为表一个卡片](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/6306d985-2399-424f-9e62-98ccee9e38cf)

这种情况已经影响了Thino的使用体验，希望能予以解决，谢谢！

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
去 Thino 设置，高级设置，多文件，查看你是否设置了该文件夹为 thino 多文件夹的来源

**Comment by whong1618** [comment]
> 去 Thino 设置，高级设置，多文件，查看你是否设置了该文件夹为 thino 多文件夹的来源

经测试，确实和这个 【多文件】 文件夹名的设置有关，但似乎也存在设计上的小Bug：
我的【日记】设置的文件夹为：日记Thino
【多文件】文件夹的设置的是默认的：Thino

【虽然两个文件夹名不完全一致，但是Thino目前版本确认【多文件】来源的规则并不是按照文件夹名的绝对一致，只要文件夹名包含了【多文件】文件夹设置的名字，就会被识别为【多文件】的有效来源。

也正是因为如此设计上存在的小问题，才出现了我上面的情况。

虽然可以通过修改名称来避免这种包含情况，但还是希望可能的话，设计者修改其中的逻辑，以文件夹名严格一致的判断逻辑，来确定【多文件】的来源，这样会更符合使用习惯。

**Comment by Quorafind** [comment]
多文件来源的文件夹可以同时存在多个，例如可以

日记/thino
周记/thino

这样用户只要满足 thino 的文件夹都可以进到 thino 中。

当仅有部分的时候，可以允许最大范围的匹配。修改绝对匹配的话，反而限制了可能性，也许未来会加一个绝对匹配的选项

**Comment by whong1618** [comment]
> 多文件来源的文件夹可以同时存在多个，例如可以
> 
> 日记/thino 周记/thino
> 
> 这样用户只要满足 thino 的文件夹都可以进到 thino 中。
> 
> 当仅有部分的时候，可以允许最大范围的匹配。修改绝对匹配的话，反而限制了可能性，也许未来会加一个绝对匹配的选项

明白了，这样设计，可以更好利用【多文件】，从而将多个来源的文件自动引入Thino。
