### ISSUE TITLE
Feature Request:   Pin status and Time range for Moments view

### ISSUE THREAD

**Issue by yankai19900930** [Quorafind/Obsidian-Thino#492]
### Feature Requested | 请求的功能

感谢bon的超级开发，thino越发强大！

近期在使用的过程，有两个小功能看看能否实现：

①增加【Pin】状态设置
 目前将很多证件、密码信息放在pin中，能随时查看。但是每次重新打开pix都是默认展开，干扰显示，可否增加设置pin的默认状态（折叠），这样不会造成信息干扰。

②【动态视图】增加【日期标记范围】 
【动态视图】由于没有【日记标记范围】，自然也没法用折叠的pin。

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/135247747/1c4b3079-df41-4cac-b016-0ec2c9815459)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已支持
