### ISSUE TITLE
Feature request: Custom hotkeys

### ISSUE THREAD

**Issue by fnfnfngmail** [Quorafind/Obsidian-Thino#493]
### Feature Requested | 请求的功能

大佬,可以把快捷键放开设置,让用户自己设置吗,.

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已经卸载掉 Alt + 1~4 的相关快捷键。其余快捷键在快捷键均可找到
