### ISSUE TITLE
Feature Request: Blank line style issue with Thino

### ISSUE THREAD

**Issue by whong1618** [Quorafind/Obsidian-Thino#494]
### Feature Requested | 请求的功能

Thino卡片在【每日Thino】中段落的间隔空行不显示，对应日记md文件中 Callout等不能正常显示，要是各处可以展示Thino卡片的地方在视觉显示上都能保持尽可能的一致，就更好了！

下面用截图说明：
【1】新创建了两个卡片，一个卡片包含两个段落，一个卡片包含一个Callout，在Thino卡片中，这些组成元素都能正常显示，符合预期。
![创建了两个卡片](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/f213fce4-8606-4843-86ec-7a4f374a8052)

【2】在点击日期，展示【每日Thino】的界面，Callout元素倒是可以显示，不过原卡片中的段落间空行，以及Callout中的标题和内容的间隔空行，都不会正确显示。卡片的内容会比较紧凑的排在一起，所有的间隔空行都不显示。

【如果这里能改善显示，使得每日Thino中的卡片显示样子和原卡片的保持一致，那么感觉会更好，一致性是一种美】
![每日Thino空行被移除](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/8ecfca9d-6a68-4c9e-8078-ba788c636d86)

【3】【日记模式】下，Thino卡片会被写入对应日期的md文件中，不过在这个文件中，原卡片中的Callout之类的组成元素不能正常显示。

【如果在这个md文件中，也能保持原Thino卡片中的显示样式，那么给人的感觉会更棒】
![对应的日记md文件中](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/51921f8c-0b2a-4ee8-905b-2e6962a39df8)

对于以上存在的一些显示方面不够完美的地方，希望Thino开发人员可以考虑改进。至少可以考虑在【每日Thino】中能保留原卡片的空行，挤在一起，影响视觉感受。与原卡片保持一致的视觉展示，感觉让人会更舒服。

如果可以实现原卡片、每日Thino及md文档等可展示卡片内容的地方，在显示上都尽可能保持一致，那么Thino将会更受欢迎，至少我会更喜欢。

期待开发者的改善和反馈，谢谢！

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已修复

**Comment by whong1618** [comment]
> 已修复

太给力了，解决问题的速度感人！！！刚去更新版本了，每日Thino里可以原样展示卡片内容，浏览起来舒服多了！

**Comment by whong1618** [comment]
@Quorafind 
标签与卡片笔记内容之间，笔记段落之间，以及callout的标题和内容之间的间隔空行，好像依然还是不能正常显示。

截图如下：
【1】更新版本到2.3.47之后，新创建两个卡片
![创建两个卡片](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/620509e8-1dbb-4882-ac70-b61ea9360dd8)

【2】每日Thino中间隔空行不显示的情况依然存在，标签与段落之间，段落与段落之间，Callout的标题与内容之间的间隔空行，还是不能正常显示，依然挤在一块，看起来不舒服。
![每日Thino间隔空行还是没解决](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/f7e09a9a-95ea-4afd-b5f3-89a7dacf3727)

麻烦核实后，予以修复，谢谢！

**Comment by whong1618** [comment]
@Quorafind 

更新版本到2.3.48后，标签和段落，以及段落之间的间隔可以正常显示了。
太给力了，修复的真及时，现在翻看 【每日 Thinio】感觉舒服多了。

Thino越来越好了，感谢开发者的努力！
