### ISSUE TITLE
[Bug]: Long tag style issue

### ISSUE THREAD

**Issue by whong1618** [Quorafind/Obsidian-Thino#495]
### Bug Description | BUG 描述

Thino卡片中长标签不能自动换行显示，电脑端屏幕大还好说，但手机端屏幕宽度有限， 会导致卡片中的标签显示不全，影响使用体验！！！

长标签在阅读模式和【每日Thino】中倒是可以自动换行，希望开发人员能重视这个问题，予以解决，以完善Thino，增强使用体验。

电脑端的截图如下：

【手机端屏幕窄，非常容易出现多级标签长度超过卡片一行宽度的情况，标签显示不全，会影响卡片的浏览和阅读】

【由于Thinio属于闪念笔记类型，随时在手并保持开机状态的手机使用Thino的频率会很高，至少对我来说是这样，希望开发人员能重视这个问题！】

【1】创建了一个较长的多级标签卡片，在Thino的卡片中，长的标签在一行中不会自动换行展示。
![长多级标签](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/f030fc22-09cf-4746-9450-690b076276ca)

【2】阅读卡片的模式下，倒是可以对长标签自动换行显示。

![阅读模式下长多级标签可以自动折行](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/efa0258d-f5ba-4585-a786-f69c7b0756e2)

【3】每日 Thino中虽然不会显示段落间的空行间隔，倒是可以对长标签自动换行显示。
![每日Thino下也可以自动换行](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/7bc32df1-5a12-400a-a4e1-6732bf1138ab)

既然在 【每日 Thino】和 阅读模式下，长标签都可以自动换行显示，那么技术上大概率应该也可以实现 Thino卡片对长标签进行自动换行的显示。

希望开发人员能够解决这个问题，让我们在使用标签系统时，可以更顺手，更好发挥Thino的生产力工具的价值。提前感谢了！

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复

**Comment by whong1618** [comment]
> 已修复

太给力了，感谢，已经更新版本2.3.48，长标签自动换行的问题解决了。
