### ISSUE TITLE
[Feature Request]: Compatiable with "paste mode" plugin

### ISSUE THREAD

**Issue by LoneFireBlossom** [Quorafind/Obsidian-Thino#496]
### Bug Description | BUG 描述

同时开启这个插件 https://github.com/jglev/obsidian-paste-mode 和thino插件，在thino的输入框里无法进行粘贴操作。

### To Reproduce | 重现问题

1. 新建一个仓库
2. 安装paste mode和thino插件
3. 打开这两个插件
4. 打开thino插件的输入框，粘贴文字，会发现粘贴不上
5. 调整paste mode的设置也还是粘贴不上<img width="791" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/50087596/6ec8782e-31af-4c2b-8d0a-6ba96f3b6bc2">
6. 把thino改成source模式显示就能粘贴了

**但是！但是！**
这个冲突很奇怪……
我一开始在沙箱仓库里测试，发现能粘贴。
但是我新建一个仓库测试就不能粘贴了。
然后重启Obsidian来回几次，不知怎么的就又能粘贴了。
然后我开启了几个thino的选项，不知怎么的就又不能粘贴了。
我把上面刚开启的选项一一关上，重启Obsidian再粘贴，还是不行。
实在是把我搞懵了……

我的意思就是，可能按照上面的步骤并不能立刻复现出bug……开发者要是复现这个bug的话，就多开关几个选项、重启obsidian试试

macOS Ventura 13.6.5

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
我无法复现你说的这个情况，能否提供更多信息？

**Comment by LoneFireBlossom** [comment]
我试了一下，不知为何现在没这个bug了……那我关了
