### ISSUE TITLE
Feature request：Support templater via slash command in Obsidian

### ISSUE THREAD

**Issue by weqoocu** [Quorafind/Obsidian-Thino#500]
### Feature Requested | 请求的功能

这是templator模板的内容：

需求::
产品::
编码::8.1.<% tp.date.now("YYYY-MM-DD")%>
### Relevant Screenshot | 相关截图

提示报错
<img width="250" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/35360006/d7efbf95-5405-4462-9878-8fc3ceb7fe6a">

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已修复
