### ISSUE TITLE
Feature Request: support camera when input in thino

### ISSUE THREAD

**Issue by xiaomingyu-git** [Quorafind/Obsidian-Thino#501]
### Feature Requested | 请求的功能

希望能在安卓移动端在插入图片的时候，可以选择调用相机拍照。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
Thino 无法越过 Obsidian 启用权限，该功能无法实现
