### ISSUE TITLE
[Bug]: Editing Toobar 在 Thino 插件编辑窗口中不能用，但是在Thino之外的md文件编辑窗口中可正常使用

### ISSUE THREAD

**Issue by whong1618** [Quorafind/Obsidian-Thino#503]
### Bug Description | BUG 描述

Editing Toobar 在 Thino 插件编辑窗口中不能用，除了全屏等几个点击有效外，其他多数工具图标，点击没啥反应，但是在Thino之外的md文件编辑窗口中可正常使用。

Thino插件和Editing Toolbar插件都更新到最新版的，麻烦开发人员核实一下问题，尽快解决一下，谢谢！

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
这个是 editing toolbar 的问题
