### ISSUE TITLE
[Bug]: 标签右侧的数字显示存在错误，会显示NaN；标签面板显示待完善，各级长标签建议都可换行显示，部分标签和统计数字没有空格间隔

### ISSUE THREAD

**Issue by whong1618** [Quorafind/Obsidian-Thino#504]
### Bug Description | BUG 描述

Thino版本已更新到最新的2.3.56，然后发现标签右侧的数字显示，存在错误：

父级标签很多显示 NaN，

另外，我刚才尝试了一下，好像知道问题的原因了：

如果父级标签，最开始以独立标签出现过，独立标签的处理逻辑是可行的，那么这个标签就拥有了数字类型的计数记录，后面如果子标签使用这个父级标签，会给这个父级标签增1，父级标签的统计就不会出现问题。

如果父级标签之前从来没有作为独立标签出现过，那么后期，当该父级标签在多级标签中首次出现时，统计时会因为出现在多级标签中而执行增加计数的操作，但是由于之前该父级标签的统计计数变量没有赋值过，所以是undefined，那么对undefined与数字相加，结果会是NaN，之后再将对这个NaN执行加1操作，结果都仍然会是NaN，也就导致没有一开始就以独立标签出现过的父级标签的标签计数统计结果都显示为NaN。

增加一个逻辑，给所有第一次出现的标签，不管是作为独立标签，还是作为多级标签中的各级标签，都给一个初始值1，这样也许可以解决问题，当然开发者也许有更好的处理办法。以上只是浅见，仅供参考。

希望开发者核实后，给与修复，谢谢！

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复
