### ISSUE TITLE
[Bug]: Tag issues

### ISSUE THREAD

**Issue by whong1618** [Quorafind/Obsidian-Thino#505]
### Bug Description | BUG 描述

Thino已更新到2.3.57，标签面板多级标签显示NaN问题有改善，但只改善了倒数第二级标签，往上各级标签依然会显示NaN：

截图说明：

【1】新创建一个多级标签的卡片，各级标签都是首次出现

![测试的多级标签](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/e00da9fc-1731-4065-a962-ac39bacca074)

【2】倒数第二级标签已经可以正常显示，但是往上各级标签依然显示 NaN

![仍有问题的标签面板](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/8953d257-98ef-4a27-be32-ecf27e86f1b0)

【3】目前标签面板存在的显示不佳的地方及修改建议。
- 【标签前面的 # 号，可以考虑去掉，多余占空间】
- 【标签层级展开和收缩的开关建议设置在标签名前面】
- 【长标签，在保持标签层级结构不变的情况下，建议自动换行】
- 【标签和统计数字之间，至少保持一个空格】

**比较完善的标签面板式样，建议参考下图：**

![完善的标签面板](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/d6b22011-20c5-40a5-8297-62d59a7d00c2)

希望开发者对于以上问题，予以完善，谢谢！

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
内容2已经修复了
反击内容1是否有实际案例，看来更像是较为边界的极限情况

**Comment by Quorafind** [comment]
计数问题已经修复，样式稍作修改，但部分建议不考虑采纳

1、标签如果没有前边的图案，在设计上和筛选器没有统一的设计风格，会显得很怪异；
2、同上，放置在前边的折叠按钮并不是最优解，Obsidian 是因为不需要标签图案作为设计风格，所以其折叠按钮能放在前边
3、4 采纳

**Comment by whong1618** [comment]
> 内容2已经修复了 反击内容1是否有实际案例，看来更像是较为边界的极限情况

我不同意你说的这个属于较为边界的极限情况！
道理很简单：
【当我是一个Thino的新用户，或者我开始记录一些关于新知识的笔记时，会很容易出现使用之前未使用过的多级标签来记新笔记的情况！】

对于用户来说，使用之前未使用过的多级标签的情况是很常见的，不会是极限边界问题。

其实标签右侧的统计数字显示为NaN的原因很简单，就是对于任何首次出现的标签，不管是作为独立标签，还是作为多级标签中的某一级，其对应统计变量正确声明并赋值为1的处理环节不够完善。

如果缺少了对首次出现标签的对应统计变量声明并赋值为数字1的操作，那么标签对应的统计数字变量会是undefined的状态，
那么当该标签后面再次出现时，会对这个 undefined 的变量执行加1的操作，这会导致出现 NaN 的结果，后面不管怎么执行加法操作，结果都是 NaN，在JavaScript里面就会这样嘛。

只要面对任何首次出现的标签的初始化工作做好了，赋予了对应的记录次数的统计变量的正确数值，后续该标签再出现时的统计数字相应增加的计算，才会正常，从而避免出现 NaN的错误显示。
