### ISSUE TITLE
[Bug]: Tag Count Error!!!

### ISSUE THREAD

**Issue by whong1618** [Quorafind/Obsidian-Thino#507]
### Bug Description | BUG 描述

Thino更新到最新的2.3.58之后，标签右侧统计数字显示NaN的问题解决，但是对于标签的统计，仍然是存在错误的！

截图说明如下：
【1】使用标签 `#中国/天安门/天安门广场/毛主席纪念堂`
 新建一个卡片，此时标签的统计数字，倒是对的

![标签计数测试-新建卡片1](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/d1e14769-0033-4b4f-b9e6-5a4d54e08e12)

【2】使用标签 `#中国/长江/黄河` 
创建第二个卡片，标签的统计开始出错：
标签`中国`出现 2 次， 结果显示为 1

![标签计数测试-新建卡片2](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/0f815132-f873-49e5-bd54-c3c448f417ae)

【3】使用标签 `#中国/天安门/故宫` 
创建第三个卡片，标签的统计结果仍然有错误：
标签`中国`出现 3 次， 结果显示为 1；
不过 标签`天安门`出现2次，倒是显示对了。

![标签计数测试-新建卡片3-2](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/4249bda3-7a34-4bd3-9c18-17fd5a1e862b)

不太清楚，Thino背后统计标签数字的逻辑，
如果是通过解析现有卡片的所有标签，然后进行统计，等卡片发生变化的时候，再重新解析统计，按说应该不难统计出正确的结果。

不过目前来看，标签，特别是存在多级标签的情况下，对于标签的统计逻辑存在一定的问题，希望开发者核实问题，然后予以修复，谢谢！

### Obsidian Version | Obsidian 版本

1.5.11

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复
