### ISSUE TITLE
[Bug]: 界面显示错位

### ISSUE THREAD

**Issue by vapensmianm149s** [Quorafind/Obsidian-Thino#509]
### Bug Description | BUG 描述

blue topaz 主题版本2024040401使用thino2.360显示错位，使用别的主题显示正常

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/7703758/7deaf6e3-2176-4f2d-a54a-c9fd92b43ae8)

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by cumany** [comment]
更新最新版bt 主题即可  2024040402

**Comment by juestchaos** [comment]
2024040402
测试通过
