### ISSUE TITLE
[Bug]: Thino share image cannot config anymore

### ISSUE THREAD

**Issue by weqoocu** [Quorafind/Obsidian-Thino#510]
### Bug Description | BUG 描述

有自定义配置页脚
![image](https://github.com/Quorafind/Obsidian-Thino/assets/35360006/aad0a188-9bc9-4cd6-8a9b-7a162f357301)
复制后，统一是thino
![image](https://github.com/Quorafind/Obsidian-Thino/assets/35360006/b56d7fb2-7cbd-4765-92b1-14549e6d559d)

### Obsidian Version | Obsidian 版本

2.3.60

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
该样式下不再支持配置右下页脚
