### ISSUE TITLE
Feature Request: 在Thino主页面增加一个模式选择按钮

### ISSUE THREAD

**Issue by ProudBenzene** [Quorafind/Obsidian-Thino#511]
### Feature Requested | 请求的功能

因为经常需要在不同模式之间切换，以满足dataview的调用需求，因此希望可以在Thino的记录页面增加一个快捷按钮，用于指定当前输入内容的保存类型，即用来快捷控制下方截图的这个选项：

### Relevant Screenshot | 相关截图

<img width="846" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/93238080/b9d87fd3-098f-498b-8f7e-ceb028b6fca7">

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by whong1618** [comment]
Thino编辑窗口有这个功能啊

**Comment by ProudBenzene** [comment]
> Thino编辑窗口有这个功能啊

麻烦截个图指指路？

**Comment by whong1618** [comment]
> > Thino编辑窗口有这个功能啊
> 
> 找到了 感谢

不客气，还没来得及给你发截图，你就找到了，够快，呵呵！

**Comment by ProudBenzene** [comment]
> > > Thino编辑窗口有这个功能啊
> > 
> > 
> > 找到了 感谢
> 
> 不客气，还没来得及给你发截图，你就找到了，够快，呵呵！

我一直没有在意下面那行按钮的数量…以为都是格式相关的，你点一下我才发现哈哈，再次感谢！
