### ISSUE TITLE
[Bug]: 出現許多未命名的篩選器

### ISSUE THREAD

**Issue by johnnyqko0124** [Quorafind/Obsidian-Thino#512]
### Bug Description | BUG 描述

![Screenshot_2024-04-05-16-14-15-61_51606159b24eff83e24a54116878fe3e](https://github.com/Quorafind/Obsidian-Thino/assets/142400886/84b2a4fe-66c9-40ee-b8c2-0d4030c0b493)
我的手機端只裝了thino以及remotely插件，我不知道是什麼原因造成的

### Relevant Screenshot | 相关截图

![Screenshot_2024-04-05-16-14-15-61_51606159b24eff83e24a54116878fe3e](https://github.com/Quorafind/Obsidian-Thino/assets/142400886/466045dd-2f05-482c-8c9f-5505120c17e8)

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
请检查你在 .obsidian 文件夹中的 query.json 文件
