### ISSUE TITLE
[Bug]: Thino和task calendar wrapper冲突了

### ISSUE THREAD

**Issue by lxmwwl** [Quorafind/Obsidian-Thino#513]
### Bug Description | BUG 描述

点击task calendar wrapper上任务的完成标志无法原本文件的中的任务没反应（这是从2.3.61的更新开始的）

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [x] New Editor (WYSIWYG) | 新编辑器
- [x] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [x] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
能否详细描述下你的问题
比如把原文内容，拆分下操作步骤，建立什么，点击哪里，哪里又没有反应

**Comment by lxmwwl** [comment]
<img width="332" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/124525616/ff49635c-dd3d-4427-879c-55cc14e711a0">

**Comment by lxmwwl** [comment]
点击上面那个地方，以前可以将原本在日记中的文件由未完成状态变成完成状态

**Comment by lxmwwl** [comment]
最近的更新已解决
