### ISSUE TITLE
[Bug]: the menu of the card in the end of list was broken by input box

### ISSUE THREAD

**Issue by aiyou9** [Quorafind/Obsidian-Thino#514]
### Bug Description | BUG 描述

the menu of the card in the end of list was broken by input box

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/15712822/cd4090a9-dc1f-4c7c-85d5-031d40e134cb)

### Obsidian Version | Obsidian 版本

2.4.10

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
Has been fixed.
