### ISSUE TITLE
Feature Request: 支持微信读出的划线的导入

### ISSUE THREAD

**Issue by lzz66** [Quorafind/Obsidian-Thino#515]
### Feature Requested | 请求的功能

yankai19900930在issue #452中提到过“可否实现【微信读书】分享标注至thino”，目前能实现静读天下实现标注一键转至thino，但是微信读书作为更大的用户群体，可否实现在微信读书一键标注转至thino功能？

但是该issue被关闭了，现在我重新提起来，我觉得它十分有用，而且对其他人都有用。

就是要注意一下分享至thino的内容带有类似源的信息，例如 #收集/微信，而从微信读书导入的时候放一个书名在后面，但是不用有标签。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
经测试微信不支持自定义导出分享，建议使用 Obsidian Weread 插件搭配 Thino 的识别格式，例如多文件或者单文件

**Comment by lzz66** [comment]
> 经测试微信不支持自定义导出分享，建议使用 Obsidian Weread 插件搭配 Thino 的识别格式，例如多文件或者单文件

可以麻烦详细说一下多文件或者单文件的使用方式吗？微信读书用Weread插件导出的格式，文件名不是日期dd--mm-ss而是书名，这样thino不会识别；而且日期在划线笔记的前面，例如 2024-04-12 15:59:08，而不是thino能读的15:59:08，这样的话Thino就读不出来了

**Comment by lzz66** [comment]
马上就实现了，多谢~

> 经测试微信不支持自定义导出分享，建议使用 Obsidian Weread 插件搭配 Thino 的识别格式，例如多文件或者单文件
