### ISSUE TITLE
[Bug]: 同步导致的重复

### ISSUE THREAD

**Issue by linfengtongxue70** [Quorafind/Obsidian-Thino#519]
### Bug Description | BUG 描述

我同时打开了ob sync和thino web服务，以确保我可以同步thino意外的ob笔记，和接收微信收集的消息。
然而，在我确定默认以多文件保存thino的情况下，处于某种原因，导致多文件类型的thino也被备份汇总到了单文件thino中，这在我的主页看上去会有连续的重复，这看起来既不美观也无用处。
值得一提的是，重复文件会在多文件类型thino创建内的五秒内生成，且会复制其他已经创建好的thino，时间也是在其五秒后

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by linfengtongxue70** [comment]
而且删除并清除回收站后，再打开又出现了重复的QAQ

**Comment by juestchaos** [comment]
你的问题我记得好像远程给你看过，你混合同步没有排除 thino 文件夹
另外“处于某种原因，导致多文件类型的thino也被备份汇总到了单文件thino中”这是什么问题？某种原因是指？

**Comment by juestchaos** [comment]
或者更新 2.4.14 之后最新的beta版试试
