### ISSUE TITLE
Feature Request: 希望增加标签隐藏功能

### ISSUE THREAD

**Issue by SouthToSouth** [Quorafind/Obsidian-Thino#520]
### Feature Requested | 请求的功能

您好，希望在常用标签右侧可以增加一个图标，点击可以切换是否隐藏标签。使 .tags-wrapper .tags-container 的display可以在flex和none间切换。
理由：vault中同时有工作学习生活的内容。不希望在记录工作时候被同事领导看到生活相关的tag名称。

### Relevant Screenshot | 相关截图

<img width="239" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/118036951/1e8eb9af-855a-4ccb-b9b2-0ba3ab9bdefc">

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已支持，命令行启用

**Comment by SouthToSouth** [comment]
感谢！命令行方案很棒。很隐蔽
