### ISSUE TITLE
[Bug]: 保存类型为日记时，日记设置无效

### ISSUE THREAD

**Issue by ZhangQinglian** [Quorafind/Obsidian-Thino#522]
### Bug Description | BUG 描述

保存类型为日记时，thino 并不会在日记文档中追加设置里的指定标题，也不会解析指定标题后面的数据。
并且 thino web 会重复同步数据，可能是因为他无法识别标题，然后认为本地没有数据，就重复写入数据

### Relevant Screenshot | 相关截图

<img width="557" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/9946302/ca4321d2-ccea-4297-9991-69a3b8f7f998">
<img width="954" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/9946302/d553cd94-37bb-4905-886b-b49ba44064e3">
<img width="790" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/9946302/4e3639f8-f9d0-43ec-9c5b-59997612bc3f">

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
请更新最新版本测试一下

**Comment by woheme** [comment]
我也遇到相同的问题，已经是最新版本了
