### ISSUE TITLE
Feature Request:  Better render for Thino in daily notes.

### ISSUE THREAD

**Issue by whong1618** [Quorafind/Obsidian-Thino#523]
### Feature Requested | 请求的功能

【Thino 笔记对应的日记 md 文件，在编辑视图里，所见即所得的显示效果略有不足，如果可行的情况下，希望开发者可以予以改善】：
![Thino测试日记md中编辑视图【版本2 4 16】](https://github.com/Quorafind/Obsidian-Thino/assets/99108639/28eb93b6-61f2-4e49-9d9c-cda09acd138c)

（1）标题在编辑视图下，没有得到很好的格式解析。
（2）引用文本和前面的标志竖线离得有点远。
（3）代码块在编辑视图倒是能显示，不过整体代码在编辑视图下，多了一个缩进，阅读视图下正常，这点倒影响不大
（4）callout 在 日记 md 里显示虽然成块显示，但是里面显示的依然是源码，而不是 callout 的格式样式，不过在阅读视图倒是可以正常显示。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
根据调查以及相关测试，日记文件中的渲染由 Obsidian 控制，目前没有处理的方案，暂时搁置
