### ISSUE TITLE
Feature Request:  Support Obsidian word count.

### ISSUE THREAD

**Issue by whong1618** [Quorafind/Obsidian-Thino#524]
### Feature Requested | 请求的功能

Obsidian 底部状态栏中的【字数统计】及 Vimrc Support 插件的【Vim 模式显示】及【按键显示】等，

在 Obsidian 自身的 md 文件编辑窗口，可以随着编辑的实际情况，正确显示对应的状态。

但切换到 Thino 的编辑窗口后，底部状态栏的这些内容，均不能正确显示。

不管在 Thino 编辑窗口怎么编辑或者改变状态，
底部状态栏的显示内容会固定在切换到 Thino 编辑器之前，Obsidian 自身编辑器底部状态栏当时显示的状态。

也就是说 Thino 编辑器和 Obsidian 自身编辑器，在底部状态的显示上存在不兼容，如果可行的话，希望 Thino 开发者，能够就这个问题予以完善，谢谢！

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
这些内容依赖于 Obsidian 的 MarkdownView，而 Thino 只是使用了 Obsidian 的 Edtior，从当前的 Thino 视图属性修改成 MarkdownView 的话会导致 Thino 被认为是一个文件或者一个独立视图导致 Thino 甚至会出现可以被重命名的情况。而这些默认的行为除非通过大量的 hack，而这些 hack 会导致 Obsidian 本体不稳定，所以这个需求经过实践以后，认为没办法实现。故关闭
