### ISSUE TITLE
Feature Request: 增强多文件模式的能力

### ISSUE THREAD

**Issue by LoneFireBlossom** [Quorafind/Obsidian-Thino#525]
### Feature Requested | 请求的功能

在多文件模式下，
1. 希望thino能够读取文件properties里的标签，现在thino不读取，我在thino的标签栏里看不到这些标签。哦，第一点有人提过了。 https://github.com/Quorafind/Obsidian-Thino/issues/438
2. 在thino窗口打开的时候，当我在源文件夹里直接新建文件时，如下图所示，我写了一阵子之后thino才往软件里插入id，这导致我容易丢失一部分刚才写的内容。
![CleanShot 2024-04-09 at 16 54 40](https://github.com/Quorafind/Obsidian-Thino/assets/50087596/f8c4a429-35b0-4979-bca0-4742e1465059)

现在我应对这个困扰的方式是关掉thino窗口，这样文件就不会被插入id。等我打开thino窗口的时候才会被插入id。

我想了几个可能实现的方式：
- 希望thino能在我在源文件夹里新建文件时立刻插入id，这样能避免这个问题。
- thino即使是不是立刻插入id，而是之后插入id，也能有更加智能的merge文件的方式。
- thino增加一个在指定文件夹中按照指定模板新建文件的能力。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
第二点已经修复，第一点继续在之前的 issue 上追踪即可

**Comment by LoneFireBlossom** [comment]
> 第二点已经修复，第一点继续在之前的 issue 上追踪即可

现在这样也太卡了，在thino窗口打开的情况下，新建一个文件之后要等一阵子才能开始输入，体感很明显。
的确是修复了，但是我的编辑方式和之前没有区别，正式输入还是得等一阵子才能开始= = 所以我觉得这依旧是个问题
