### ISSUE TITLE
[Bug]: 不支持生成Task

### ISSUE THREAD

**Issue by maiyajj** [Quorafind/Obsidian-Thino#526]
### Bug Description | BUG 描述

使用了Tasks插件，在Thino主页编辑框内无法创建任务。
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/92a8a653-30ed-43a2-a9de-52d8fa1b7336)
需要做到的效果如下，这是我手动在日记文件内手动调整的，可是每次都要调整太麻烦了，希望在主页能支持快捷创建：
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/d91c4fdb-d909-4867-a84b-55d641f7bf3e)

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已支持调用该命令，搜索 `Thino: 插入任务`

**Comment by maiyajj** [comment]
> 已支持调用该命令，搜索 `Thino: 插入任务`
有几个问题：
1. 这个勾作用是啥，怎么默认是选中的？
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/ca5b5bbc-0cb1-4281-9638-0231135d2c38)
2. 没有插入我设定的模板中而是新建了一个文件，我的日记文件格式是2024年04月12日。而且写入格式不对，在一行的话，[ ] 没有转换成选择框，最好默认两行，时间在第一行，内容另起一行。
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/6fa0a9c9-f419-4870-abc6-f4c0a08c1a60)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/93e9e0bb-d015-48aa-bcec-33dc6dae78f5)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/7c7b66fa-0bdc-4037-a58c-b75eccb4984b)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/d1e5e607-ca45-4db2-83d3-9fa2c915dd5c)
3.完成任务时，会自动插入完成时间，插入的内容在webid链接后面了
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/70649b56-24c8-4c66-857e-a4a18072d325)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/b1244a24-4955-4001-b0b0-e435d7dba480)

**Comment by maiyajj** [comment]
4. 在任务列表点击选择框完成任务，日记源文件的任务从新建的3行变成了一行
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/ea65b9ff-b5d8-4ac6-b2cf-b0031ec77cee)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/fad3b4e0-da65-4764-a773-7b5e912c1a06)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/e5ca8c91-ac53-4df9-bad9-87e5bf15d57d)

**Comment by Quorafind** [comment]
当前不支持 Templater 插件，建议先调用再创建

复选框是指的是底层是一个任务，例如日记中的应当是：

`- [ ] 12:09:00 asdasdads`

其它下一个版本已修复

**Comment by maiyajj** [comment]
> > Bot detected the issue body's language is not English, translate it automatically...
> 
> Template plug-in is currently not supported, it is recommended to call it first and then create it.
> 
> The check box refers to the bottom layer being a task. For example, the entry in the diary should be:
> 
> `- [ ] 12:09:00 asdasdads`
> 
> Others have been fixed in the next version

基本改的很好了，但是还有一些小问题：
1. tasks我设置了自动插入完成时间，但在任务列表完成任务，没有给我自动插入完成时间，这个是我手动改的
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/c2ab0322-a6cd-408c-a01c-e9299dae4620)
2.在日记文件完成任务，插入了完成时间，但插在了超链接后面，经过测试，可以把超链接换行，而且缩进和任务一致（第二条），你们原生是最后一条。
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/670baafc-04cd-430a-8197-2583a96d01ec)

**Comment by maiyajj** [comment]
另外，测试弹窗忘了注释了 ☺
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/4d6eda57-053f-4176-a434-d0207c353735)

**Comment by maiyajj** [comment]
感觉还是不够完美：
能否也支持在日记文件内点击完成？目前在Thino内操作都正确无误。但感觉和Tasks的插件联动还有些问题，具体操作如下：
1.Thino创建任务并完成
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/80d337d4-2442-44e8-91df-85e919b44f83)
2. 日记文件取消完成，点击完成，会变成这样
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/ae6e55d2-d6d8-471f-9c11-02bb26ea88c3)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/72a4ed9b-180f-4815-a36d-f0532f6b7a4b)

**Comment by Quorafind** [comment]
https://github.com/Quorafind/Obsidian-Thino/assets/13215013/48824aba-2b71-4c70-9a0d-da97950be92f

**Comment by maiyajj** [comment]
> 没办法复现你说的场景，请看我的录屏，请测试一下关闭其它插件以后是否能复现。
> 
>  thino-tasks-realted.mp4

你试试一行的任务。

https://github.com/Quorafind/Obsidian-Thino/assets/18521350/921f166d-0968-4b75-98e5-4f0e2c0a31ee

**Comment by Quorafind** [comment]
> > 没办法复现你说的场景，请看我的录屏，请测试一下关闭其它插件以后是否能复现。
> > thino-tasks-realted.mp4
> 
> 你试试一行的任务。
> 
>  2024-04-16.092522.mp4

可以测试一下是不是只要完成标志后包含任意内容都会导致它失效，如果是的话，是 Tasks 本身的问题。刚刚经过沙箱测试，只要在 Tasks 后侧加上任意文本（除了块id外），均不兼容。

**Comment by maiyajj** [comment]
> > > 没办法复现你说的场景，请看我的录屏，请测试一下关闭其它插件以后是否能复现。
> > > thino-tasks-realted.mp4
> > 
> > 
> > 你试试一行的任务。
> > 2024-04-16.092522.mp4
> 
> 可以测试一下是不是只要完成标志后包含任意内容都会导致它失效，如果是的话，是 Tasks 本身的问题。刚刚经过沙箱测试，只要在 Tasks 后侧加上任意文本（除了块id外），均不兼容。

是这样的，所以我上面有个提议是，一个任务的时候块web_id也换行，这样就能保持完成标志后没有内容了。
https://github.com/Quorafind/Obsidian-Thino/issues/526#issuecomment-2051073920第二点

**Comment by maiyajj** [comment]
很棒，就是这样的

**Comment by maiyajj** [comment]
不过新版本不能快捷键创建任务了？

**Comment by maiyajj** [comment]
@Quorafind 不能通过快捷键创建task的问题麻烦修复一下~
