### ISSUE TITLE
[Bug]: 插入日期时缺少一个空格导致其他任务管理插件无法识别

### ISSUE THREAD

**Issue by xyy-1997** [Quorafind/Obsidian-Thino#529]
### Bug Description | BUG 描述

使用@键插入日期时，标识符和日期之间没有空格，导致Cardboard插件无法识别任务具体日期，手动添加空格后可以识别。

### Relevant Screenshot | 相关截图

![20240413013710](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/9e3faa5a-239a-4f1d-bd0e-bf26d2a1f4a4)
![20240413013546](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/29d0eaa9-ec0c-4b26-98ce-063600d203a5)

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复

**Comment by xyy-1997** [comment]
谢谢你及时修复，emoji后面确实添加了空格。但是我发现仍然有两个问题：
1. dataview格式的插入日期中间没有添加空格，“::”后面应该有一个空格；
![image](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/fa2bb032-a078-4f11-93f0-a56d5d5b5860)
2. 直接使用@插入的日期emoji和task插件的emoji不一样，这也会导致无法正确识别。左边是调用“Thino：插入任务”指令创建的，右边是@创建的，两者不一样。
![image](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/cc777394-302f-49c7-bf90-e11b0752f6ef)
