### ISSUE TITLE
Feature Request: md语法识别不全

### ISSUE THREAD

**Issue by lzz66** [Quorafind/Obsidian-Thino#533]
### Feature Requested | 请求的功能

能有效自动识别[]()的超链接语法，特别是()里面的文字，要以一个整体的形式进行识别，这个显示问题一直存在，所以现在提出。如图所示
![PixPin_2024-04-14_00-44-24](https://github.com/Quorafind/Obsidian-Thino/assets/47048565/a6eea63d-ef47-4252-b7f3-e417a73fb24f)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
右侧切换成渲染模式下能正常显示吗？

**Comment by lzz66** [comment]
> 右侧切换成渲染模式下能正常显示吗？

右侧单文件下”阅读模式“和”源码模式“都不能正常显示，thino的显示和右侧单文件下”阅读模式“下是一样的，都不会识别完整[]()后的()内的内容。
![PixPin_2024-04-14_10-18-17](https://github.com/Quorafind/Obsidian-Thino/assets/47048565/22841e34-0073-43b3-a2e3-534738095e11)

**Comment by Quorafind** [comment]
那这里是 Ob 的渲染器的问题，Thino 目前使用的渲染器是 Ob 的渲染器。可以等待 Ob 那边修复，或者你可以在 `(url)` 中的 url 的两侧加上 `<>` 使其变成： `(<url>)` 这个能让渲染器正常运作

**Comment by lzz66** [comment]
many thanks

> 那这里是 Ob 的渲染器的问题，Thino 目前使用的渲染器是 Ob 的渲染器。可以等待 Ob 那边修复，或者你可以在 `(url)` 中的 url 的两侧加上 `<>` 使其变成： `(<url>)` 这个能让渲染器正常运作

多谢~
