### ISSUE TITLE
Feature Request: 默认分享模板可以设置为：简洁么？或者保存上一次分享的模板

### ISSUE THREAD

**Issue by weqoocu** [Quorafind/Obsidian-Thino#534]
### Feature Requested | 请求的功能

目前每一次分享都要选择一下，不喜欢目前的默认模板
<img width="495" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/35360006/ccbb8a7e-ef0a-4554-a6aa-c5355c8e6354">

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已经支持
