### ISSUE TITLE
[Bug]: 自定义背景无法正常显示

### ISSUE THREAD

**Issue by liujunfeng1998** [Quorafind/Obsidian-Thino#537]
### Bug Description | BUG 描述

自定义背景会因为两边同时存在边栏而消失，只能在显示一侧边栏，或者没有边栏的时候中间才能有背景

### Relevant Screenshot | 相关截图

<img width="1512" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/87808990/ab635797-f861-4627-98da-d4716f31e9df">
<img width="1512" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/87808990/de8a1a98-a639-4773-bc5b-7cf8134f2400">
<img width="1512" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/87808990/949848ea-9ff1-47b5-af6b-c54cf8dee9ad">

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
如果是主题问题的话，可以去对应的主题提 issue。例如 [blue](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/issues)
