### ISSUE TITLE
[Bug]: 重新打开插件后或者刷新后所作笔记消失&提交功能需求

### ISSUE THREAD

**Issue by FeiLZX3Km** [Quorafind/Obsidian-Thino#538]
### Bug Description | BUG 描述

重新打开插件后或者刷新后所作笔记消失，如下图。

功能需求：
在插件个人昵称后的三个点菜单中提供一个入口，展示内容为：一、当前插件的版本号；二、github的项目地址。不然用户找起来问题反馈入口与提交问题会极为麻烦。

### Obsidian Version | Obsidian 版本

2.4.24

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
是第一个创建的 Thino 吗

**Comment by FeiLZX3Km** [comment]
已通过回退1.9.7版本解决问题。

**Comment by juestchaos** [comment]
你的图片没有上传上来，需要再看下
