### ISSUE TITLE
Thino 侧边栏增加隐藏开关

### ISSUE THREAD

**Issue by SrSh-notme** [Quorafind/Obsidian-Thino#540]
### Feature Requested | 请求的功能

在整理卡片有的时候不是很需要侧边栏，为了能看到更多的信息和卡片，可否增加个隐藏开关。谢谢

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by juestchaos** [comment]
你是指如果用窄界面，或者 经典视图。在一定宽度下，thino 会自动隐藏侧边栏

**Comment by SrSh-notme** [comment]
> 你是指如果用窄界面，或者 经典视图。在一定宽度下，thino 会自动隐藏侧边栏

我希望在更大的宽度下 或者瀑布流模式下也能隐藏 侧边栏，只聚焦再中间的内容

**Comment by Quorafind** [comment]
已支持，命令行启动或关闭
