### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by JeffreyGH10** [Quorafind/Obsidian-Thino#541]
### Feature Requested | 请求的功能

**功能需求：希望增加“回收站”「批量处理」的功能，可以批量对文件进行删除/恢复的处理等。**
当“回收站”里的内容越来越多之后，目前每次删除/还原都需要一条一条的进行，很麻烦效率也很低，希望为“回收站”开发「批量处理」功能，用户可以定期回溯“回收站”的内容进行批量处理，谢谢。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已支持
