### ISSUE TITLE
[Bug]: 每次第一次打开thino日历的热力图都失效，以前不会的

### ISSUE THREAD

**Issue by lzz66** [Quorafind/Obsidian-Thino#542]
### Bug Description | BUG 描述

现在打开日历的热力图什么都没有，左右翻页后才有显示，以前的版本不会，近几个版本才出现的问题
![image](https://github.com/Quorafind/Obsidian-Thino/assets/47048565/23b09e24-9054-4011-95a5-e50e6a79ca39)

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复
