### ISSUE TITLE
[Bug]: 输入框和插件“Editing Toolbar版本: 2.4.15作者: Cuman”不兼容，遮挡正常文字输入

### ISSUE THREAD

**Issue by honghongnana** [Quorafind/Obsidian-Thino#543]
### Bug Description | BUG 描述

如图所示，该插件和ob其他功能以及页面都兼容正常，但是在升级后的thino中，连最基本的输入都被遮挡

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/167398128/3ba0c777-10af-4368-b506-47dd5a8b5f71)

### Obsidian Version | Obsidian 版本

1.5.8

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by cumany** [comment]
editing toolbar 是新版吗

**Comment by honghongnana** [comment]
我用的是obsidian nord，刚刚试了一下换回默认主题，这个样子依然存在，我再试试把其他插件都关掉看看

**Comment by honghongnana** [comment]
我把第三方插件都依次关闭了一次，这个问题依然存在，我也把editing toolbar里的附加方法和位置选项都选了一遍，只要选择fixed就还是这样。附上我打开的所有第三方。
![Snipaste_2024-04-22_14-02-04](https://github.com/Quorafind/Obsidian-Thino/assets/167398128/e725fbb4-954d-48b1-8137-134a908163a6)
笔记本是13寸，系统是家庭版11

**Comment by Quorafind** [comment]
你可以开一个空白库测试仅安装 Thino 以及 editing toolbar 是否有类似的情况

**Comment by Quorafind** [comment]
你关插件后 用命令 `重新加载 Obsidian` 再测试，因为部分插件卸载后不一定会将数据清掉，如果只有几个插件的话很容易就能排查到问题插件

**Comment by honghongnana** [comment]
> 你关插件后 用命令 `重新加载 Obsidian` 再测试，因为部分插件卸载后不一定会将数据清掉，如果只有几个插件的话很容易就能排查到问题插件

这个我试过了，我把所有插件都关闭，只保留这两个插件，然后点击了那个重新加载，又关掉软件，再重新打开软件，还是这样。但是新库里确实都正常，好奇怪啊

**Comment by Quorafind** [comment]
有可能是样式片段影响

**Comment by honghongnana** [comment]
那有什么办法能解决呢，我如果删掉所有插件，重新装一次呢，之前写的memo会丢吗

**Comment by Quorafind** [comment]
样式片段影响的话，你可以看下主题和外观的相关设置
