### ISSUE TITLE
Feature Request: 希望能实现编辑和预览显示内容一致

### ISSUE THREAD

**Issue by xiaomingyu-git** [Quorafind/Obsidian-Thino#545]
### Feature Requested | 请求的功能

thino 编辑和实际显示的内容不一致，不同类型间有预计不到的空格。
希望能实现编辑和预览显示内容一致

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/44595719/8e5212de-756e-4b83-b27e-86ad3a2bbfaa)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
已修复
