### ISSUE TITLE
[Bug]: 折叠最大高度无法设置为0

### ISSUE THREAD

**Issue by xyy-1997** [Quorafind/Obsidian-Thino#547]
### Bug Description | BUG 描述

在设置中修改折叠最大高度后想要重置为0，但是修改后会自动恢复到上一次设置的非0值。

并且折叠后的显示高度不够，只能显示两排内容，开头添加标签和引用之后基本看不到卡片内容，建议增加折叠后显示高度的设置选项。

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/a9fc8dd1-a72b-44b6-aabe-b566ed55de44)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/d9521e5f-20be-406e-937f-672e9816faf2)

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
已修复
