### ISSUE TITLE
Feature Request: 移除激活

### ISSUE THREAD

**Issue by Tobeprmn** [Quorafind/Obsidian-Thino#548]
### Feature Requested | 请求的功能

请问手机端可以像电脑上一样移除激活吗？

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
经过测试，移动端可以移除激活，你可以用默认主题测试。注意，目前不支持注销某一设备的激活。
