### ISSUE TITLE
[BUG]: Task with number prefix cannot be toggled

### ISSUE THREAD

**Issue by MTL321** [Quorafind/Obsidian-Thino#549]
### Bug Description | BUG 描述

待办无法在普通视图中勾选

### Relevant Screenshot | 相关截图

https://github.com/Quorafind/Obsidian-Thino/assets/95291956/2eedd424-8396-4069-a50f-b4c22bc02a09

### Obsidian Version | Obsidian 版本

ob 1.4.16（114）

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
请更新版本后复测

**Comment by MTL321** [comment]
版本已更新，问题还是存在。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月20日(周六) 晚上10:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Quorafind/Obsidian-Thino] BUG:待办无法在普通视图中勾选 (Issue #549)




 
请更新版本后复测

**Comment by Quorafind** [comment]
已经经过移动端以及桌面库的空白库测试，均无法复现。

**Comment by Quorafind** [comment]
确定了，限定条件是包含数字前置的任务复选框存在无法勾选的情况

**Comment by Quorafind** [comment]
更新后已修复
