### ISSUE TITLE
[Bug]: 当日记还未创建的时候，输入当天的第一条thino，输入的thino会消失。

### ISSUE THREAD

**Issue by wopanda** [Quorafind/Obsidian-Thino#556]
### Bug Description | BUG 描述

输入的第一条thino会消失，但是有成功创建出日记，而后再输入，都是正常的。

### Obsidian Version | Obsidian 版本

v1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
是否有使用任何模板插件

**Comment by yifoo** [comment]
我也有这种情况，好多条memo在thino上都不显示

**Comment by Quorafind** [comment]
> 我也有这种情况，好多条memo在thino上都不显示

是否使用任何模板插件？

**Comment by wopanda** [comment]
> 是否有使用任何模板插件

有使用核心插件日记、Periodic Notes 的日记模板。

**Comment by Quorafind** [comment]
> > 是否有使用任何模板插件
> 
> 有使用核心插件日记、Periodic Notes 的日记模板。

Periodic notes 会在文件创建后再覆盖内容吗？如果会的话，是这个插件导致的

**Comment by Quorafind** [comment]
请更新后测试。

**Comment by Quorafind** [comment]
暂时无法复现
