### ISSUE TITLE
[Bug]: 切换标签后，列表内容不再显示

### ISSUE THREAD

**Issue by zephyrleaves** [Quorafind/Obsidian-Thino#559]
### Bug Description | BUG 描述

进行切换标签后，列表内容不再显示

### Relevant Screenshot | 相关截图

<img width="520" alt="iShot_2024-04-21_14 48 42" src="https://github.com/Quorafind/Obsidian-Thino/assets/363180/d4ac585c-b795-47cc-9d91-9250afb4c9d0">

### To Reproduce | 重现问题

1. 打开thino
2. 选择一个标签
3. 列表内容小时

### Obsidian Version | Obsidian 版本

Version 1.5.12 (Installer 1.4.13)

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by zephyrleaves** [comment]
已经明确是在更新2.4.27 后出现这个问题，在回退到2.4.26后问题解决。
应该是折叠功能的问题

**Comment by zephyrleaves** [comment]
<img width="266" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/363180/bcdead22-c0f3-4f00-b8d5-8443de0a06b9">

打开或关闭 Thino会显示这个错误

**Comment by zephyrleaves** [comment]
<img width="542" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/363180/646bdb7c-1c87-48a0-bfda-c6436b339dfe">
点击标签的时候会有这个错误堆栈

**Comment by Quorafind** [comment]
> <img alt="image" width="542" src="https://private-user-images.githubusercontent.com/363180/324229680-646bdb7c-1c87-48a0-bfda-c6436b339dfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODQ0MTUsIm5iZiI6MTcxMzY4NDExNSwicGF0aCI6Ii8zNjMxODAvMzI0MjI5NjgwLTY0NmJkYjdjLTFjODctNDhhMC1iZmRhLWM2NDM2YjMzOWRmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNzIxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmFiN2MwMWE1Yjk2ZTdkNmUwNjQ2YzVmMDFkODQ5YzVjNWFlMzAzN2U2ZTQyODc1ZTNlNWFhNDU5OTdhOGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.psx-RY3l8NA7PJklvzBSNS6WWu3q9zbLm4hlzQbbmf0"> 点击标签的时候会有这个错误堆栈

请升级你的 Obsidian canvas mindmap 插件。

**Comment by zephyrleaves** [comment]
> > <img alt="image" width="542" src="https://private-user-images.githubusercontent.com/363180/324229680-646bdb7c-1c87-48a0-bfda-c6436b339dfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODQ0MTUsIm5iZiI6MTcxMzY4NDExNSwicGF0aCI6Ii8zNjMxODAvMzI0MjI5NjgwLTY0NmJkYjdjLTFjODctNDhhMC1iZmRhLWM2NDM2YjMzOWRmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNzIxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmFiN2MwMWE1Yjk2ZTdkNmUwNjQ2YzVmMDFkODQ5YzVjNWFlMzAzN2U2ZTQyODc1ZTNlNWFhNDU5OTdhOGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.psx-RY3l8NA7PJklvzBSNS6WWu3q9zbLm4hlzQbbmf0"> 点击标签的时候会有这个错误堆栈
> 
> 请升级你的 Obsidian canvas mindmap 插件。

好的，升级到0.1.11解决了，谢谢
