### ISSUE TITLE
[Bug]: 新建 thino 失败

### ISSUE THREAD

**Issue by huangduzhang** [Quorafind/Obsidian-Thino#562]
### Bug Description | BUG 描述

macos环境下，更新到插件的最新版本之后，新建一条 thino，点击刷新或者重新打开 thino，新建的 thino 丢失了。

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
#556 是否和其中的一样，使用了 Periodic notes 或者 Templater 插件

**Comment by huangduzhang** [comment]
> #556 是否和其中的一样，使用了 Periodic notes 或者 Templater 插件

是，这两个插件都有

**Comment by Quorafind** [comment]
请备份今天已经写过的 Thino ，更新最新版本测试一次看看

**Comment by Quorafind** [comment]
暂时无法复现
