### ISSUE TITLE
[Bug]: 移动端标签筛选和搜索时卡片内容不显示

### ISSUE THREAD

**Issue by xyy-1997** [Quorafind/Obsidian-Thino#563]
### Bug Description | BUG 描述

安卓移动端使用标签或者搜索进行筛选后，卡片排列出来了，但是不显示内容。之前Windows端也有同样的问题，新版本应该是修复了。

### Relevant Screenshot | 相关截图

![275c7333e66bbd8e6b80f4ae8628a87](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/f65ef26b-0291-437a-a281-472d3b1ebd6a)

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
更新 canvas mindmap 插件

**Comment by Quorafind** [comment]
然后检查是否是折叠高度设置过小导致出现异常，可以测试设置回为0来检查是否是因为设置导致的问题

**Comment by xyy-1997** [comment]
> 然后检查是否是折叠高度设置过小导致出现异常，可以测试设置回为0来检查是否是因为设置导致的问题

折叠高度是0，canvas mindmap也是最新版。但是我现在什么都没干，它自己好了
