### ISSUE TITLE
希望移动端将输入框改为一个点击可展开输入框的悬浮按钮，类似 flomo

### ISSUE THREAD

**Issue by Fishygoddy** [Quorafind/Obsidian-Thino#564]
### Feature Requested | 请求的功能

如题。
有这个想法的原因是 obsidian 移动端的界面实在太繁重了，顶栏、底栏，再加上一个不小的输入框，剩下有效显示区域太小了，跟 thino 标志性的「轻量快捷输入」有些不搭。希望能就此加以优化。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
这是一个很早的设置：

Thino 设置=》界面设置=》编辑器设置在底部=》使用按钮唤出编辑器

**Comment by Fishygoddy** [comment]
> 这是一个很早的设置：
> 
> Thino 设置=》界面设置=》编辑器设置在底部=》使用按钮唤出编辑器

不好意思之前居然一直没发现……没有意义的 issue +1……

刚试了下，这样的确可以实现底部加号按钮，但还有个问题是呼出之后无法方便地再将输入框 collapse 回去，这个可否再优化下呢，比如点击输入框外区域就自动 collapse 回按钮的形态？

不管怎么说都感谢回复！

**Comment by Quorafind** [comment]
滚动列表后就会恢复。你可以更新一下，我两个小时前修了一个相关 bug
