### ISSUE TITLE
[Feature request] Source path display on card

### ISSUE THREAD

**Issue by Quorafind** [Quorafind/Obsidian-Thino#565]
相比于给每张 card 添加一个 title 标签，能否让Thino支持 单文件来源的卡片 显示文件名且支持基于文件名的筛选/过滤。 
前者有点污染标签列表了。
而后者除了索引 Zotero 笔记，应该对于其他单文件的用法都是有益的。

_Originally posted by @Steven-AA in https://github.com/Quorafind/Obsidian-Thino/discussions/561#discussioncomment-9184870_

**Comment by Fishygoddy** [comment]
十分赞同。
这样文献笔记、微信读书笔记就都没必要每条都加书目来源的标签了，可直接从文件名获知道来源。

**Comment by Quorafind** [comment]
已支持
