### ISSUE TITLE
[Bug]: 关于thino影响OB流畅度的问题

### ISSUE THREAD

**Issue by Morganwan90** [Quorafind/Obsidian-Thino#567]
### Bug Description | BUG 描述

thino的功能非常强大。但是在我的使用中，启用thino会很大的影响我OB的流畅度。
主要是在一些很多文档的文件夹，或者较长的文档中会出现。
注：我并没有打开同步功能，仅激活状态下。
这种延迟是只要启动了thino插件就会出现，禁止后就恢复，而不是需要打开thino界面才出现。

这里举  文档属性 和文件列表 两个例子：

## 文档属性

当我没有打开thino时，打开文档时，文档属性可以很快显示出来，当我启用thino后，每个文档的文档属性会延迟很久才出现。
![列表属性](https://github.com/Quorafind/Obsidian-Thino/assets/61633409/37924ae6-8ed7-4d92-8a3a-6ebb090fb404)

## 文件列表

当我在没有打开thino时，文档列表打开是比较流畅的，当我启用thino后，在我开关一些拥有很多文档的文件夹时，出现明显卡顿，这个示例并不明显，但其实我在实际使用中感知比较强。
![文件列表](https://github.com/Quorafind/Obsidian-Thino/assets/61633409/52d1603a-a924-4420-a4d6-bf8fffe5c387)

明显的卡顿比较影响我的使用，尤其是当我并没有实际使用thino就会影响到我正常使用OB。

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
麻烦您这边测试在开启 Thino 的情况下，按以下步骤录制，并且查看 bottom-up 调用树：

![image](https://github.com/Quorafind/Obsidian-Thino/assets/13215013/0fa8ba52-d30d-4df9-9da3-9adc0d5a7e01)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/13215013/7ed89aa5-1e9a-4bec-95fb-282f63e66c4b)

这个能更好让你查看是否是 Thino 影响；如果是的话，最好具体到具体那一片代码导致的，第二张图的右下角的右侧都是可以点击查看对应的源码的

**Comment by Morganwan90** [comment]
附件如图，我没有什么编程能力，还辛苦您看下。

1. 仅关闭再开启thino

[仅关闭再开启thino.json](https://github.com/Quorafind/Obsidian-Thino/files/15075085/thino.json)

![仅关闭再开启thino](https://github.com/Quorafind/Obsidian-Thino/assets/61633409/b869468e-861c-4873-881a-5630c0acf093)

2.关开thino+文件夹文档切换

[关开thino+文件夹文档切换.json](https://github.com/Quorafind/Obsidian-Thino/files/15075088/thino%2B.json)

![关开thino+文件夹文档切换](https://github.com/Quorafind/Obsidian-Thino/assets/61633409/27c045b7-b745-4498-8580-bd1129ac0cda)

**Comment by Morganwan90** [comment]
尝试了一下，发现应该是metamenu导致的冲突，我暂时卸载了metamenu正常了。

**Comment by Morganwan90** [comment]
我最后经过2天的排查...
发现是一个分栏CSS【MCL Multi Column】导致的。
只要thino和这个snippets下的CSS同时打开，就会出现文件夹打开关闭卡顿、thino输入卡顿等情况。
关闭其中任何一个并且重启可以恢复流畅。
虽然我不太理解为什么会出现这种情况，但是似乎该插件的其他人也出现了类似的问题：[Seems to have serious performance issues](https://github.com/efemkay/obsidian-modular-css-layout/issues/67)。
update一下，以防其他人也有类似的问题。
