### ISSUE TITLE
Feature Request: 限制每条记录的格子的长度

### ISSUE THREAD

**Issue by RogerProSelf** [Quorafind/Obsidian-Thino#569]
### Feature Requested | 请求的功能

目前对于比较长的单条记录来说，Thino将内容全部显示会有些挤占空间，导致页面上展示不了几条，希望能加入一个限制单条显示长度的功能，谢谢！

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
设置=>界面=>折叠高度
