### ISSUE TITLE
[Bug]: web同步下出现重复输入

### ISSUE THREAD

**Issue by Morganwan90** [Quorafind/Obsidian-Thino#570]
## 背景

OB官方同步和thino web同时开启

### OB官方同步设置，排除了thino单文件所在文件夹

![image](https://github.com/Quorafind/Obsidian-Thino/assets/61633409/6ec8c488-f5bd-4bdf-825c-c5fbccd99c3b)

### thino 的同步和保存均为单文件

![image](https://github.com/Quorafind/Obsidian-Thino/assets/61633409/236f035a-1a8e-4653-bd72-b54459c6bf30)

## 出现的问题

当我在thino输入文字后，点击同步，会同步出重复内容

![PixPin_20240423232326](https://github.com/Quorafind/Obsidian-Thino/assets/61633409/6f0e02c7-d18a-4c4d-8e75-b594aad6f858)

请问是我设置上出现了问题么

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
查看是否有同样的 ID

**Comment by Morganwan90** [comment]
同样id是指同时登陆了两个么？
我在一个同一个电脑下的空仓库测试过thino。我刚已将空仓库的thino移除了同步和取消激活，问题依旧。

出现的id情况如图：
![image](https://github.com/Quorafind/Obsidian-Thino/assets/61633409/fa3729ca-a1f5-47cc-af70-991eda97429c)

**Comment by Quorafind** [comment]
我研究下，因为其中一个没有 webid，一个有 webid，估计是出现了同步的时候没找到 id 的情况

**Comment by Morganwan90** [comment]
好的好的，之前好像是没有这个情况的...不知道是不是我前几天在一个空仓库下载了thino，激活和同步了同样一个账号导致的...

**Comment by Morganwan90** [comment]
@Quorafind 我把原来空仓库测试的thino删除，使用的仓库的thino的同步和激活取消，卸载thino，重新安装、激活以及链接后恢复了正常。

**Comment by Morganwan90** [comment]
updated一下...我把thino重置，取消了激活和同步，卸载，再重装。
好像现在好了，但是有时候似乎还是会出现重复情况。。。

**Comment by Morganwan90** [comment]
updated...又开始了...每次弄完都会生成一个一样的...

**Comment by Quorafind** [comment]
> updated...又开始了...每次弄完都会生成一个一样的...救命阿... 另外，我试了将OB官方同步关闭，问题仍然出现...感觉是只有我的thino出了问题么... ![PixPin_20240425232451](https://private-user-images.githubusercontent.com/61633409/325672278-661735ea-10f2-433b-96f1-94bbd195bd8d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTk4MDYsIm5iZiI6MTcxNDA1OTUwNiwicGF0aCI6Ii82MTYzMzQwOS8zMjU2NzIyNzgtNjYxNzM1ZWEtMTBmMi00MzNiLTk2ZjEtOTRiYmQxOTViZDhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1MzgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYTE4ODUyMjc2NTAzNDNkM2E0YzJhNzdmMDRmODI5NTQ5M2QzMzRkNTU2MWQ1OTZmN2E1Njg0NDk5NDE0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uaDe0nolDmNJ7vgfqc0ekMcu1BsGUTfz9wOXDSp4R1A) [ ](https://private-user-images.githubusercontent.com/61633409/325672278-661735ea-10f2-433b-96f1-94bbd195bd8d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTk4MDYsIm5iZiI6MTcxNDA1OTUwNiwicGF0aCI6Ii82MTYzMzQwOS8zMjU2NzIyNzgtNjYxNzM1ZWEtMTBmMi00MzNiLTk2ZjEtOTRiYmQxOTViZDhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1MzgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYTE4ODUyMjc2NTAzNDNkM2E0YzJhNzdmMDRmODI5NTQ5M2QzMzRkNTU2MWQ1OTZmN2E1Njg0NDk5NDE0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uaDe0nolDmNJ7vgfqc0ekMcu1BsGUTfz9wOXDSp4R1A) ![PixPin_20240425232451](https://private-user-images.githubusercontent.com/61633409/325672278-661735ea-10f2-433b-96f1-94bbd195bd8d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTk4MDYsIm5iZiI6MTcxNDA1OTUwNiwicGF0aCI6Ii82MTYzMzQwOS8zMjU2NzIyNzgtNjYxNzM1ZWEtMTBmMi00MzNiLTk2ZjEtOTRiYmQxOTViZDhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1MzgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYTE4ODUyMjc2NTAzNDNkM2E0YzJhNzdmMDRmODI5NTQ5M2QzMzRkNTU2MWQ1OTZmN2E1Njg0NDk5NDE0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uaDe0nolDmNJ7vgfqc0ekMcu1BsGUTfz9wOXDSp4R1A) [ ](https://private-user-images.githubusercontent.com/61633409/325672278-661735ea-10f2-433b-96f1-94bbd195bd8d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTk4MDYsIm5iZiI6MTcxNDA1OTUwNiwicGF0aCI6Ii82MTYzMzQwOS8zMjU2NzIyNzgtNjYxNzM1ZWEtMTBmMi00MzNiLTk2ZjEtOTRiYmQxOTViZDhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1MzgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYTE4ODUyMjc2NTAzNDNkM2E0YzJhNzdmMDRmODI5NTQ5M2QzMzRkNTU2MWQ1OTZmN2E1Njg0NDk5NDE0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uaDe0nolDmNJ7vgfqc0ekMcu1BsGUTfz9wOXDSp4R1A)

已经定位到原因，你暂时将保存为单文件修改成保存为日记文件即可解决。

**Comment by Morganwan90** [comment]
可以了，但是保存类型目前只开启日记才行。
如果类型中日记和单文件都开启了，尽管选择默认类型为日记，仍会出现重复。
只开启日记是正常的，感谢！

**Comment by Quorafind** [comment]
劳烦复测下

**Comment by juestchaos** [comment]
我服测量下，目前看是正常的

**Comment by Morganwan90** [comment]
已完美解决！
