### ISSUE TITLE
[Bug]: 标准Markdown格式下图片显示不全

### ISSUE THREAD

**Issue by xyy-1997** [Quorafind/Obsidian-Thino#573]
### Bug Description | BUG 描述

- 使用Wiki形式链接插入图片时显示正常
![image](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/888e2db2-90f7-4bab-8d7d-a1915ec55502)

- 使用标准Markdown格式时图片显示不全并且变小
![image](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/699837e3-0fcb-4822-a207-9e971009b46a)

- PC端有这个问题，安卓端长方形图片始终显示不全

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
跟语法无关，才用这种类朋友圈的比例尺寸，是之前部分用户提交的需求
建议在讨论多图排列尺寸上，有相关需求的用户线讨论下

**Comment by Quorafind** [comment]
下一个版本修复。css 影响
