### ISSUE TITLE
[Bug]: 和CardBoard插件冲突，造成显示问题

### ISSUE THREAD

**Issue by xyy-1997** [Quorafind/Obsidian-Thino#574]
### Bug Description | BUG 描述

# 同时使用Thino和Cardboard插件时，有概率导致两者同时出现显示问题
- Thino问题：部分卡片不显示，有时是最顶端，有时是最顶部的
- PC和安卓都出现过这个问题，特别是在搜索或者便签筛选的时候
![image](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/cf88917c-e77f-422f-bd48-8e46df187bf3)
- Cardboard问题：无法显示插件内容，并且有几率自动关闭插件
![image](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/c90d0df8-6761-4bf0-8cdc-353f8b492bae)
- 中途出现过一次error提示，但是我没截图到，之后有机会我补充上来。

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by xyy-1997** [comment]
- 补充error信息
![image](https://github.com/Quorafind/Obsidian-Thino/assets/56293318/9c624df7-69ce-488d-a6f7-c90666aa007d)

**Comment by xyy-1997** [comment]
关闭Cardboard插件后，使用标签晒训时仍然发生显示问题，最后只能禁用Thino后重新加载ob，再打开Thino才没问题。如果和Cardboard的兼容之后不打算做的话，我就把todo都改成Thino的格式，不然我还挺需要Cardboard的看板

**Comment by xyy-1997** [comment]
最新发现，禁用Cardboard插件后，使用标签筛选后，仍然发生显示问题。不知道是不是要彻底卸载Cardboard插件

**Comment by xyy-1997** [comment]
> 和 Cardboard 无关，更新 Canvas mindmap 插件 相关 issue：#559
> 
> 除非 Cardboard 有做出过 hack showPreview 函数的相关方法，否则的话，你甚至可以直接卸载 Canvas mindmap 一劳永逸

感谢，canvas mindmap更新到0.1.11没问题了。之前我在obsidian中检查更新canvas mindmap最新版本只有0.1.10，我以为我更新到最新版了。

**Comment by odayou** [comment]
> > 和 Cardboard 无关，更新 Canvas mindmap 插件 相关 issue：#559
> > 除非 Cardboard 有做出过 hack showPreview 函数的相关方法，否则的话，你甚至可以直接卸载 Canvas mindmap 一劳永逸
> 
> 感谢，canvas mindmap更新到0.1.11没问题了。之前我在obsidian中检查更新canvas mindmap最新版本只有0.1.10，我以为我更新到最新版了。

我也报相同的错误，加载文件失败，但是升级了canvas mindmap问题还在，尝试彻底卸载，并重装Thino，问题还在

**Comment by Quorafind** [comment]
@odayou 最简单的测试方法是卸载掉 canvas mindmap 插件测试一下，卸载后重启一次 ob

**Comment by odayou** [comment]
> @odayou 最简单的测试方法是卸载掉 canvas mindmap 插件测试一下，卸载后重启一次 ob

我尝试了，不行

**Comment by Quorafind** [comment]
@odayou 你可以试一下空白库，且仅安装 thino 的情况下是否还可不可以吗

**Comment by odayou** [comment]
> @odayou 你可以试一下空白库，且仅安装 thino 的情况下是否还可不可以吗

忽略我的问题吧，我纠正下，做了上述操作后，不报错了，但是点开筛选器列表还是展示为空，原因是thino只展示他自己创建的标签，虽然设置里勾选了"使用库内的所有标签"，可能是我不会用thino吧，

**Comment by Quorafind** [comment]
> > @odayou 你可以试一下空白库，且仅安装 thino 的情况下是否还可不可以吗
> 
> 忽略我的问题吧，我纠正下，做了上述操作后，不报错了，但是点开筛选器列表还是展示为空，原因是thino只展示他自己创建的标签，虽然设置里勾选了"使用库内的所有标签"，可能是我不会用thino吧，

筛选器启用后，也只会筛选带有该标签的 Thino，如果没有任何 Thino 应用过这个标签，这个筛选器也是无效的。。。可能这个我做得还不够明白。

启用库内的所有标签特指输入的时候的标签建议是来自库内的
