### ISSUE TITLE
[Bug]: 添加标签会默认给标签添加一个一级标题

### ISSUE THREAD

**Issue by DearTang** [Quorafind/Obsidian-Thino#576]
### Bug Description | BUG 描述

当前版本是2.4.33
Uploading QQ2024425-95348.mp4…

### To Reproduce | 重现问题

输入标签 #然后选中已有标签
然后在下面输入 - [ ] 
然后就上面的标签就多了 #  变成 # #xxxx

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
我测试过了，并没有这样问题
你需要提交下你使用了什么插件，可能是其他插件修改了你的输入导致的

**Comment by DearTang** [comment]
我测试过了，确实是插件导致的，在正常写文档的界面不会出现这个问题，但是通过thino会异常
插件名为：Number Heading 用于给多级标题自动生成序号
argustang
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年4月25日 ***@***.***>抄送人argus ***@***.***>,
***@***.***>主题Re: [Quorafind/Obsidian-Thino] [Bug]: 添加标签会默认给标签添加一个一级标题 (Issue #576)
我测试过了，并没有这样问题
你需要提交下你使用了什么插件，可能是其他插件修改了你的输入导致的

**Comment by juestchaos** [comment]
我试过了 number headings 也没有这个现象，可能跟你的配置有关
如果不介意，可以把这个配置告诉我

**Comment by DearTang** [comment]
是需要这个吗？还是其他的，我需要怎么提供
argustang
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年4月27日 ***@***.***>抄送人argus ***@***.***>,
***@***.***>主题Re: [Quorafind/Obsidian-Thino] [Bug]: 添加标签会默认给标签添加一个一级标题 (Issue #576)
我试过了 number headings 也没有这个现象，可能跟你的配置有关
如果不介意，可以把这个配置告诉我

**Comment by DearTang** [comment]
不知道是不是跟主题有关系，换了一个主题，今天写thino的时候又正常了
argustang
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年4月27日 ***@***.***>抄送人argus ***@***.***>,
***@***.***>主题Re: [Quorafind/Obsidian-Thino] [Bug]: 添加标签会默认给标签添加一个一级标题 (Issue #576)
我试过了 number headings 也没有这个现象，可能跟你的配置有关
如果不介意，可以把这个配置告诉我

**Comment by juestchaos** [comment]
请问你之前用的是哪个主题？

**Comment by DearTang** [comment]
一下子想不起来了，下载的主题有点多
argustang
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年4月28日 ***@***.***>抄送人argus ***@***.***>,
***@***.***>主题Re: [Quorafind/Obsidian-Thino] [Bug]: 添加标签会默认给标签添加一个一级标题 (Issue #576)
请问你之前用的是哪个主题？

**Comment by juestchaos** [comment]
你可以一次性，提供下你的主题和使用插进
但目前看起来是其他插件对 输入做了更改导致的
