### ISSUE TITLE
设备是Matepad Air 11.5，移动（平板端）端希望也能设置总是展示左侧栏

### ISSUE THREAD

**Issue by lixy1998** [Quorafind/Obsidian-Thino#589]
### Feature Requested | 请求的功能

设备是Matepad Air 11.5，最新版不能默认展示左侧栏，屏幕大小是足够的，希望移动（平板端）端希望也能设置总是展示左侧栏，现在移动端没有这个设置

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/56257410/e75dc882-8a30-4b4f-8a36-ef0786295a9f)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by juestchaos** [comment]
能否附带下截图

**Comment by lixy1998** [comment]
![Screenshot_20240501_125610_md obsidian_edit_739460282211949](https://github.com/Quorafind/Obsidian-Thino/assets/56257410/147e50de-3d53-4954-919f-45fb60047899)
![Screenshot_20240501_125541_md obsidian_edit_739439160676488](https://github.com/Quorafind/Obsidian-Thino/assets/56257410/2ab4b007-3fce-4b03-bc45-745562673af2)
![Screenshot_20240501_130245_md obsidian_edit_739775990383495](https://github.com/Quorafind/Obsidian-Thino/assets/56257410/aa35d832-1f7f-43fc-b104-df1da9ae6640)
显示侧边栏的话，Thino侧边栏显示不了。

**Comment by Quorafind** [comment]
已支持
