### ISSUE TITLE
[Bug]: Thino 编辑器中选中文本时加粗等格式化文本菜单无效

### ISSUE THREAD

**Issue by Yaozhuwa** [Quorafind/Obsidian-Thino#591]
### Bug Description | BUG 描述

Thino 编辑器中选中文本时加粗等格式化文本菜单无效

### Relevant Screenshot | 相关截图

![iShot_2024-04-29_15 08 51](https://github.com/Quorafind/Obsidian-Thino/assets/28787183/a970da10-daa5-4d23-87c6-c639702a7cf2)

### Obsidian Version | Obsidian 版本

1.5.12 MacOS M1 pro

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
补充，我试过 win + 2.4.33
无法复现这个问题，保存，和在编辑框内加错都是正常的。
可能跟mac有关， 或者看看是否有控制台报错

**Comment by Yaozhuwa** [comment]
我关闭了所有其他插件，悬浮菜单有效了，应该是插件冲突了，我排查下~

**Comment by Yaozhuwa** [comment]
经过测试：与 https://github.com/pjeby/pane-relief  冲突了~

**Comment by juestchaos** [comment]
- [[pane-relief]] 冲突：目前判断是 Pane Relief 的问题，你可以选择使用一些插件，来延迟启动，保证 Panel Relief 插件晚于 Thino 启动即可。
