### ISSUE TITLE
Requirements for closed-source plugins are not met

### ISSUE THREAD

**Issue by joethei** [Quorafind/Obsidian-Thino#594]
Hi @Quorafind,

The license of this plugin has changed to closed-source without notifying Obsidian.
Per the [Obsidian Developer Policies](https://docs.obsidian.md/Developer+policies), closed source plugins require case-by-case approval.

There are a few requirements for closed-source plugins to be allowed in the community directory:

- Add the text "(Closed source)" to the end of the plugin description.
- Provide the Obsidian team with access to the source code. You can do this by giving me access to the repo.

If these requirements are not met within 30 days, this plugin will be removed from the community directory.

Thanks,
— The Obsidian team

**Comment by Quorafind** [comment]
Finished. You can access to the code now.

**Comment by Quorafind** [comment]
And push a new update 2.3.34, now if people update the plugin should update their plugin's description.  Btw, I push a patch for the description for Obsidian-memos(thino): https://github.com/obsidianmd/obsidian-releases/pull/3452

**Comment by joethei** [comment]
Thanks for the quick reaction.
