### ISSUE TITLE
Unique attachments compatibility

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Thino#6]
Unique Attachments (https://github.com/derwish-pro/obsidian-unique-attachments) allows you to have more order with the images in Obsidian.

No plugin - ![](Pasted%20Image%2020220105091215.png)

With plugin - ![](images/20220105091245.png)

When using images in Memos does not work the plugin.
Can you make it compatible?

Thanks

**Comment by Quorafind** [comment]
Should go to find out what happened

**Comment by Quorafind** [comment]
Now this should be fixed with latest version.
