### ISSUE TITLE
[FR] : Hope to add more heat map colors

### ISSUE THREAD

**Issue by i-iooi-i** [Quorafind/Obsidian-Thino#611]
### Feature Requested | 请求的功能

希望可以增加更多的热力图配色，比如 黄色系，以及黑曜石默认主题的紫色系，现在冷色系偏多，暖色系偏少。

- 或许，可以考虑直接调用用户当前使用的主题的高亮色系。
- 或者，是否考虑直接使用调色盘工具，让用户自己决定要使用的高亮颜色呢。

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/1827701/26313fbe-f1c3-47e2-aaaf-9c76b5791dcb)

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by juestchaos** [comment]
已经有人提供了类似的方法，可以自己来DIY
[PKMer_Obsidian 样式：给 Thino 搭配 10 种热力图颜色]( https://pkmer.cn/show/20231111004457 )

**Comment by i-iooi-i** [comment]
> 已经有人提供了类似的方法，可以自己来DIY [PKMer_Obsidian 样式：给 Thino 搭配 10 种热力图颜色](https://pkmer.cn/show/20231111004457)

非常感谢，Pkmer 提供的这几组配色👍👍👍
