### ISSUE TITLE
[Bug]: In light mode, the background color cannot match the theme color.

### ISSUE THREAD

**Issue by i-iooi-i** [Quorafind/Obsidian-Thino#613]
### Bug Description | BUG 描述

测试了一下，在亮模式主题下，使用 “Modern” 界面。
切换默认主题以及一些第三方主题，背景色都无法与主题很好的适配，默认始终是青蓝色，
跟大部分主题搭配显得不协调，缺乏美观度。

Classic 界面兼容性很好，似乎没有此类问题。
![image](https://github.com/Quorafind/Obsidian-Thino/assets/1827701/1af979a3-abaf-4292-aa25-16fcc2ee944c)

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/1827701/e6448291-f9d6-4fbe-bbf7-ae6ecb686373)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/1827701/35d06c20-3388-46cc-9d73-6da8f3cf6471)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/1827701/2a1669a6-5823-45e7-8fd8-d7b09140962e)

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
classic 主题被很多主题主动兼容过，但是 morden 主题才出来不久，很多主题还跟不上
另外如果你对外观有要求过，可以尝试自行添加 snippets
