### ISSUE TITLE
[Bug]: Modern has problems with third-party theme adaptation

### ISSUE THREAD

**Issue by i-iooi-i** [Quorafind/Obsidian-Thino#617]
### Bug Description | BUG 描述

![image](https://github.com/Quorafind/Obsidian-Thino/assets/1827701/7321dbdb-665b-4f6a-bc5c-65581e389d21)

当隐藏标题栏以后，Modern 界面的边角为90°的硬转折，没有适配主题的圆角设计。

![image](https://github.com/Quorafind/Obsidian-Thino/assets/1827701/e76b7616-ea8a-4ae2-ba6f-58da9468e8d2)

使用 Classic 界面，适配的就很好，没有此类问题。

### To Reproduce | 重现问题

![image](https://github.com/Quorafind/Obsidian-Thino/assets/1827701/b4358434-1c81-40a0-8411-36469979b0c2)
启用第三方主题
![image](https://github.com/Quorafind/Obsidian-Thino/assets/1827701/ddf53a8d-6406-455f-9a90-4b29d62091af)
并且在 Style Settings 里开启 隐藏浮动标题栏

即可复现此问题。

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
一般情况下是主题去兼容插件
因为主题会不停变动，插件没办法去适配主题的每个版本，只能有限检查一些量级比较大的版本
一般这种情况，可以通过 snippets 解决，或者在主题作者issue 提议适配
已经有一些主题和插件作者开始主动适配 thino 了
