### ISSUE TITLE
[Bug]: 某些单个文件组成的thino条目无法achive的问题

### ISSUE THREAD

**Issue by lzz66** [Quorafind/Obsidian-Thino#618]
### Bug Description | BUG 描述

在某些单文件md文件上的thino条目上点击achive无效，刷新后还是会显示到thino列表里面
内容如下，可测试

---
tags: 
原文链接: "https://mp.weixin.qq.com/s/HNjFw56nsmR0DRCNwQ1epg"
五彩链接: "https://marker.dotalk.cn/#/?noteidx=H8CCB5M"
创建时间: 2024-05-17 11:39
更新时间: 2024-05-17 11:40
tags: ["thino/file"]

---

## 页面笔记

> [!thino] 2024/05/17 11:40:21 %% [id::H8CCB5M] [thinoType::JOURNAL] %%
> 八段锦真不错呀！ [老祖宗的锻炼真的有用！还能生发！](https://mp.weixin.qq.com/s/HNjFw56nsmR0DRCNwQ1epg)
>

![image](https://github.com/Quorafind/Obsidian-Thino/assets/47048565/48660472-3688-4810-8c4a-3c02cba4988b)

### Obsidian Version | Obsidian 版本

0.13.19

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
我没有复现你的情况，但是从你的截图中可以看到，你同样的内容你既有单文件，也有多文件模式存储，请检查下是否由使用了混合同步导致的

**Comment by lzz66** [comment]
> 我没有复现你的情况，但是从你的截图中可以看到，你同样的内容你既有单文件，也有多文件模式存储，请检查下是否由使用了混合同步导致的

我没有开多文件模式啊
![image](https://github.com/Quorafind/Obsidian-Thino/assets/47048565/d8ab7233-b08f-4e45-a8b4-e9f8de37d180)
