### ISSUE TITLE
[FR]: Use ctrl+e to save thino

### ISSUE THREAD

**Issue by JJcdomat** [Quorafind/Obsidian-Thino#619]
### Feature Requested | 请求的功能

日常使用ob时，写完了就ctrl+e切换模式，也算是一种保存。能否在thino同步这个操作。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by juestchaos** [comment]
切换视图是 Obsidian 的快捷键的操作，你是说需要 thino 监听这个操作嘛？
你描述的是操作方式，那么实际使用这个场景是什么？

**Comment by JJcdomat** [comment]
测试了下，好像ob不能同时处理两个冲突快捷键…用ahk取个巧算了。
