### ISSUE TITLE
好久没用升级完却不能用

### ISSUE THREAD

**Issue by zhl111** [Quorafind/Obsidian-Thino#620]
### Bug Description | BUG 描述

很久以前是memos吧，最近自动升级成thino后，发现什么都没有，这是怎么个情况?
![image](https://github.com/Quorafind/Obsidian-Thino/assets/29135984/51fb4105-9420-4127-85ed-99c256e6a28e)

**Comment by juestchaos** [comment]
你这不是 bug ，你是升级之后侧边栏不识别了，重新拖住就好

**Comment by juestchaos** [comment]
拖动的是页签，你那个是被你自己定义到了侧边栏，关闭侧边栏，使用thino原始居中的页签，再推动
