### ISSUE TITLE
Feature Request: 能否把单条卡片存储为一个单独的文件？

### ISSUE THREAD

**Issue by runningZ1** [Quorafind/Obsidian-Thino#623]
### Feature Requested | 请求的功能

能够将每条笔记内容保存为单独的文件。每一条笔记内容应该能够存储在一个独立的文件中,而不是将所有笔记内容保存在同一个文件里。这样做可以方便管理、备份和搜索单个笔记。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
可以，PRO 已支持：[多文件] (https://thino.pkmer.net/thino/02_thino-advanced/thino-multi-souce#多文件模式)
