### ISSUE TITLE
[Bug]:[Thino web] 标签创建失败

### ISSUE THREAD

**Issue by lj123454321** [Quorafind/Obsidian-Thino#627]
### Bug Description | BUG 描述

我在Thino Web上写了四条Thino，每条都有一个标签，但是很奇怪，只有最后一条的标签显示在了右边的标签列表里，也只有点击最后一条的标签才会显示相应内容，前面三条点了标签，下面都不会显示对应的Thino内容，而是空白。刷新了也没有用。
之后为了测试，我又添加了两条Thino，分别加上了新标签A和B。奇怪的是，前三条的标签如果删除重新添加，下面的提示列表会显示A和B，如果真的选择A或者B作为前三条的新标签，点击标签A或者B进去，并不会显示前三条的内容。
我以为是前三条添加标签有bug，于是复制了前三条的内容新添加，结果还是不显示相应标签，点了标签下面也没有相应内容。

### Obsidian Version | Obsidian 版本

N/A

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
可以提供输入的数据和实际问题的截图嘛？

**Comment by lj123454321** [comment]
> 可以提供输入的数据和实际问题的截图嘛？

不好意思，涉及隐私不太方面提供具体文字内容。
而且我不能稳定复现。
我试了一下好像是跟内容相关，如果替换成其他内容，哪怕是同样的标签就可以创建。成功创建该标签以后，点击标签下面会显示两条内容，但是右侧还是只会显示数量1。如果不替换内容，用一样的内容，换了一个标签，也能创建成功。后来我还是用同样内容同样标签创建，这次又成功了，而且数量也+1了，一切正常，只是还是最开始那条内容没有计数进去。
但是这些都不能复现，我删除以上内容以后重新添加，问题又都没有了，又都正常了。

**Comment by juestchaos** [comment]
已经修了，直接刷新 web 即可用
