### ISSUE TITLE
[Bug]: Thino页面不能浮窗预览文件链接

### ISSUE THREAD

**Issue by maiyajj** [Quorafind/Obsidian-Thino#631]
### Bug Description | BUG 描述

![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/70d78753-963c-414d-bf98-112275bcd3c9)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/0bfbb915-ad25-474e-93d0-cd642c95aa0a)
Thino页面Ctrl＋鼠标左键不能预览文件链接

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
更新后修复

**Comment by maiyajj** [comment]
> 更新后修复

[[#下一步行动]] 不支持
![image](https://github.com/Quorafind/Obsidian-Thino/assets/18521350/7fecf23b-7e87-4b4c-a801-dcb2577533ea)

**Comment by Quorafind** [comment]
> > 更新后修复
> 
> [[#下一步行动]] 不支持 ![image](https://private-user-images.githubusercontent.com/18521350/333001958-7fecf23b-7e87-4b4c-a801-dcb2577533ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Mjc1ODAsIm5iZiI6MTcxNjQyNzI4MCwicGF0aCI6Ii8xODUyMTM1MC8zMzMwMDE5NTgtN2ZlY2YyM2ItN2U4Ny00YjRjLWE4MDEtZGNiMjU3NzUzM2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAxMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzI0YmQwZGI1OGE4YWE4YjJhMzFiOGFiNDIzZTJkZDRiMzk0N2NhMGIyMTAxMmVlZGQ4MzAyZTFiOWYyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CuxZI6YrpDaOpXRStb_bK-NvDivvbWqpeMJMXrTU3_o)

默认不支持。也不考虑支持

**Comment by maiyajj** [comment]
> > > 更新后修复
> > 
> > 
> > [[#下一步行动]] 不支持 ![image](https://private-user-images.githubusercontent.com/18521350/333001958-7fecf23b-7e87-4b4c-a801-dcb2577533ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Mjc1ODAsIm5iZiI6MTcxNjQyNzI4MCwicGF0aCI6Ii8xODUyMTM1MC8zMzMwMDE5NTgtN2ZlY2YyM2ItN2U4Ny00YjRjLWE4MDEtZGNiMjU3NzUzM2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAxMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzI0YmQwZGI1OGE4YWE4YjJhMzFiOGFiNDIzZTJkZDRiMzk0N2NhMGIyMTAxMmVlZGQ4MzAyZTFiOWYyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CuxZI6YrpDaOpXRStb_bK-NvDivvbWqpeMJMXrTU3_o)
> 
> 默认不支持。也不考虑支持
好的，原因是啥？架构不支持吗

**Comment by Quorafind** [comment]
> > > > 更新后修复
> > > 
> > > 
> > > [[#下一步行动]] 不支持 ![image](https://private-user-images.githubusercontent.com/18521350/333001958-7fecf23b-7e87-4b4c-a801-dcb2577533ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Mjc1ODAsIm5iZiI6MTcxNjQyNzI4MCwicGF0aCI6Ii8xODUyMTM1MC8zMzMwMDE5NTgtN2ZlY2YyM2ItN2U4Ny00YjRjLWE4MDEtZGNiMjU3NzUzM2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAxMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzI0YmQwZGI1OGE4YWE4YjJhMzFiOGFiNDIzZTJkZDRiMzk0N2NhMGIyMTAxMmVlZGQ4MzAyZTFiOWYyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CuxZI6YrpDaOpXRStb_bK-NvDivvbWqpeMJMXrTU3_o)
> > 
> > 
> > 默认不支持。也不考虑支持
> > 好的，原因是啥？架构不支持吗

Obsidian 渲染器局限。

**Comment by maiyajj** [comment]
> > > > > 更新后修复
> > > > 
> > > > 
> > > > [[#下一步行动]] 不支持 ![image](https://private-user-images.githubusercontent.com/18521350/333001958-7fecf23b-7e87-4b4c-a801-dcb2577533ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Mjc1ODAsIm5iZiI6MTcxNjQyNzI4MCwicGF0aCI6Ii8xODUyMTM1MC8zMzMwMDE5NTgtN2ZlY2YyM2ItN2U4Ny00YjRjLWE4MDEtZGNiMjU3NzUzM2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAxMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzI0YmQwZGI1OGE4YWE4YjJhMzFiOGFiNDIzZTJkZDRiMzk0N2NhMGIyMTAxMmVlZGQ4MzAyZTFiOWYyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CuxZI6YrpDaOpXRStb_bK-NvDivvbWqpeMJMXrTU3_o)
> > > 
> > > 
> > > 默认不支持。也不考虑支持
> > > 好的，原因是啥？架构不支持吗
> 
> Obsidian 渲染器局限。

好的
