### ISSUE TITLE
[Bug]: Synchronization problem between Thino Web and Thino plug-in in Obsidian

### ISSUE THREAD

**Issue by lj123454321** [Quorafind/Obsidian-Thino#646]
### Bug Description | BUG 描述

我也不清楚这个是不是bug，我刚用Thino，对Thino的功能还不是太清楚。
想知道Thino Web和Obsidian里的Thino插件的记录内容是同步的吗？我在Thino插件里添加了条目，但是没有同步到Thino Web上。
我不知道是bug，还是我哪里设置有问题，还是本来就不能同步。我Thino插件的激活码确实填的就是Thino Web的账号的。

### Obsidian Version | Obsidian 版本

1.5.12

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
需要开启同步，且 thino web 和 thino 本地版链接的账号要是一个
另外同步需要你点击下刷新，不会每分钟都去请求最新的数据，防止移动端用户流量的无形消耗
另外你的描述里面只有现象，没有其他配置或者现象可以供参考

**Comment by lj123454321** [comment]
> 需要开启同步，且 thino web 和 thino 本地版链接的账号要是一个 另外同步需要你点击下刷新，不会每分钟都去请求最新的数据，防止移动端用户流量的无形消耗 另外你的描述里面只有现象，没有其他配置或者现象可以供参考

是的，因为我还搞不太懂功能，所以我只描述了现象。我检查了一下，账号是同一个，我是用的web端账号的激活码激活的插件的，我也点击了刷新，同步我不清楚在哪里开启，是下面这个吗，我已经点击过了，Obsidian也提示Saved sync token successfully. 但是我在插件里写东西还是没有同步到web上, web的东西也没有同步到插件里。
![image](https://github.com/Quorafind/Obsidian-Thino/assets/45161820/fef39657-c72e-46b6-8d26-3d9f05fe2e6b)

**Comment by lj123454321** [comment]
> 需要开启同步，且 thino web 和 thino 本地版链接的账号要是一个 另外同步需要你点击下刷新，不会每分钟都去请求最新的数据，防止移动端用户流量的无形消耗 另外你的描述里面只有现象，没有其他配置或者现象可以供参考

Web端和插件端的同步按钮我也点击过了，还是无事发生。

**Comment by juestchaos** [comment]
你可以在 pkmer 群里联系管理员，但我目前几周没有收到过任何同步异常的问题
