### ISSUE TITLE
[Bug]: After turning on multi-file mode, there is a problem with the modern mode page.

### ISSUE THREAD

**Issue by lxmwwl** [Quorafind/Obsidian-Thino#647]
### Bug Description | BUG 描述

页面宽度出现问题

### Relevant Screenshot | 相关截图

<img width="967" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/124525616/52ee5546-2404-44cb-b740-4483f17311e4">
<img width="1034" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/124525616/20ce21f5-501c-4215-8471-bed135eb1e64">

### Obsidian Version | Obsidian 版本

1.6.1

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [X] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
你需要提供你的主题，或者相关信息

**Comment by lxmwwl** [comment]
> 你需要提供你的主题，或者相关信息

我用的border主题

**Comment by lxmwwl** [comment]
> 你需要提供你的主题，或者相关信息

<img width="1247" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/124525616/126857c3-4994-45e8-bd32-0da9901ea6b9">
似乎失去了自适应大小的能力

**Comment by juestchaos** [comment]
我试了试 bord 主题，没有发生你的情况， 你可以告诉我你在 border 中设置了什么

**Comment by lxmwwl** [comment]
> 我试了试 bord 主题，没有发生你的情况， 你可以告诉我你在 border 中设置了什么

没设置啥啊，我把主题全部改成默认还是这样，css和插件也都试过了，发现你们那边不会有个情况后我又试了一下是不是文件识别的问题，然后我发现似乎对于某种写法的文件在多文件模式会出现问题。如图
![image](https://github.com/Quorafind/Obsidian-Thino/assets/124525616/bd118272-4d61-4201-8d02-69893244393d)
<img width="1086" alt="image" src="https://github.com/Quorafind/Obsidian-Thino/assets/124525616/cd7afc0e-df56-4b33-8206-e2be753bfb01">
问题似乎在这个地方，我的问题已解决。
