### ISSUE TITLE
[Bug]: 将Thino置于左右边栏时，每次新打开obsidian总是不显示

### ISSUE THREAD

**Issue by SwordBlade1** [Quorafind/Obsidian-Thino#669]
### Bug Description | BUG 描述

将Thino置于左右边栏时，每次新打开obsidian时总是不显示，需要关闭重新打开一次

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/115546841/2a85efd0-1f2e-446a-a976-d5b14d72f2ec)

### Obsidian Version | Obsidian 版本

v1.6.5最新版

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
我测试过你描述的内容，没有复现你的现象，你能提供更多信息吗？

比如你的 thino 版本，比如你还装了什么插件

这是我的重启后，thino 在侧边栏的装填

**Comment by SwordBlade1** [comment]
解决了，obsidian里有个新版thino和旧版thino，删掉旧版后就好了，非常感谢！
