### ISSUE TITLE
[Bug]: 安装后无法使用,提示“failed to find daily notes folder"

### ISSUE THREAD

**Issue by bruzyin** [Quorafind/Obsidian-Thino#672]
### Bug Description | BUG 描述

安装好插件后，不知道是否还需要有初始化的动作，新的记录找不到生成文件的文件夹路径，也不知道如何修复这个问题。

### Relevant Screenshot | 相关截图

<img width="1152" alt="1" src="https://github.com/Quorafind/Obsidian-Thino/assets/18223090/3acea700-c734-4784-b575-a51e969edac2">

### To Reproduce | 重现问题

1. 去OB第三方市场下载插件
2. 安装Thino插件
3. 按照默认设置点完
4. 尝试输入memos，看到报错。

### Obsidian Version | Obsidian 版本

2.4.47

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
检查你的obsidian 日记插件路径是否，设置了
检查你是否在 thino 中设置日记使用的插件是默认的日记插件

**Comment by bruzyin** [comment]
好的，问题已经找到了，是在系统的日记的配置里面，路径给填错了，所以没法记录到文件里去了。
