### ISSUE TITLE
[Bug]: 列表回车时无法自动生成二级列表

### ISSUE THREAD

**Issue by canlwd** [Quorafind/Obsidian-Thino#676]
### Bug Description | BUG 描述

# 列表共存问题（有序列表，无序列表，复选框等等）
# 所有端都存在（桌面端的快捷编辑器界面没有这个问题）

### Relevant Screenshot | 相关截图

截图无法展现

### To Reproduce | 重现问题

在thino界面直接在输入框输入列表

### Obsidian Version | Obsidian 版本

1.6.5

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
我无法复现这个问题，你可以告诉我你的建盘如何操作的
或者录屏，我测试了有序和无序列表都没有发现这个问题

**Comment by canlwd** [comment]
改问题已经解决了（我记得是在我反映过后第二天更新的那次解决的）
