### ISSUE TITLE
[Bug]: “~”符号快速关联thino

### ISSUE THREAD

**Issue by canlwd** [Quorafind/Obsidian-Thino#677]
### Relevant Screenshot | 相关截图

![image.png](https://obsidian--tuchuang.oss-cn-chengdu.aliyuncs.com/202407041850394.png)

### Obsidian Version | Obsidian 版本

1.6.5

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
r如果没有选中建议内容，删除 ~ 是会直接消失建议提示框的
需要提供更多条件
如图
![image](https://github.com/Quorafind/Obsidian-Thino/assets/241007/bd0768c9-888c-4334-99a7-c3dfe71087ed)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/241007/82be2a19-b70c-4018-aaf3-44a9da93fbd4)

**Comment by juestchaos** [comment]
经过用户反馈应该跟此问题类似
#678

**Comment by canlwd** [comment]
这个问题也解决了
