### ISSUE TITLE
[Bug]: 不能很好的展示缩进效果

### ISSUE THREAD

**Issue by nidongpinyinme** [Quorafind/Obsidian-Thino#685]
### Bug Description | BUG 描述

输入如下格式文字时，缩进文字显示异常
如果不使用无序列表，则无法展示缩进效果

### Relevant Screenshot | 相关截图

<img width="146" alt="image" src="https://github.com/user-attachments/assets/2a92a616-95de-4ebf-b509-ae0d1ba74d91">
<img width="196" alt="image" src="https://github.com/user-attachments/assets/1d3f70f7-6cd7-47b0-a879-fc561afb7368">

### To Reproduce | 重现问题

- 23:20 测试 
	- 缩进测试

### Obsidian Version | Obsidian 版本

Obsidian Version 1.6.5 (Installer 1.4.16)

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
你说的缩进不知道是不是如图这种效果
我这里是展示成这样的，或者你可以提供的书写，和期望样式，以及主题

![image](https://github.com/user-attachments/assets/e5a455c9-4b81-4953-b662-f646d398ea65)

**Comment by nidongpinyinme** [comment]
感谢回复。我是指字体不一致的现象。缩进后的字体和笔记中的字体是保持一致的，但是未缩进的字体似乎是单独控制的大小。
