### ISSUE TITLE
[Bug]: Thino Pro (license not showing up in pkmer user profile)

### ISSUE THREAD

**Issue by Rhinopark** [Quorafind/Obsidian-Thino#687]
### Bug Description | BUG 描述

I paid for Thino pro in Dec last year 2023. I was able to use it on one device. When I login again this month, I can't find the order in my profile. I have sent multiple emails on the support email, but no reply. Is there a support email that works? Order # 229657521. Please help fix this issue. Also if you are going for a paid model, make sure someone replies to support emails. If you need details, let me know, but please fix since I paid for the pro version and I can't use it except one device. I am posting it here hoping the developer replies since my emails went unanswered.

### Relevant Screenshot | 相关截图

N/A

### To Reproduce | 重现问题

N/A

### Obsidian Version | Obsidian 版本

1.6.7

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by Quorafind** [comment]
Sorry for not replying, I am checking your order.

**Comment by Rhinopark** [comment]
> Sorry for not replying, I am checking your order.

No worries. Thanks for taking a look and apologies for posting it here. This was my last resort :). Happy to give more information. let me know what you need from me.

**Comment by juestchaos** [comment]
Based on the order number 229657521 you provided, we have detected that your account already has an activated thino pro, quantity: 1. 

1. If you need to activate a second device, you can use the user you purchased to log in to the corresponding platform. 
2. Continue the activation process in the corresponding thino tab.

If you encounter difficulties during activation, please let me know the specific prompts you are encountering, such as being unable to log in to pkmer.net or encountering any activation-related prompts

**Comment by Rhinopark** [comment]
its working now. I had to reset my account last month so probably lost activation, but it's good now. Thanks for fixing if you had to make it work for me again. Please feel free to close this issue. Appreciate the help and support. It's a great product and hope others see the value in buying the pro version.
