### ISSUE TITLE
[FR]：能否增强一些筛选功能

### ISSUE THREAD

**Issue by lxmwwl** [Quorafind/Obsidian-Thino#692]
### Feature Requested | 请求的功能

希望能够建立筛选本周，本月之类的快速筛选的筛选式，不需要每次重新更改。

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by juestchaos** [comment]
目前你可以尝试定义筛选器，并保存来实现这个问题

**Comment by Quorafind** [comment]
2.4.51 已支持，自行去筛选器中选择
