### ISSUE TITLE
[Question]:  The @ command of the natural languages ​​dates plug-in cannot be used in the input box

### ISSUE THREAD

**Issue by LaiZeTian** [Quorafind/Obsidian-Thino#714]
### Bug Description | BUG 描述

输入框中不能使用natural languages dates插件的@命令；在之前的版本还是可以的

### Obsidian Version | Obsidian 版本

2.4.51

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
因为 Thino 有自己 date picker，你如果一定要使用 NLD 的date picker。
可以再 NLD 的插件中，寻找一个设置 trigger ，并将其切换到另外的 出发关键字，比如很多人常用 $$
