### ISSUE TITLE
[Bug]: Task 类型的 thino 无法点击复选框无法变为完成状态

### ISSUE THREAD

**Issue by ZhangQinglian** [Quorafind/Obsidian-Thino#723]
### Bug Description | BUG 描述

Task 类型的 thino 无法点击复选框无法变为完成状态

### Relevant Screenshot | 相关截图

<img width="879" alt="image" src="https://github.com/user-attachments/assets/af10f0c4-15b0-4a76-b0d2-7f2482c8c57c">

### To Reproduce | 重现问题

新建一个 task 类型的 thino，点击复选框，无法完成。

### Obsidian Version | Obsidian 版本

2.4.57

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
使用日记模式不会有这个问题，多文件的问题，会在下个版本修复

**Comment by juestchaos** [comment]
升级 2.4.58
