### ISSUE TITLE
[Bug]: 插件页面缺少修改日记插件的设置

### ISSUE THREAD

**Issue by tp1415926535** [Quorafind/Obsidian-Thino#731]
### Bug Description | BUG 描述

只有首次安装插件、或重置所有设置时，可以设定日记插件的**文件名格式**和**所在文件夹**，之后进入设置没有相关的页面可以更改。
插件版本`v2.4.58`

### Obsidian Version | Obsidian 版本

1.7.4

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
如果你使用的日记模式，日记模式是依托于 obsidian 自己的日记核心插件
需要去日记核心插件里面自行设置

**Comment by tp1415926535** [comment]
> 如果你使用的日记模式，日记模式是依托于 obsidian 自己的日记核心插件 需要去日记核心插件里面自行设置

还真是..之前没有用过这个核心插件不知道。
或许可以在Thino设置页面加个按钮，跳转到这个核心插件的日志设置页面，可以帮助我像这样不了解的。
![image](https://github.com/user-attachments/assets/fdc7018b-1b2a-4855-9f29-b794ed54aa52)
