### ISSUE TITLE
Can We have some more shortcuts

### ISSUE THREAD

**Issue by Gaaruda** [Quorafind/Obsidian-Thino#81]
Like `Cntrl+Enter` to insert the memo instead of Noteit. Just elimininating the mouse. we can also have discussion in community for any other shortcuts they want

**Comment by Quorafind** [comment]
You can use ctrl+shift+enter to noteit now because ctrl+enter has been used by Obsidian default. Will try to add a Hotkey to it

**Comment by Quorafind** [comment]
I added noteit hotkey in next version, so you can modify it as you want. But default hotkey is stll `ctrl+shift+enter`

**Comment by FelipeRearden** [comment]
> I added noteit hotkey in next version, so you can modify it as you want. But default hotkey is stll `ctrl+shift+enter`

This item will close #5 when the next version were available :)
