### ISSUE TITLE
[feature request] work with tasks plugin

### ISSUE THREAD

**Issue by pcause** [Quorafind/Obsidian-Thino#93]
it would be nice to have memo work with the tasks plugin so that the tasks hoykey brings up tghe form and then inserts the task text and icons in the memo

**Comment by Quorafind** [comment]
Maybe need the Tasks exposed a api to get the tasks generate from modal.

**Comment by pcause** [comment]
When I use the shortcut key to try to add a task, it isn't recognized if I am in the memo sidebar.  does that require an API?  Just getting that to work might be enough.

**Comment by pcause** [comment]
I found the problem.  When you insert the textyou insert a time ahead of the text and this causes the tasks plugin to not recognize the memo as a task.

The task looks sort of like:

- 08:34 - [ ] #tasks some text ....

and that leading - and time are the issue.

**Comment by Quorafind** [comment]
Now you can save task into single file mode. That means you created a whole file for Thino(Obsidian Memos). More information: https://thino.pkmer.net/en/thino/02_thino-advanced/thino-multi-souce/
